$axure.loadCurrentPage({
  "url":"about_company.html",
  "generationDate":new Date(1444814346257.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f0b4d7077c534cb89bbd4531fa22f360",
    "type":"Axure:Page",
    "name":"About Company",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ded1daa268dd427a906e88e26fa75bc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":1298},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af52d2165a254cbb88cf519bb6d26638",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":92},
                "size":{
                  "width":720,
                  "height":1298},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about_company/u0.png"}},
{
          "id":"34af48979ac94a8299185bbd1876ccef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e045ac3e43e24a0292525427b4ee2c76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"0c201355ee3f41f88e7015dea6687f78",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"c5849ee6ba6a4b20bc2f458a9244b2e8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":14},
            "size":{
              "width":69,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04436debf45d4b4787ef03c5bdf8506e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":14},
                "size":{
                  "width":69,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 UserConter-my",
                      "target":{
                        "targetType":"page",
                        "url":"userconter-my.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"71c90dd74c1b4e8b95c2af4c25300023",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "location":{
              "x":280,
              "y":22},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"278f88f72c6b4c1a858c7ac5253ae236",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "location":{
                  "x":280,
                  "y":22},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da94a9e3eccf48b3b0e478806c27ffcf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":131},
            "size":{
              "width":720,
              "height":864},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d15f904e1c1b4ad3b53a1041bcc5c3c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":131},
                "size":{
                  "width":720,
                  "height":864},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about_company/u9.png"}},
{
          "id":"6e23450740da45129513c998ca301028",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "lineSpacing":"96px",
            "location":{
              "x":27,
              "y":131},
            "size":{
              "width":541,
              "height":864}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a90e66e27a5e48c195ee1a2bd743a6c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"96px",
                "location":{
                  "x":27,
                  "y":131},
                "size":{
                  "width":541,
                  "height":864}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 About Company edit",
                      "target":{
                        "targetType":"page",
                        "url":"about_company_edit.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9730b8fc15a4f209e5e979004b99259",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":125},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"b45740db20f84cbc9b33eff12569b618",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":221},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"6855310bd55d436992a21dfe43efc43c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":317},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"de0b0be50066413d8ccc88aa020e7953",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":413},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"e6abf341449e4cddb66a707f80d8736d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":509},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"c0f641e42f414fb8a50340bb98e99d8b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":605},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"c9c450b5b9e34a44af8857ae4fd9294d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":701},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"a409ce81f662471a94d808f19695401a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":798},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"7c191dbe6632421fa1ac13974d16df98",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":894},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"107472ccdaf24e4cb4623482d9616299",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":991},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"ec501e0f9d064b64b8706a497c311828",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":685,
              "y":259},
            "size":{
              "width":16,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5470211d739c4acd88bbc223e4baae22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":685,
                  "y":259},
                "size":{
                  "width":16,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1b5851e37ec45208763a1a9d20fe403",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":685,
              "y":163},
            "size":{
              "width":16,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5816f8f36f4d4e21981f2f49283c0146",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":685,
                  "y":163},
                "size":{
                  "width":16,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"496213364ec3406ba3b775a008872916",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":685,
              "y":355},
            "size":{
              "width":16,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b679a0bd71dc4b9d95e6daf81442d019",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":685,
                  "y":355},
                "size":{
                  "width":16,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff2f47a9179b450ea71b3b6dc4f4c58f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":685,
              "y":453},
            "size":{
              "width":16,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22a6c708aa1c4dd088e4ffae4251a319",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":685,
                  "y":453},
                "size":{
                  "width":16,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"515e633da66b49d7b949a3b8b8ce841c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":685,
              "y":547},
            "size":{
              "width":16,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b28cf7606002498f98ff34a96270952b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":685,
                  "y":547},
                "size":{
                  "width":16,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0cfb3fbcfe57463e952b859f79824567",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":685,
              "y":645},
            "size":{
              "width":16,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28dbb96c5cfc4db287c98f226af7194e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":685,
                  "y":645},
                "size":{
                  "width":16,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4114e7ddb78840cc826beed68c20d169",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":685,
              "y":735},
            "size":{
              "width":16,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fe367f60e3e41a798494ac097a3a9c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":685,
                  "y":735},
                "size":{
                  "width":16,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cab9669cd0294a6ea74e4b9d6fb5d50b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":685,
              "y":835},
            "size":{
              "width":16,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2e17e3e81a34a2b80b6da473652cfb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":685,
                  "y":835},
                "size":{
                  "width":16,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"992220f725ca43a9b6b3cf0bd2cc2ed1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":685,
              "y":933},
            "size":{
              "width":16,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a56a4f9155054446a57eb0ef5d4e5d70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":685,
                  "y":933},
                "size":{
                  "width":16,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"32f3e6cb0f034bae8b1f1af0af01963b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1026},
            "size":{
              "width":720,
              "height":306},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9af0a7e3a5a643d2aec3fc73c249a361",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1026},
                "size":{
                  "width":720,
                  "height":306},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about_company/u41.png"}},
{
          "id":"001d137cee104829beb565d56c5b9136",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1021},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"356438d9c97b49cd9c1f20877965fb09",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "lineSpacing":"48px",
            "location":{
              "x":29,
              "y":1049},
            "size":{
              "width":658,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec851997a387497393a499f24c86b3e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"48px",
                "location":{
                  "x":29,
                  "y":1049},
                "size":{
                  "width":658,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc428788118a4df888ca01336cee1d1d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1328},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ded1daa268dd427a906e88e26fa75bc3":{
      "scriptId":"u0"},
    "af52d2165a254cbb88cf519bb6d26638":{
      "scriptId":"u1"},
    "34af48979ac94a8299185bbd1876ccef":{
      "scriptId":"u2"},
    "e045ac3e43e24a0292525427b4ee2c76":{
      "scriptId":"u3"},
    "0c201355ee3f41f88e7015dea6687f78":{
      "scriptId":"u4"},
    "c5849ee6ba6a4b20bc2f458a9244b2e8":{
      "scriptId":"u5"},
    "04436debf45d4b4787ef03c5bdf8506e":{
      "scriptId":"u6"},
    "71c90dd74c1b4e8b95c2af4c25300023":{
      "scriptId":"u7"},
    "278f88f72c6b4c1a858c7ac5253ae236":{
      "scriptId":"u8"},
    "da94a9e3eccf48b3b0e478806c27ffcf":{
      "scriptId":"u9"},
    "d15f904e1c1b4ad3b53a1041bcc5c3c6":{
      "scriptId":"u10"},
    "6e23450740da45129513c998ca301028":{
      "scriptId":"u11"},
    "a90e66e27a5e48c195ee1a2bd743a6c9":{
      "scriptId":"u12"},
    "f9730b8fc15a4f209e5e979004b99259":{
      "scriptId":"u13"},
    "b45740db20f84cbc9b33eff12569b618":{
      "scriptId":"u14"},
    "6855310bd55d436992a21dfe43efc43c":{
      "scriptId":"u15"},
    "de0b0be50066413d8ccc88aa020e7953":{
      "scriptId":"u16"},
    "e6abf341449e4cddb66a707f80d8736d":{
      "scriptId":"u17"},
    "c0f641e42f414fb8a50340bb98e99d8b":{
      "scriptId":"u18"},
    "c9c450b5b9e34a44af8857ae4fd9294d":{
      "scriptId":"u19"},
    "a409ce81f662471a94d808f19695401a":{
      "scriptId":"u20"},
    "7c191dbe6632421fa1ac13974d16df98":{
      "scriptId":"u21"},
    "107472ccdaf24e4cb4623482d9616299":{
      "scriptId":"u22"},
    "ec501e0f9d064b64b8706a497c311828":{
      "scriptId":"u23"},
    "5470211d739c4acd88bbc223e4baae22":{
      "scriptId":"u24"},
    "b1b5851e37ec45208763a1a9d20fe403":{
      "scriptId":"u25"},
    "5816f8f36f4d4e21981f2f49283c0146":{
      "scriptId":"u26"},
    "496213364ec3406ba3b775a008872916":{
      "scriptId":"u27"},
    "b679a0bd71dc4b9d95e6daf81442d019":{
      "scriptId":"u28"},
    "ff2f47a9179b450ea71b3b6dc4f4c58f":{
      "scriptId":"u29"},
    "22a6c708aa1c4dd088e4ffae4251a319":{
      "scriptId":"u30"},
    "515e633da66b49d7b949a3b8b8ce841c":{
      "scriptId":"u31"},
    "b28cf7606002498f98ff34a96270952b":{
      "scriptId":"u32"},
    "0cfb3fbcfe57463e952b859f79824567":{
      "scriptId":"u33"},
    "28dbb96c5cfc4db287c98f226af7194e":{
      "scriptId":"u34"},
    "4114e7ddb78840cc826beed68c20d169":{
      "scriptId":"u35"},
    "2fe367f60e3e41a798494ac097a3a9c1":{
      "scriptId":"u36"},
    "cab9669cd0294a6ea74e4b9d6fb5d50b":{
      "scriptId":"u37"},
    "b2e17e3e81a34a2b80b6da473652cfb0":{
      "scriptId":"u38"},
    "992220f725ca43a9b6b3cf0bd2cc2ed1":{
      "scriptId":"u39"},
    "a56a4f9155054446a57eb0ef5d4e5d70":{
      "scriptId":"u40"},
    "32f3e6cb0f034bae8b1f1af0af01963b":{
      "scriptId":"u41"},
    "9af0a7e3a5a643d2aec3fc73c249a361":{
      "scriptId":"u42"},
    "001d137cee104829beb565d56c5b9136":{
      "scriptId":"u43"},
    "356438d9c97b49cd9c1f20877965fb09":{
      "scriptId":"u44"},
    "ec851997a387497393a499f24c86b3e3":{
      "scriptId":"u45"},
    "fc428788118a4df888ca01336cee1d1d":{
      "scriptId":"u46"}}});