$axure.loadCurrentPage({
  "url":"register3.html",
  "generationDate":new Date(1444814341270.81),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"27580218b4e4421d8704f9a0db0f8acb",
    "type":"Axure:Page",
    "name":"register3",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"823fcf03611d41c298bbf5b9b10d6df1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":86},
            "size":{
              "width":720,
              "height":1094},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8cc170da71c47548a037887260b23ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":86},
                "size":{
                  "width":720,
                  "height":1094},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u0.png"}},
{
          "id":"c66b160831274c8cab6693ea758d1423",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2566c646811d4d02a9c266a63741daa6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"e6fd4f6b1f294d6fafe68d1bb292eefe",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"510837e482bc4113b8270297e1d69d40",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":14},
            "size":{
              "width":69,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e04fe6706c84b8c91e8407d9e73b45f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":14},
                "size":{
                  "width":69,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 login",
                      "target":{
                        "targetType":"page",
                        "url":"login.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"fa6e7c24f6204d42b995abf275b36b06",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "location":{
              "x":279.5,
              "y":22},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ab363e517de43d2aeaf69a7e9b597f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "location":{
                  "x":279.5,
                  "y":22},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc696dd7f0e4433fb606d2cf7995867b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":30,
              "y":565},
            "size":{
              "width":660,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4baa941dc3742b098812f300d15eeeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":30,
                  "y":565},
                "size":{
                  "width":660,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDBDBDB},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u17.png"}},
{
          "id":"32279b756c5645bda4aec652ca8c37c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":125,
              "y":587},
            "size":{
              "width":479,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c60a836d7b0472a8ee7d304a85366ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":125,
                  "y":587},
                "size":{
                  "width":479,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e85269d347d4f59943e9fad1ca80c90",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"40px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF339900,
              "opacity":1},
            "location":{
              "x":120,
              "y":333},
            "size":{
              "width":481,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"938ca6456e8f450683cbe543661845b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"40px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF339900,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":333},
                "size":{
                  "width":481,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3a8b8e079c04c79b178134556e20761",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"55px",
            "location":{
              "x":141,
              "y":405},
            "size":{
              "width":438,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be27084e31c6425b8dd50df1afdc545d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"55px",
                "location":{
                  "x":141,
                  "y":405},
                "size":{
                  "width":438,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"72d404286363405a987c18e273cbc139",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":306,
              "y":198},
            "size":{
              "width":107,
              "height":107}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a560653e7b5e417cb72102819306cbd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":306,
                  "y":198},
                "size":{
                  "width":107,
                  "height":107}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/register3/u17.png"}},
{
          "id":"fa88af8074054fc5a79ddbd0d1228356",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":30,
              "y":699},
            "size":{
              "width":660,
              "height":96},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a65d078c77a443bbf4399d516be6f55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":30,
                  "y":699},
                "size":{
                  "width":660,
                  "height":96},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/register3/u19.png"}},
{
          "id":"736d1f0247fb41e593f1408d2a9d7464",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":140,
              "y":721},
            "size":{
              "width":441,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e13100c02244acf99ded00625aad247",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":721},
                "size":{
                  "width":441,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 About Company",
                      "target":{
                        "targetType":"page",
                        "url":"about_company.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "823fcf03611d41c298bbf5b9b10d6df1":{
      "scriptId":"u0"},
    "a8cc170da71c47548a037887260b23ee":{
      "scriptId":"u1"},
    "c66b160831274c8cab6693ea758d1423":{
      "scriptId":"u2"},
    "2566c646811d4d02a9c266a63741daa6":{
      "scriptId":"u3"},
    "e6fd4f6b1f294d6fafe68d1bb292eefe":{
      "scriptId":"u4"},
    "510837e482bc4113b8270297e1d69d40":{
      "scriptId":"u5"},
    "1e04fe6706c84b8c91e8407d9e73b45f":{
      "scriptId":"u6"},
    "fa6e7c24f6204d42b995abf275b36b06":{
      "scriptId":"u7"},
    "5ab363e517de43d2aeaf69a7e9b597f9":{
      "scriptId":"u8"},
    "fc696dd7f0e4433fb606d2cf7995867b":{
      "scriptId":"u9"},
    "d4baa941dc3742b098812f300d15eeeb":{
      "scriptId":"u10"},
    "32279b756c5645bda4aec652ca8c37c6":{
      "scriptId":"u11"},
    "7c60a836d7b0472a8ee7d304a85366ab":{
      "scriptId":"u12"},
    "4e85269d347d4f59943e9fad1ca80c90":{
      "scriptId":"u13"},
    "938ca6456e8f450683cbe543661845b7":{
      "scriptId":"u14"},
    "b3a8b8e079c04c79b178134556e20761":{
      "scriptId":"u15"},
    "be27084e31c6425b8dd50df1afdc545d":{
      "scriptId":"u16"},
    "72d404286363405a987c18e273cbc139":{
      "scriptId":"u17"},
    "a560653e7b5e417cb72102819306cbd2":{
      "scriptId":"u18"},
    "fa88af8074054fc5a79ddbd0d1228356":{
      "scriptId":"u19"},
    "4a65d078c77a443bbf4399d516be6f55":{
      "scriptId":"u20"},
    "736d1f0247fb41e593f1408d2a9d7464":{
      "scriptId":"u21"},
    "9e13100c02244acf99ded00625aad247":{
      "scriptId":"u22"}}});