$axure.loadCurrentPage({
  "url":"products-buy-help.html",
  "generationDate":new Date(1444814342648.89),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"52c50940efe44b6d99f31a48345fbac8",
    "type":"Axure:Page",
    "name":"Products-Buy-help",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dc3722520ca84d3ba83eb55d10bef0d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":96},
            "size":{
              "width":720,
              "height":1084},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d933343411e54a368ef1039f4a43b36f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":96},
                "size":{
                  "width":720,
                  "height":1084},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/products-buy-help/u0.png"}},
{
          "id":"2dbba10ec7cc4302bb07fae5729aa151",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":126},
            "size":{
              "width":720,
              "height":709},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35211120718e4e5b97d460480936a34d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":126},
                "size":{
                  "width":720,
                  "height":709},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/products-buy-help/u2.png"}},
{
          "id":"9ddc424fdf434b0a9a2d17f9f4375998",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cb7b5d024254b67ba9b29d08f5795c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"d42e73ea5a724bbeb15b6dbd56c153cc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"ea0c3f39eecf4264b0c003b46013e0a4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":14},
            "size":{
              "width":69,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ee609d943c44ea6b9c90ac90e364682",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":14},
                "size":{
                  "width":69,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Products-Buy-content",
                      "target":{
                        "targetType":"page",
                        "url":"products-buy-content.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"8c1987ea3e054c039719a6049522e8e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "location":{
              "x":280,
              "y":22},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9649a7f1df049f79829211ec820ddfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "location":{
                  "x":280,
                  "y":22},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b345f71b16c94a819730db1737c92eec",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":122},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"4a5d8859303c4bc6ab819e106784d23b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":830},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"c7ac8a3c49c34d0690319d23b4f9b658",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "lineSpacing":"72px",
            "location":{
              "x":38,
              "y":146},
            "size":{
              "width":544,
              "height":659}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52a3f238396749d185b74c3aa5706329",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "lineSpacing":"72px",
                "location":{
                  "x":38,
                  "y":146},
                "size":{
                  "width":544,
                  "height":659}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "dc3722520ca84d3ba83eb55d10bef0d0":{
      "scriptId":"u0"},
    "d933343411e54a368ef1039f4a43b36f":{
      "scriptId":"u1"},
    "2dbba10ec7cc4302bb07fae5729aa151":{
      "scriptId":"u2"},
    "35211120718e4e5b97d460480936a34d":{
      "scriptId":"u3"},
    "9ddc424fdf434b0a9a2d17f9f4375998":{
      "scriptId":"u4"},
    "9cb7b5d024254b67ba9b29d08f5795c8":{
      "scriptId":"u5"},
    "d42e73ea5a724bbeb15b6dbd56c153cc":{
      "scriptId":"u6"},
    "ea0c3f39eecf4264b0c003b46013e0a4":{
      "scriptId":"u7"},
    "0ee609d943c44ea6b9c90ac90e364682":{
      "scriptId":"u8"},
    "8c1987ea3e054c039719a6049522e8e2":{
      "scriptId":"u9"},
    "c9649a7f1df049f79829211ec820ddfe":{
      "scriptId":"u10"},
    "b345f71b16c94a819730db1737c92eec":{
      "scriptId":"u11"},
    "4a5d8859303c4bc6ab819e106784d23b":{
      "scriptId":"u12"},
    "c7ac8a3c49c34d0690319d23b4f9b658":{
      "scriptId":"u13"},
    "52a3f238396749d185b74c3aa5706329":{
      "scriptId":"u14"}}});