$axure.loadCurrentPage({
  "url":"about_user.html",
  "generationDate":new Date(1444814346125.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1986daad12694572a142922e35324b30",
    "type":"Axure:Page",
    "name":"About User",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2e8a5316487f4cbf8ed620cff7b555c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":1088},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d7fc236491c40db8a528dea96ed643b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":92},
                "size":{
                  "width":720,
                  "height":1088},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search/u0.png"}},
{
          "id":"a2dd9eaaa784427eac43795f6532f52d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8b46a51c2464a98a4d0fd791c6108d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"919ce4d4fbfe4ea2922af9bea6facf8c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"36af2bbc771343b9941bdb677bfa19f3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":14},
            "size":{
              "width":69,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a049a78d39e4c3cb1edf3273cbfb3eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":14},
                "size":{
                  "width":69,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 UserConter-my",
                      "target":{
                        "targetType":"page",
                        "url":"userconter-my.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"07f000af20284d309df31060f09ea27b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "location":{
              "x":280,
              "y":22},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"781c5e66d18b4e1f80537c7223e240b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "location":{
                  "x":280,
                  "y":22},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3c14e59794d416baa2675d8eaddec7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":131},
            "size":{
              "width":720,
              "height":574},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07569f53b6664e5b9d03abdef824bf7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":131},
                "size":{
                  "width":720,
                  "height":574},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about_user/u9.png"}},
{
          "id":"82ab29e8c123483ba59917f9aa1d6742",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "lineSpacing":"96px",
            "location":{
              "x":27,
              "y":131},
            "size":{
              "width":485,
              "height":576}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41d1eac459a24244ad1f7d769387ec91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"96px",
                "location":{
                  "x":27,
                  "y":131},
                "size":{
                  "width":485,
                  "height":576}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01342ff845ef41459eb43e691168aca7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":125},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"f981778036bf45baa6f92f928aec10d0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":221},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"cb37ceb890574215b9e81e403ce941a8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":317},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"410a8609970c4c829fad3d283d47e5b2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":413},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"08f224b8480f49bbb53d428b82e0bcb8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":509},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"b97aa3f6c6e94ba887c6c2131f5ed42e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":605},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"60512d9826514e96b8ff931f49105119",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":701},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"8bed3c484fee42b5b2012321befdaa6e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":649,
              "y":635},
            "size":{
              "width":45,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08c5545250764a80bdb83c94332b66b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":649,
                  "y":635},
                "size":{
                  "width":45,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about_user/u20.png"}},
{
          "id":"2fbf5885d2ad4d5a825f4b55e15b4a6e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":649,
              "y":540},
            "size":{
              "width":45,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95108235a62b465d809c8d9174372811",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":649,
                  "y":540},
                "size":{
                  "width":45,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about_user/u20.png"}},
{
          "id":"296a8d2231fe4f0bb065dd3efe483bb2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":649,
              "y":347},
            "size":{
              "width":45,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7741ad1ff45a4bbb8fd21f40ad4ef06c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":649,
                  "y":347},
                "size":{
                  "width":45,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about_user/u20.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "2e8a5316487f4cbf8ed620cff7b555c8":{
      "scriptId":"u0"},
    "3d7fc236491c40db8a528dea96ed643b":{
      "scriptId":"u1"},
    "a2dd9eaaa784427eac43795f6532f52d":{
      "scriptId":"u2"},
    "a8b46a51c2464a98a4d0fd791c6108d9":{
      "scriptId":"u3"},
    "919ce4d4fbfe4ea2922af9bea6facf8c":{
      "scriptId":"u4"},
    "36af2bbc771343b9941bdb677bfa19f3":{
      "scriptId":"u5"},
    "8a049a78d39e4c3cb1edf3273cbfb3eb":{
      "scriptId":"u6"},
    "07f000af20284d309df31060f09ea27b":{
      "scriptId":"u7"},
    "781c5e66d18b4e1f80537c7223e240b0":{
      "scriptId":"u8"},
    "e3c14e59794d416baa2675d8eaddec7f":{
      "scriptId":"u9"},
    "07569f53b6664e5b9d03abdef824bf7f":{
      "scriptId":"u10"},
    "82ab29e8c123483ba59917f9aa1d6742":{
      "scriptId":"u11"},
    "41d1eac459a24244ad1f7d769387ec91":{
      "scriptId":"u12"},
    "01342ff845ef41459eb43e691168aca7":{
      "scriptId":"u13"},
    "f981778036bf45baa6f92f928aec10d0":{
      "scriptId":"u14"},
    "cb37ceb890574215b9e81e403ce941a8":{
      "scriptId":"u15"},
    "410a8609970c4c829fad3d283d47e5b2":{
      "scriptId":"u16"},
    "08f224b8480f49bbb53d428b82e0bcb8":{
      "scriptId":"u17"},
    "b97aa3f6c6e94ba887c6c2131f5ed42e":{
      "scriptId":"u18"},
    "60512d9826514e96b8ff931f49105119":{
      "scriptId":"u19"},
    "8bed3c484fee42b5b2012321befdaa6e":{
      "scriptId":"u20"},
    "08c5545250764a80bdb83c94332b66b8":{
      "scriptId":"u21"},
    "2fbf5885d2ad4d5a825f4b55e15b4a6e":{
      "scriptId":"u22"},
    "95108235a62b465d809c8d9174372811":{
      "scriptId":"u23"},
    "296a8d2231fe4f0bb065dd3efe483bb2":{
      "scriptId":"u24"},
    "7741ad1ff45a4bbb8fd21f40ad4ef06c":{
      "scriptId":"u25"}}});