$axure.loadCurrentPage({
  "url":"edit_password.html",
  "generationDate":new Date(1444814346662.12),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1f8e2b7080f44b7f83b9785a391d0fa1",
    "type":"Axure:Page",
    "name":"Edit Password",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5ad5244a4d0f479fbd97ca3168ce9f64",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":86},
            "size":{
              "width":720,
              "height":1094},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"268ae3278a014d34be8bd58d79261c22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":86},
                "size":{
                  "width":720,
                  "height":1094},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u0.png"}},
{
          "id":"da738abf4a24457aa8143926d5619874",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fea9f63d72724958a1a4e079c6731df2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"fc53d36fb0cf428b913d8e571607b24a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"aac3bee2a0484cc9ad1baf504919c3dd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":14},
            "size":{
              "width":69,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85e8b8c8eb2047ae92bcb1be2b123cfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":14},
                "size":{
                  "width":69,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 UserConter-my",
                      "target":{
                        "targetType":"page",
                        "url":"userconter-my.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"01260e7434064d2f801f95322ac1ddc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "location":{
              "x":239.5,
              "y":22},
            "size":{
              "width":241,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0be1a8913df470594f445ab94c4c9d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "location":{
                  "x":239.5,
                  "y":22},
                "size":{
                  "width":241,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c37302275bd48c98bb2d3e69b09bb3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":37,
              "y":152},
            "size":{
              "width":410,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"842072d5753c4af2977e81859979705a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":37,
                  "y":152},
                "size":{
                  "width":410,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2cf5da0a85a141a184b8bbf8deae5006",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":235},
            "size":{
              "width":360,
              "height":96},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c511ad075339448f9c2a04cc512d82cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":235},
                "size":{
                  "width":360,
                  "height":96},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDBDBDB},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/register/u13.png"}},
{
          "id":"07db39d9fc594474b156117a964391cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":59,
              "y":263},
            "size":{
              "width":183,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"438b52acee2f4cb3826f651a11d08930",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":59,
                  "y":263},
                "size":{
                  "width":183,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7cd3dd908e6b4b188d41b62285a483de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":30,
              "y":385},
            "size":{
              "width":660,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbc4b610d05e46d88df33e46e2b24060",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":30,
                  "y":385},
                "size":{
                  "width":660,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDBDBDB},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/register/u17.png"}},
{
          "id":"a475cfecf42249ac9840cb7f56c67cdb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":300,
              "y":407},
            "size":{
              "width":121,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb6003cadd5a49cca5239a1eada157d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":407},
                "size":{
                  "width":121,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7afa62481f764987beb31e32581ab588",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF30A9EE},
            "location":{
              "x":410,
              "y":235},
            "size":{
              "width":280,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"504346bc96834f4189f1262f2d56b6ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF30A9EE},
                "location":{
                  "x":410,
                  "y":235},
                "size":{
                  "width":280,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDBDBDB},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/register/u23.png"}},
{
          "id":"bb3cd83a2cd84809983647d8ce2a095d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":443,
              "y":263},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e15276036f6d45ca89889e0a33f6db96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":443,
                  "y":263},
                "size":{
                  "width":214,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0cf1b3e2f7cb4d9595c0b17d11ab756c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":30,
              "y":514},
            "size":{
              "width":660,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86ef6d7127584b6786972ddf706b9b18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":30,
                  "y":514},
                "size":{
                  "width":660,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDBDBDB},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u17.png"}},
{
          "id":"2c39785f72ec490e8e97b95c353bc5fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":300,
              "y":536},
            "size":{
              "width":121,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfea261f571d4d0e9ae5a399f4eb0e49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":536},
                "size":{
                  "width":121,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Edit Password2",
                      "target":{
                        "targetType":"page",
                        "url":"edit_password2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "5ad5244a4d0f479fbd97ca3168ce9f64":{
      "scriptId":"u0"},
    "268ae3278a014d34be8bd58d79261c22":{
      "scriptId":"u1"},
    "da738abf4a24457aa8143926d5619874":{
      "scriptId":"u2"},
    "fea9f63d72724958a1a4e079c6731df2":{
      "scriptId":"u3"},
    "fc53d36fb0cf428b913d8e571607b24a":{
      "scriptId":"u4"},
    "aac3bee2a0484cc9ad1baf504919c3dd":{
      "scriptId":"u5"},
    "85e8b8c8eb2047ae92bcb1be2b123cfa":{
      "scriptId":"u6"},
    "01260e7434064d2f801f95322ac1ddc4":{
      "scriptId":"u7"},
    "f0be1a8913df470594f445ab94c4c9d3":{
      "scriptId":"u8"},
    "4c37302275bd48c98bb2d3e69b09bb3d":{
      "scriptId":"u9"},
    "842072d5753c4af2977e81859979705a":{
      "scriptId":"u10"},
    "2cf5da0a85a141a184b8bbf8deae5006":{
      "scriptId":"u11"},
    "c511ad075339448f9c2a04cc512d82cc":{
      "scriptId":"u12"},
    "07db39d9fc594474b156117a964391cd":{
      "scriptId":"u13"},
    "438b52acee2f4cb3826f651a11d08930":{
      "scriptId":"u14"},
    "7cd3dd908e6b4b188d41b62285a483de":{
      "scriptId":"u15"},
    "cbc4b610d05e46d88df33e46e2b24060":{
      "scriptId":"u16"},
    "a475cfecf42249ac9840cb7f56c67cdb":{
      "scriptId":"u17"},
    "eb6003cadd5a49cca5239a1eada157d6":{
      "scriptId":"u18"},
    "7afa62481f764987beb31e32581ab588":{
      "scriptId":"u19"},
    "504346bc96834f4189f1262f2d56b6ac":{
      "scriptId":"u20"},
    "bb3cd83a2cd84809983647d8ce2a095d":{
      "scriptId":"u21"},
    "e15276036f6d45ca89889e0a33f6db96":{
      "scriptId":"u22"},
    "0cf1b3e2f7cb4d9595c0b17d11ab756c":{
      "scriptId":"u23"},
    "86ef6d7127584b6786972ddf706b9b18":{
      "scriptId":"u24"},
    "2c39785f72ec490e8e97b95c353bc5fa":{
      "scriptId":"u25"},
    "cfea261f571d4d0e9ae5a399f4eb0e49":{
      "scriptId":"u26"}}});