$axure.loadCurrentPage({
  "url":"edit_password3.html",
  "generationDate":new Date(1444814346803.13),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6db7f7fd2f9b4f33b714835b1df278da",
    "type":"Axure:Page",
    "name":"Edit Password3",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dbcc4bc99eb3411cbc204bd56a106fcb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":86},
            "size":{
              "width":720,
              "height":1094},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0913736327e149c9b6bc3d6ef46ebe8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":86},
                "size":{
                  "width":720,
                  "height":1094},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u0.png"}},
{
          "id":"4e8169451feb40dea9c80a0132c9eb2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74d917f0905045a4ae341fbdb3773afc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"c70d4cab07ff48ad84a92825d42eea8f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"a50ccc4f912e4d1ebaa03466fa7975c2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":14},
            "size":{
              "width":69,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c5bbfdf90734629b64cf105f45ac376",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":14},
                "size":{
                  "width":69,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Edit Password2",
                      "target":{
                        "targetType":"page",
                        "url":"edit_password2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"9b5d6baa357d44c599b2f3b40e6ab5e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "location":{
              "x":240,
              "y":22},
            "size":{
              "width":241,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"612d06036e36458caa75af560764254b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "location":{
                  "x":240,
                  "y":22},
                "size":{
                  "width":241,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16a1b3ed91674479bb55ec32a3e50378",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":30,
              "y":501},
            "size":{
              "width":660,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dc00d82771246b0882b3538b80ac321",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":30,
                  "y":501},
                "size":{
                  "width":660,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDBDBDB},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u17.png"}},
{
          "id":"649198ca939c464183552c4747080918",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":240,
              "y":523},
            "size":{
              "width":241,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a49cb5ef55a04faab597435a09ae3482",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":240,
                  "y":523},
                "size":{
                  "width":241,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 UserConter-orders",
                      "target":{
                        "targetType":"page",
                        "url":"userconter-orders.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29601a45c52345ffaec99f34c62971e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"40px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF339900,
              "opacity":1},
            "location":{
              "x":220,
              "y":333},
            "size":{
              "width":281,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7209519c0f6c49e3816c1e6976d1d019",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"40px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF339900,
                  "opacity":1},
                "location":{
                  "x":220,
                  "y":333},
                "size":{
                  "width":281,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fdbcdb7e10804ecf9452013fe27a860f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"55px",
            "location":{
              "x":170,
              "y":405},
            "size":{
              "width":380,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef828da0be944b59a53db9ba2e1a862a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"55px",
                "location":{
                  "x":170,
                  "y":405},
                "size":{
                  "width":380,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1460ffb45be14c1881054602f04da0f3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":306,
              "y":198},
            "size":{
              "width":107,
              "height":107}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2d6b56044fa448f8e67c12141f33a0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":306,
                  "y":198},
                "size":{
                  "width":107,
                  "height":107}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/register3/u17.png"}},
{
          "id":"5d80f8c4e6824868a01304dd352a08d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":30,
              "y":635},
            "size":{
              "width":660,
              "height":96},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4a67ba4fd4a4564a205d5ac451907ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":30,
                  "y":635},
                "size":{
                  "width":660,
                  "height":96},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/register3/u19.png"}},
{
          "id":"a7cbe2415f9c46bd80c54e684a645c4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":140,
              "y":657},
            "size":{
              "width":479,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4c082150e3349cf802b826c9cecca84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":140,
                  "y":657},
                "size":{
                  "width":479,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "dbcc4bc99eb3411cbc204bd56a106fcb":{
      "scriptId":"u0"},
    "0913736327e149c9b6bc3d6ef46ebe8d":{
      "scriptId":"u1"},
    "4e8169451feb40dea9c80a0132c9eb2e":{
      "scriptId":"u2"},
    "74d917f0905045a4ae341fbdb3773afc":{
      "scriptId":"u3"},
    "c70d4cab07ff48ad84a92825d42eea8f":{
      "scriptId":"u4"},
    "a50ccc4f912e4d1ebaa03466fa7975c2":{
      "scriptId":"u5"},
    "6c5bbfdf90734629b64cf105f45ac376":{
      "scriptId":"u6"},
    "9b5d6baa357d44c599b2f3b40e6ab5e3":{
      "scriptId":"u7"},
    "612d06036e36458caa75af560764254b":{
      "scriptId":"u8"},
    "16a1b3ed91674479bb55ec32a3e50378":{
      "scriptId":"u9"},
    "0dc00d82771246b0882b3538b80ac321":{
      "scriptId":"u10"},
    "649198ca939c464183552c4747080918":{
      "scriptId":"u11"},
    "a49cb5ef55a04faab597435a09ae3482":{
      "scriptId":"u12"},
    "29601a45c52345ffaec99f34c62971e1":{
      "scriptId":"u13"},
    "7209519c0f6c49e3816c1e6976d1d019":{
      "scriptId":"u14"},
    "fdbcdb7e10804ecf9452013fe27a860f":{
      "scriptId":"u15"},
    "ef828da0be944b59a53db9ba2e1a862a":{
      "scriptId":"u16"},
    "1460ffb45be14c1881054602f04da0f3":{
      "scriptId":"u17"},
    "d2d6b56044fa448f8e67c12141f33a0a":{
      "scriptId":"u18"},
    "5d80f8c4e6824868a01304dd352a08d0":{
      "scriptId":"u19"},
    "e4a67ba4fd4a4564a205d5ac451907ff":{
      "scriptId":"u20"},
    "a7cbe2415f9c46bd80c54e684a645c4d":{
      "scriptId":"u21"},
    "f4c082150e3349cf802b826c9cecca84":{
      "scriptId":"u22"}}});