$axure.loadCurrentPage({
  "url":"release-buy.html",
  "generationDate":new Date(1444814343339.93),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5d37e6d08a0d49e5b1fff5d0c11578f7",
    "type":"Axure:Page",
    "name":"release-buy",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"13f8440ace54451fa2eae3284da8ae10",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":100},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0de0b105898c4906bcbe7ddfbe16be47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":92},
                "size":{
                  "width":720,
                  "height":100},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/release-buy/u0.png"}},
{
          "id":"72bc92906fc34524b399f09898f8d4b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c870aab57195496cbb24d309007e6020",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"da8317aad3f8401ba9abde14b79fe169",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"42c3865a5fa249e3b2fc778d1ea2c4f5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":14},
            "size":{
              "width":69,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ece0b05b03a64d63aea4d6de304aae32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":14},
                "size":{
                  "width":69,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"a3892d0dca094e4488f9254341824da9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "location":{
              "x":280,
              "y":22},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1561d21dcb94490595dff85e335dc76b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "location":{
                  "x":280,
                  "y":22},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b8b2016c749457ca32897fbb3af1fd9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":186},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"1bca0a33946546678447e4e2b90dcedf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0094DE,
              "opacity":1},
            "location":{
              "x":234,
              "y":120},
            "size":{
              "width":253,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba654b6cf8324be99a067f35134bfe17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE,
                  "opacity":1},
                "location":{
                  "x":234,
                  "y":120},
                "size":{
                  "width":253,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24ec161c396649edb51bbc3ddd131153",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "lineSpacing":"85px",
            "location":{
              "x":36,
              "y":206},
            "size":{
              "width":183,
              "height":1272}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50ee98d0bb6a45debbc1674f096aaf92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "lineSpacing":"85px",
                "location":{
                  "x":36,
                  "y":206},
                "size":{
                  "width":183,
                  "height":1272}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 release-buy-plans2-1",
                      "target":{
                        "targetType":"page",
                        "url":"release-buy-plans2-1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a007567eee646e48e0ea24d9456da20",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":17,
              "y":232},
            "size":{
              "width":15,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33c0c7fae4df425aabaa851d147d8bcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":17,
                  "y":232},
                "size":{
                  "width":15,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b75586f0d86d4342a5ba99f0c51a5fb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":17,
              "y":402},
            "size":{
              "width":15,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51a606ed086d4b83a7a5147249653b63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":17,
                  "y":402},
                "size":{
                  "width":15,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9445819d743745728eb1b7e2f515824c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":17,
              "y":574},
            "size":{
              "width":15,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da020f05cbc143cb9709195625e859c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":17,
                  "y":574},
                "size":{
                  "width":15,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e395f60af31a4f99a4bdf2344a41b16c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":17,
              "y":743},
            "size":{
              "width":15,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a917875b4e64d8d85e154e1633f5575",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":17,
                  "y":743},
                "size":{
                  "width":15,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54ba9d38f1ff4bff809df5e5546d5516",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":17,
              "y":830},
            "size":{
              "width":15,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c424365ae2254e31886792e6ecbdd00d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":17,
                  "y":830},
                "size":{
                  "width":15,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54feb7fa68b4412ebe6ddcdda0d0b291",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":17,
              "y":915},
            "size":{
              "width":15,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60a491d950ed4abf860e407c0a8033e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":17,
                  "y":915},
                "size":{
                  "width":15,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"396735b0cd814c2183c2430485f202ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":17,
              "y":1000},
            "size":{
              "width":15,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa26609f857b447c8559e281bfb2047f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":17,
                  "y":1000},
                "size":{
                  "width":15,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b599c153193d40198588a20f2e107813",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":17,
              "y":1084},
            "size":{
              "width":15,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d410a3b414a47fbb915eacdac501a6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":17,
                  "y":1084},
                "size":{
                  "width":15,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c4f011e7d564a3c8cc5bd27f4c00679",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":17,
              "y":1166},
            "size":{
              "width":15,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64c6d954a5304a2b8ce9dbe386913056",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":17,
                  "y":1166},
                "size":{
                  "width":15,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ea90b159ae94e5db8c1db8723318d0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":17,
              "y":1252},
            "size":{
              "width":15,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6a835358d484251aefc75c49a212941",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":17,
                  "y":1252},
                "size":{
                  "width":15,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c8190787aed4e7faa80453c540c55a8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":287},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"03351caf1d3047c6976d1e960173b7bf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":372},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"69ad0c290858416c9396e0defdcd9385",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":457},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"ca6acd9e595c474aaddfeff5983dab9a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":542},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"dfb39e1880f94af082213e0538d9e5ad",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":627},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"f44070af376a4b13855cdea7084b8bbb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":712},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"16dcd97d677b4a47b9d9e1a4e277ba7e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":797},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"1f4714bdd8684270ae0a17307c432a55",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":882},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"77445a9221be48aba28ecb39655d04c2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":967},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"43e34a7db6e74b07a1025eb69dca47c2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1052},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"e677feaaae184b44bc88b55419e998b2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1137},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"2217ffa34703497fbc559de236a75afc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1222},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"63069c0746ef4f538bbf76dceb9a81d2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1307},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"98f8a95b3f5442e0b88762a56beaf283",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1392},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"44e18169434c4274831ebcecd46d3123",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":30,
              "y":1450},
            "size":{
              "width":660,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc3331e699fc4b8495ad0fd339c2ab94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":30,
                  "y":1450},
                "size":{
                  "width":660,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDBDBDB},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u17.png"}},
{
          "id":"899841efe63b42b59df48bdaa9121425",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":319.5,
              "y":1472},
            "size":{
              "width":81,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41e84ba9933e404c9d8ee6b02bef4f9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":319.5,
                  "y":1472},
                "size":{
                  "width":81,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac6dc473704c4002844c573ebf181f9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"85px",
            "location":{
              "x":615,
              "y":717},
            "size":{
              "width":75,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8de1ea1c3da945b2af6292953db98f7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"85px",
                "location":{
                  "x":615,
                  "y":717},
                "size":{
                  "width":75,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "13f8440ace54451fa2eae3284da8ae10":{
      "scriptId":"u0"},
    "0de0b105898c4906bcbe7ddfbe16be47":{
      "scriptId":"u1"},
    "72bc92906fc34524b399f09898f8d4b4":{
      "scriptId":"u2"},
    "c870aab57195496cbb24d309007e6020":{
      "scriptId":"u3"},
    "da8317aad3f8401ba9abde14b79fe169":{
      "scriptId":"u4"},
    "42c3865a5fa249e3b2fc778d1ea2c4f5":{
      "scriptId":"u5"},
    "ece0b05b03a64d63aea4d6de304aae32":{
      "scriptId":"u6"},
    "a3892d0dca094e4488f9254341824da9":{
      "scriptId":"u7"},
    "1561d21dcb94490595dff85e335dc76b":{
      "scriptId":"u8"},
    "1b8b2016c749457ca32897fbb3af1fd9":{
      "scriptId":"u9"},
    "1bca0a33946546678447e4e2b90dcedf":{
      "scriptId":"u10"},
    "ba654b6cf8324be99a067f35134bfe17":{
      "scriptId":"u11"},
    "24ec161c396649edb51bbc3ddd131153":{
      "scriptId":"u12"},
    "50ee98d0bb6a45debbc1674f096aaf92":{
      "scriptId":"u13"},
    "6a007567eee646e48e0ea24d9456da20":{
      "scriptId":"u14"},
    "33c0c7fae4df425aabaa851d147d8bcb":{
      "scriptId":"u15"},
    "b75586f0d86d4342a5ba99f0c51a5fb4":{
      "scriptId":"u16"},
    "51a606ed086d4b83a7a5147249653b63":{
      "scriptId":"u17"},
    "9445819d743745728eb1b7e2f515824c":{
      "scriptId":"u18"},
    "da020f05cbc143cb9709195625e859c2":{
      "scriptId":"u19"},
    "e395f60af31a4f99a4bdf2344a41b16c":{
      "scriptId":"u20"},
    "8a917875b4e64d8d85e154e1633f5575":{
      "scriptId":"u21"},
    "54ba9d38f1ff4bff809df5e5546d5516":{
      "scriptId":"u22"},
    "c424365ae2254e31886792e6ecbdd00d":{
      "scriptId":"u23"},
    "54feb7fa68b4412ebe6ddcdda0d0b291":{
      "scriptId":"u24"},
    "60a491d950ed4abf860e407c0a8033e0":{
      "scriptId":"u25"},
    "396735b0cd814c2183c2430485f202ca":{
      "scriptId":"u26"},
    "aa26609f857b447c8559e281bfb2047f":{
      "scriptId":"u27"},
    "b599c153193d40198588a20f2e107813":{
      "scriptId":"u28"},
    "8d410a3b414a47fbb915eacdac501a6a":{
      "scriptId":"u29"},
    "1c4f011e7d564a3c8cc5bd27f4c00679":{
      "scriptId":"u30"},
    "64c6d954a5304a2b8ce9dbe386913056":{
      "scriptId":"u31"},
    "0ea90b159ae94e5db8c1db8723318d0e":{
      "scriptId":"u32"},
    "d6a835358d484251aefc75c49a212941":{
      "scriptId":"u33"},
    "4c8190787aed4e7faa80453c540c55a8":{
      "scriptId":"u34"},
    "03351caf1d3047c6976d1e960173b7bf":{
      "scriptId":"u35"},
    "69ad0c290858416c9396e0defdcd9385":{
      "scriptId":"u36"},
    "ca6acd9e595c474aaddfeff5983dab9a":{
      "scriptId":"u37"},
    "dfb39e1880f94af082213e0538d9e5ad":{
      "scriptId":"u38"},
    "f44070af376a4b13855cdea7084b8bbb":{
      "scriptId":"u39"},
    "16dcd97d677b4a47b9d9e1a4e277ba7e":{
      "scriptId":"u40"},
    "1f4714bdd8684270ae0a17307c432a55":{
      "scriptId":"u41"},
    "77445a9221be48aba28ecb39655d04c2":{
      "scriptId":"u42"},
    "43e34a7db6e74b07a1025eb69dca47c2":{
      "scriptId":"u43"},
    "e677feaaae184b44bc88b55419e998b2":{
      "scriptId":"u44"},
    "2217ffa34703497fbc559de236a75afc":{
      "scriptId":"u45"},
    "63069c0746ef4f538bbf76dceb9a81d2":{
      "scriptId":"u46"},
    "98f8a95b3f5442e0b88762a56beaf283":{
      "scriptId":"u47"},
    "44e18169434c4274831ebcecd46d3123":{
      "scriptId":"u48"},
    "fc3331e699fc4b8495ad0fd339c2ab94":{
      "scriptId":"u49"},
    "899841efe63b42b59df48bdaa9121425":{
      "scriptId":"u50"},
    "41e84ba9933e404c9d8ee6b02bef4f9d":{
      "scriptId":"u51"},
    "ac6dc473704c4002844c573ebf181f9e":{
      "scriptId":"u52"},
    "8de1ea1c3da945b2af6292953db98f7a":{
      "scriptId":"u53"}}});