$axure.loadCurrentPage({
  "url":"userconter-my.html",
  "generationDate":new Date(1444814346026.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"42e6825dcab74eeebf43a0c0a9256fe8",
    "type":"Axure:Page",
    "name":"UserConter-my",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"14ec9fe37eb44b85ad81e06240f822f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":936},
            "size":{
              "width":720,
              "height":245},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c33dd893711948159d4cc046e7c55e61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":936},
                "size":{
                  "width":720,
                  "height":245},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-my/u0.png"}},
{
          "id":"8e3d880184be4ed6be4237ce5153820d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0094DE},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef9dd82e379641fe90cec635d9cdc95e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0094DE},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-orders/u2.png"}},
{
          "id":"166dcef3918e49408c33bc350a9b6049",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":16},
            "size":{
              "width":216,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b122deae9fe4b1cab28d940be1ce67a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":16},
                "size":{
                  "width":216,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u6.png"}},
{
          "id":"c45c1a11ce784c6f95d1e5acdd14ef25",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":637,
              "y":23},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed511da15a604388a26ca6269a631b1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":637,
                  "y":23},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 About User",
                      "target":{
                        "targetType":"page",
                        "url":"about_user.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u28.png"}},
{
          "id":"8db2390effb34af5af859153cf674fd7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":0,
              "y":1073},
            "size":{
              "width":720,
              "height":108},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1857385e42814556ab5a8e2edbd0d578",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":0,
                  "y":1073},
                "size":{
                  "width":720,
                  "height":108},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-orders/u8.png"}},
{
          "id":"6d64d77fc419432698e349b6e7d4e65b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1066},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"9f02c3cd114f4a7693457decbe8c4eb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":535,
              "y":30},
            "size":{
              "width":85,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a14a16042940461fb006622409021940",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":535,
                  "y":30},
                "size":{
                  "width":85,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9ae2032335b42fb80c71f4e87271330",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"26px",
            "location":{
              "x":74,
              "y":1138},
            "size":{
              "width":572,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce0925179a784beeb2815e68c784c5e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"26px",
                "location":{
                  "x":74,
                  "y":1138},
                "size":{
                  "width":572,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d1ec4255e2f4bfbb47a3f4068a13f54",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":1085},
            "size":{
              "width":49,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c8422e10eab4463911884039ddedbc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":1085},
                "size":{
                  "width":49,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 UserConter-orders",
                      "target":{
                        "targetType":"page",
                        "url":"userconter-orders.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/userconter-release/u15.png"}},
{
          "id":"add9a73be5594881b852bd50ae49b6f9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":1086},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef23945037774928837b9ae67466d895",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":249,
                  "y":1086},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 UserConter-release",
                      "target":{
                        "targetType":"page",
                        "url":"userconter-release.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/userconter-orders/u17.png"}},
{
          "id":"1f9436c6d68c49b583433bcc43dca2ce",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":419,
              "y":1086},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4c913a9cd394539846b8e943921fa67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":419,
                  "y":1086},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-my/u19.png"}},
{
          "id":"417acc08011a4881af45048ef74aefc9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":1086},
            "size":{
              "width":56,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85b7cc07987f4a3c9e26cf432f0df69d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":1086},
                "size":{
                  "width":56,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/userconter-orders/u21.png"}},
{
          "id":"4f4f89afb493481bb5cb343ffde7d0f1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":148},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23e0acc9e34d4cbe9750fedd420b8807",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":148},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-orders/u23.png"}},
{
          "id":"5e376fb04f6c4bf1980eee7def3f0f0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":149,
              "y":175},
            "size":{
              "width":145,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be9b98936a284f3ebb2dc3299b933625",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":149,
                  "y":175},
                "size":{
                  "width":145,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 About User",
                      "target":{
                        "targetType":"page",
                        "url":"about_user.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34134b476fa84fe6bc0cd0729864bcc2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":298},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"4585a94c8c094af88c9f7f40901c3f8c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":931},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"a931bcffd5e24bc088810f44d3e81540",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":356},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac3d258b4eba4e51962cdf3e312ceca0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":356},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-orders/u23.png"}},
{
          "id":"36c23cead7454ab88c90e4bd367bff8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":149,
              "y":383},
            "size":{
              "width":145,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e153ff9f3d744bf9acd11d6be0c3d9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":149,
                  "y":383},
                "size":{
                  "width":145,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 About Company",
                      "target":{
                        "targetType":"page",
                        "url":"about_company.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d94606a4a6454d7085abcd2a68d438ef",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":506},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"ccee2e418c6d452ba2b25bdd69de1f49",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":569},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e56fe835e2142d487de8517ff5cda0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":569},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-orders/u23.png"}},
{
          "id":"d9cd54a75866427d9c7cecef536cc215",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":149,
              "y":596},
            "size":{
              "width":145,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d3c8667dace4ee5a1c72a19a22610be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":149,
                  "y":596},
                "size":{
                  "width":145,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Papers upload",
                      "target":{
                        "targetType":"page",
                        "url":"papers_upload.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9a8b01a2a8a4740b38a53354532ebc8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":719},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"23bf448c9b4249ce96ee7f89014dbe1a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":780},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f99a74eab264c9b8f91ec98f21a51a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":780},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-orders/u23.png"}},
{
          "id":"b1a3453df3e64187a48011c5a3a4b328",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":149,
              "y":807},
            "size":{
              "width":145,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d031de16a7f741298c8921e7a9c80daf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":149,
                  "y":807},
                "size":{
                  "width":145,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Edit Password",
                      "target":{
                        "targetType":"page",
                        "url":"edit_password.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"308395710c98436abf0219dc5bba8b00",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":672,
              "y":182},
            "size":{
              "width":16,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99e99d2ebebc47e595093a9253e2063d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":672,
                  "y":182},
                "size":{
                  "width":16,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80f2e640ac7d4705b4b96aa981630f7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":672,
              "y":390},
            "size":{
              "width":16,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5136b90ffa2b4a46a969f5c8ef57337c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":672,
                  "y":390},
                "size":{
                  "width":16,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a1bfa0d4f84460ca15255fe9b66b9ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":672,
              "y":603},
            "size":{
              "width":16,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48b43d01e5f24812b931239c01d2782f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":672,
                  "y":603},
                "size":{
                  "width":16,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a6b989a9fc44f9ea0b4bafa4321d56e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":672,
              "y":814},
            "size":{
              "width":16,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a828769e0eb64f058b850c9ff337f5cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":672,
                  "y":814},
                "size":{
                  "width":16,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "14ec9fe37eb44b85ad81e06240f822f7":{
      "scriptId":"u0"},
    "c33dd893711948159d4cc046e7c55e61":{
      "scriptId":"u1"},
    "8e3d880184be4ed6be4237ce5153820d":{
      "scriptId":"u2"},
    "ef9dd82e379641fe90cec635d9cdc95e":{
      "scriptId":"u3"},
    "166dcef3918e49408c33bc350a9b6049":{
      "scriptId":"u4"},
    "8b122deae9fe4b1cab28d940be1ce67a":{
      "scriptId":"u5"},
    "c45c1a11ce784c6f95d1e5acdd14ef25":{
      "scriptId":"u6"},
    "ed511da15a604388a26ca6269a631b1c":{
      "scriptId":"u7"},
    "8db2390effb34af5af859153cf674fd7":{
      "scriptId":"u8"},
    "1857385e42814556ab5a8e2edbd0d578":{
      "scriptId":"u9"},
    "6d64d77fc419432698e349b6e7d4e65b":{
      "scriptId":"u10"},
    "9f02c3cd114f4a7693457decbe8c4eb2":{
      "scriptId":"u11"},
    "a14a16042940461fb006622409021940":{
      "scriptId":"u12"},
    "c9ae2032335b42fb80c71f4e87271330":{
      "scriptId":"u13"},
    "ce0925179a784beeb2815e68c784c5e5":{
      "scriptId":"u14"},
    "9d1ec4255e2f4bfbb47a3f4068a13f54":{
      "scriptId":"u15"},
    "5c8422e10eab4463911884039ddedbc5":{
      "scriptId":"u16"},
    "add9a73be5594881b852bd50ae49b6f9":{
      "scriptId":"u17"},
    "ef23945037774928837b9ae67466d895":{
      "scriptId":"u18"},
    "1f9436c6d68c49b583433bcc43dca2ce":{
      "scriptId":"u19"},
    "b4c913a9cd394539846b8e943921fa67":{
      "scriptId":"u20"},
    "417acc08011a4881af45048ef74aefc9":{
      "scriptId":"u21"},
    "85b7cc07987f4a3c9e26cf432f0df69d":{
      "scriptId":"u22"},
    "4f4f89afb493481bb5cb343ffde7d0f1":{
      "scriptId":"u23"},
    "23e0acc9e34d4cbe9750fedd420b8807":{
      "scriptId":"u24"},
    "5e376fb04f6c4bf1980eee7def3f0f0e":{
      "scriptId":"u25"},
    "be9b98936a284f3ebb2dc3299b933625":{
      "scriptId":"u26"},
    "34134b476fa84fe6bc0cd0729864bcc2":{
      "scriptId":"u27"},
    "4585a94c8c094af88c9f7f40901c3f8c":{
      "scriptId":"u28"},
    "a931bcffd5e24bc088810f44d3e81540":{
      "scriptId":"u29"},
    "ac3d258b4eba4e51962cdf3e312ceca0":{
      "scriptId":"u30"},
    "36c23cead7454ab88c90e4bd367bff8b":{
      "scriptId":"u31"},
    "3e153ff9f3d744bf9acd11d6be0c3d9c":{
      "scriptId":"u32"},
    "d94606a4a6454d7085abcd2a68d438ef":{
      "scriptId":"u33"},
    "ccee2e418c6d452ba2b25bdd69de1f49":{
      "scriptId":"u34"},
    "8e56fe835e2142d487de8517ff5cda0a":{
      "scriptId":"u35"},
    "d9cd54a75866427d9c7cecef536cc215":{
      "scriptId":"u36"},
    "8d3c8667dace4ee5a1c72a19a22610be":{
      "scriptId":"u37"},
    "b9a8b01a2a8a4740b38a53354532ebc8":{
      "scriptId":"u38"},
    "23bf448c9b4249ce96ee7f89014dbe1a":{
      "scriptId":"u39"},
    "2f99a74eab264c9b8f91ec98f21a51a8":{
      "scriptId":"u40"},
    "b1a3453df3e64187a48011c5a3a4b328":{
      "scriptId":"u41"},
    "d031de16a7f741298c8921e7a9c80daf":{
      "scriptId":"u42"},
    "308395710c98436abf0219dc5bba8b00":{
      "scriptId":"u43"},
    "99e99d2ebebc47e595093a9253e2063d":{
      "scriptId":"u44"},
    "80f2e640ac7d4705b4b96aa981630f7f":{
      "scriptId":"u45"},
    "5136b90ffa2b4a46a969f5c8ef57337c":{
      "scriptId":"u46"},
    "1a1bfa0d4f84460ca15255fe9b66b9ba":{
      "scriptId":"u47"},
    "48b43d01e5f24812b931239c01d2782f":{
      "scriptId":"u48"},
    "7a6b989a9fc44f9ea0b4bafa4321d56e":{
      "scriptId":"u49"},
    "a828769e0eb64f058b850c9ff337f5cd":{
      "scriptId":"u50"}}});