$axure.loadCurrentPage({
  "url":"myattention.html",
  "generationDate":new Date(1444814345676.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4d86823ade2f4167a742a9b9a2e900b3",
    "type":"Axure:Page",
    "name":"MyAttention",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"607978c7ec6f4e7fa9a598be5b3ebdf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":14},
            "size":{
              "width":720,
              "height":1806},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef58823c761545128cb76b791743078a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":14},
                "size":{
                  "width":720,
                  "height":1806},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/myattention/u0.png"}},
{
          "id":"1272d20222b94113b3c803ff62db4c16",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c08240645eb40af937ee6ce1c54c8d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"4e4d3888e7b3490cba2dc286ba64b7b3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"46dca96fad3f47d899040f6ea8493825",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":14},
            "size":{
              "width":69,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1bf2e72c4dc4d7fb6d728d6e20fc0c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":14},
                "size":{
                  "width":69,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 UserConter-release",
                      "target":{
                        "targetType":"page",
                        "url":"userconter-release.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"6c5ab9eaea4e4a4badcf405174e825e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "location":{
              "x":280,
              "y":22},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"592a1a3b1ec8494e9d6a8348d5865d9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "location":{
                  "x":280,
                  "y":22},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f4548b630abb48eb8476dbf4e1c24d30",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":129},
            "size":{
              "width":720,
              "height":604},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b094a18dc5054e71ada471258704c1d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":129},
                "size":{
                  "width":720,
                  "height":604},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/myattention/u9.png"}},
{
          "id":"0c7bfdfdf0384a6c9d5e42c36cc4e5b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "lineSpacing":"60px",
            "location":{
              "x":27,
              "y":272},
            "size":{
              "width":374,
              "height":420}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6987826e86146eeb1a0412672acf55f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "lineSpacing":"60px",
                "location":{
                  "x":27,
                  "y":272},
                "size":{
                  "width":374,
                  "height":420}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5decf227ac64f94a118c1ffd5a04c1c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":125},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"9570ab1b3a394824bd7fbf57db855b4e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":729},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"0446bf7a6be04b14b9b751c9bb796530",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":765},
            "size":{
              "width":720,
              "height":484},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8555d9ecd9bf40b0bcaeafb0f004e6c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":765},
                "size":{
                  "width":720,
                  "height":484},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/myattention/u15.png"}},
{
          "id":"ad46713ce3904031b121da9134898488",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "lineSpacing":"60px",
            "location":{
              "x":27,
              "y":787},
            "size":{
              "width":374,
              "height":420}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb4626ebf76541d6882182bbe8eb2ce7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "lineSpacing":"60px",
                "location":{
                  "x":27,
                  "y":787},
                "size":{
                  "width":374,
                  "height":420}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"514dd77d912643ae984d636eeb518160",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":759},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"b18a416ead654971a2bede62bf3a962e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1244},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"0b388d1fce0d433eb87e06400281092c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1280},
            "size":{
              "width":720,
              "height":484},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d62b09f4e7ed42f2b4741f8a45e2e794",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1280},
                "size":{
                  "width":720,
                  "height":484},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/myattention/u15.png"}},
{
          "id":"1ffe37064fa14ca6a53d93b8227e824c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "lineSpacing":"60px",
            "location":{
              "x":27,
              "y":1302},
            "size":{
              "width":374,
              "height":420}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83b7f5519131418ba69226bb72812e30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "lineSpacing":"60px",
                "location":{
                  "x":27,
                  "y":1302},
                "size":{
                  "width":374,
                  "height":420}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bbc9b3a235804e3489df83778c7cd493",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1274},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"7f7c01baf92e4fe5901a7802576c2484",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1759},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"d4d78a8b97584c34838153a94d6cf437",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":247},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"0f698c1f71a14dadabb1bc31bbe93986",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":151},
            "size":{
              "width":485,
              "height":80},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7df63d657394501ac0ca786ce0b3eb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":151},
                "size":{
                  "width":485,
                  "height":80},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-plan/u46.png"}},
{
          "id":"9ebdb98c10d247aca1db50b8c8273021",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":528,
              "y":151},
            "size":{
              "width":164,
              "height":80},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4081311af1144d3bb42421a173242b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":528,
                  "y":151},
                "size":{
                  "width":164,
                  "height":80},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDBDBDB},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-plan/u48.png"}},
{
          "id":"d1c75d292cd44eb491ba5e98b3555560",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":574,
              "y":168},
            "size":{
              "width":73,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d861b03c39a409785320645ba329474",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":574,
                  "y":168},
                "size":{
                  "width":73,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "607978c7ec6f4e7fa9a598be5b3ebdf4":{
      "scriptId":"u0"},
    "ef58823c761545128cb76b791743078a":{
      "scriptId":"u1"},
    "1272d20222b94113b3c803ff62db4c16":{
      "scriptId":"u2"},
    "4c08240645eb40af937ee6ce1c54c8d9":{
      "scriptId":"u3"},
    "4e4d3888e7b3490cba2dc286ba64b7b3":{
      "scriptId":"u4"},
    "46dca96fad3f47d899040f6ea8493825":{
      "scriptId":"u5"},
    "a1bf2e72c4dc4d7fb6d728d6e20fc0c0":{
      "scriptId":"u6"},
    "6c5ab9eaea4e4a4badcf405174e825e4":{
      "scriptId":"u7"},
    "592a1a3b1ec8494e9d6a8348d5865d9d":{
      "scriptId":"u8"},
    "f4548b630abb48eb8476dbf4e1c24d30":{
      "scriptId":"u9"},
    "b094a18dc5054e71ada471258704c1d1":{
      "scriptId":"u10"},
    "0c7bfdfdf0384a6c9d5e42c36cc4e5b6":{
      "scriptId":"u11"},
    "e6987826e86146eeb1a0412672acf55f":{
      "scriptId":"u12"},
    "a5decf227ac64f94a118c1ffd5a04c1c":{
      "scriptId":"u13"},
    "9570ab1b3a394824bd7fbf57db855b4e":{
      "scriptId":"u14"},
    "0446bf7a6be04b14b9b751c9bb796530":{
      "scriptId":"u15"},
    "8555d9ecd9bf40b0bcaeafb0f004e6c6":{
      "scriptId":"u16"},
    "ad46713ce3904031b121da9134898488":{
      "scriptId":"u17"},
    "fb4626ebf76541d6882182bbe8eb2ce7":{
      "scriptId":"u18"},
    "514dd77d912643ae984d636eeb518160":{
      "scriptId":"u19"},
    "b18a416ead654971a2bede62bf3a962e":{
      "scriptId":"u20"},
    "0b388d1fce0d433eb87e06400281092c":{
      "scriptId":"u21"},
    "d62b09f4e7ed42f2b4741f8a45e2e794":{
      "scriptId":"u22"},
    "1ffe37064fa14ca6a53d93b8227e824c":{
      "scriptId":"u23"},
    "83b7f5519131418ba69226bb72812e30":{
      "scriptId":"u24"},
    "bbc9b3a235804e3489df83778c7cd493":{
      "scriptId":"u25"},
    "7f7c01baf92e4fe5901a7802576c2484":{
      "scriptId":"u26"},
    "d4d78a8b97584c34838153a94d6cf437":{
      "scriptId":"u27"},
    "0f698c1f71a14dadabb1bc31bbe93986":{
      "scriptId":"u28"},
    "e7df63d657394501ac0ca786ce0b3eb9":{
      "scriptId":"u29"},
    "9ebdb98c10d247aca1db50b8c8273021":{
      "scriptId":"u30"},
    "b4081311af1144d3bb42421a173242b9":{
      "scriptId":"u31"},
    "d1c75d292cd44eb491ba5e98b3555560":{
      "scriptId":"u32"},
    "1d861b03c39a409785320645ba329474":{
      "scriptId":"u33"}}});