$axure.loadCurrentPage({
  "url":"myenquiry-content.html",
  "generationDate":new Date(1444814345966.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"93912d5bb31146d3987f26dd4f44a703",
    "type":"Axure:Page",
    "name":"MyEnquiry-content",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"140aba53330f41939c900596822161f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":14},
            "size":{
              "width":720,
              "height":1446},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e99280939904ce784940167fcd5aafd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":14},
                "size":{
                  "width":720,
                  "height":1446},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/myenquiry-content/u0.png"}},
{
          "id":"202c8bbc7d1a415da35f034a7ea1dbcf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e051e2a64ab4c7591c07c12447903a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"a3d13858489d439ba74c60c890a7efa2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"2d917ab842484f7d9e3dc74cf11e1589",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":14},
            "size":{
              "width":69,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fde9a0ff80549e3b58108435a8b90b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":14},
                "size":{
                  "width":69,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 MyEnquiry",
                      "target":{
                        "targetType":"page",
                        "url":"myenquiry.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"9357be33a2234fcba660026d01c404ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "location":{
              "x":280,
              "y":22},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66816f2265f5414fa23f9063bd5f4308",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "location":{
                  "x":280,
                  "y":22},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4f0265eeeb5451f93a93038003ed154",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":129},
            "size":{
              "width":720,
              "height":416},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b83929426044a90ac44036a0a31911c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":129},
                "size":{
                  "width":720,
                  "height":416},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/myenquiry-content/u9.png"}},
{
          "id":"90fe6c2b5c284f909b5d87fba69b0009",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "lineSpacing":"72px",
            "location":{
              "x":27,
              "y":149},
            "size":{
              "width":442,
              "height":360}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c61c6d2e5d74b5288e954a5ca3fafb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "lineSpacing":"72px",
                "location":{
                  "x":27,
                  "y":149},
                "size":{
                  "width":442,
                  "height":360}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45b13a6d894046a2924656beb5fa226c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":125},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"b46dd89e0c824d539a35749eb652ecc8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":541},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"4f7fb69773334c3fbab1eda3e38fbac6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":577},
            "size":{
              "width":720,
              "height":819},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc31b95e009c4ca5b0b53198982aa4bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":577},
                "size":{
                  "width":720,
                  "height":819},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/myenquiry-content/u15.png"}},
{
          "id":"03f8e2d5be664f38beb507cb03e9d68b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1392},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"efd392cf29dd49e4a3e2ee32da9228f6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":572},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"dbaed291cbfd4fe8b1daf9345dc65889",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "lineSpacing":"72px",
            "location":{
              "x":27,
              "y":712},
            "size":{
              "width":544,
              "height":659}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92ebf544e6b64e55a3f2bcd842abf7ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "lineSpacing":"72px",
                "location":{
                  "x":27,
                  "y":712},
                "size":{
                  "width":544,
                  "height":659}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c57192c6f9ce406f808812a9f9095ff1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"40px",
            "location":{
              "x":27,
              "y":619},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b4fb4d2a9714dd09a9a3de98da2af42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"40px",
                "location":{
                  "x":27,
                  "y":619},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85fbc1cc341a4c42ab26f97c30746cdb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":686},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "140aba53330f41939c900596822161f9":{
      "scriptId":"u0"},
    "4e99280939904ce784940167fcd5aafd":{
      "scriptId":"u1"},
    "202c8bbc7d1a415da35f034a7ea1dbcf":{
      "scriptId":"u2"},
    "7e051e2a64ab4c7591c07c12447903a0":{
      "scriptId":"u3"},
    "a3d13858489d439ba74c60c890a7efa2":{
      "scriptId":"u4"},
    "2d917ab842484f7d9e3dc74cf11e1589":{
      "scriptId":"u5"},
    "5fde9a0ff80549e3b58108435a8b90b3":{
      "scriptId":"u6"},
    "9357be33a2234fcba660026d01c404ab":{
      "scriptId":"u7"},
    "66816f2265f5414fa23f9063bd5f4308":{
      "scriptId":"u8"},
    "c4f0265eeeb5451f93a93038003ed154":{
      "scriptId":"u9"},
    "6b83929426044a90ac44036a0a31911c":{
      "scriptId":"u10"},
    "90fe6c2b5c284f909b5d87fba69b0009":{
      "scriptId":"u11"},
    "4c61c6d2e5d74b5288e954a5ca3fafb9":{
      "scriptId":"u12"},
    "45b13a6d894046a2924656beb5fa226c":{
      "scriptId":"u13"},
    "b46dd89e0c824d539a35749eb652ecc8":{
      "scriptId":"u14"},
    "4f7fb69773334c3fbab1eda3e38fbac6":{
      "scriptId":"u15"},
    "fc31b95e009c4ca5b0b53198982aa4bf":{
      "scriptId":"u16"},
    "03f8e2d5be664f38beb507cb03e9d68b":{
      "scriptId":"u17"},
    "efd392cf29dd49e4a3e2ee32da9228f6":{
      "scriptId":"u18"},
    "dbaed291cbfd4fe8b1daf9345dc65889":{
      "scriptId":"u19"},
    "92ebf544e6b64e55a3f2bcd842abf7ae":{
      "scriptId":"u20"},
    "c57192c6f9ce406f808812a9f9095ff1":{
      "scriptId":"u21"},
    "6b4fb4d2a9714dd09a9a3de98da2af42":{
      "scriptId":"u22"},
    "85fbc1cc341a4c42ab26f97c30746cdb":{
      "scriptId":"u23"}}});