$axure.loadCurrentPage({
  "url":"forget2.html",
  "generationDate":new Date(1444814341418.82),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b0d4f614458c4200abde8a91a3f0504c",
    "type":"Axure:Page",
    "name":"forget2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ae69c3abae394e5d910d1171cfa6b847",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":86},
            "size":{
              "width":720,
              "height":1094},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1c0ef9a74394b988176c14ea2630e24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":86},
                "size":{
                  "width":720,
                  "height":1094},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u0.png"}},
{
          "id":"347cdf518e604bccbf3b4f41c823aa4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9d6b70c321d4e1f9336c3473b5d0e90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"4558c11641e74503a57acc0ff21b8713",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"1dd7b3e667eb4a2a9b26f1dfc7493766",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":14},
            "size":{
              "width":69,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a32fe61b74ef46bfa5ca9ed4a99af018",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":14},
                "size":{
                  "width":69,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 forget",
                      "target":{
                        "targetType":"page",
                        "url":"forget.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"1c79a02bf1cd4f87a85e7cc4f62727be",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "location":{
              "x":240,
              "y":22},
            "size":{
              "width":241,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"781f1f2e608d43d394d3f62a85685b33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "location":{
                  "x":240,
                  "y":22},
                "size":{
                  "width":241,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65bf6470d3bc49b2bdc722a35deed1f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":153},
            "size":{
              "width":660,
              "height":96},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d720c6795d742a6ade78e8e24a276b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":153},
                "size":{
                  "width":660,
                  "height":96},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDBDBDB},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u9.png"}},
{
          "id":"a9c2eccc48044f959803512225d190e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":59,
              "y":181},
            "size":{
              "width":183,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d596c8f6d0f409d96b2274f118a0335",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":59,
                  "y":181},
                "size":{
                  "width":183,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"517a0fc785cc4341842f21e357704b39",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":276},
            "size":{
              "width":660,
              "height":96},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1dfdd1f00eb14a719d91cca2ce62c927",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":276},
                "size":{
                  "width":660,
                  "height":96},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDBDBDB},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u9.png"}},
{
          "id":"496062b7e35a40ba9e2c46213c5ab168",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":59,
              "y":304},
            "size":{
              "width":153,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25d649fc764142d9b3dcf0f308055e89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":59,
                  "y":304},
                "size":{
                  "width":153,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b08cfb734b05403cb558470bcfec64c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":30,
              "y":423},
            "size":{
              "width":660,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0e9a49b061b45bb819fa64312f1e677",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":30,
                  "y":423},
                "size":{
                  "width":660,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDBDBDB},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u17.png"}},
{
          "id":"41b7f39b5fee466986807a3d2af6e4cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":280,
              "y":445},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b6d16c23eb4485689c4f202dc3bb8d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":280,
                  "y":445},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 forget3",
                      "target":{
                        "targetType":"page",
                        "url":"forget3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "ae69c3abae394e5d910d1171cfa6b847":{
      "scriptId":"u0"},
    "d1c0ef9a74394b988176c14ea2630e24":{
      "scriptId":"u1"},
    "347cdf518e604bccbf3b4f41c823aa4f":{
      "scriptId":"u2"},
    "c9d6b70c321d4e1f9336c3473b5d0e90":{
      "scriptId":"u3"},
    "4558c11641e74503a57acc0ff21b8713":{
      "scriptId":"u4"},
    "1dd7b3e667eb4a2a9b26f1dfc7493766":{
      "scriptId":"u5"},
    "a32fe61b74ef46bfa5ca9ed4a99af018":{
      "scriptId":"u6"},
    "1c79a02bf1cd4f87a85e7cc4f62727be":{
      "scriptId":"u7"},
    "781f1f2e608d43d394d3f62a85685b33":{
      "scriptId":"u8"},
    "65bf6470d3bc49b2bdc722a35deed1f1":{
      "scriptId":"u9"},
    "2d720c6795d742a6ade78e8e24a276b4":{
      "scriptId":"u10"},
    "a9c2eccc48044f959803512225d190e9":{
      "scriptId":"u11"},
    "7d596c8f6d0f409d96b2274f118a0335":{
      "scriptId":"u12"},
    "517a0fc785cc4341842f21e357704b39":{
      "scriptId":"u13"},
    "1dfdd1f00eb14a719d91cca2ce62c927":{
      "scriptId":"u14"},
    "496062b7e35a40ba9e2c46213c5ab168":{
      "scriptId":"u15"},
    "25d649fc764142d9b3dcf0f308055e89":{
      "scriptId":"u16"},
    "b08cfb734b05403cb558470bcfec64c0":{
      "scriptId":"u17"},
    "b0e9a49b061b45bb819fa64312f1e677":{
      "scriptId":"u18"},
    "41b7f39b5fee466986807a3d2af6e4cd":{
      "scriptId":"u19"},
    "4b6d16c23eb4485689c4f202dc3bb8d9":{
      "scriptId":"u20"}}});