$axure.loadCurrentPage({
  "url":"papers_upload.html",
  "generationDate":new Date(1444814346491.11),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9f243516155343f99248fd96613d312e",
    "type":"Axure:Page",
    "name":"Papers upload",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f98d983ddac44ccbb01da90d07c3f9eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":1538},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d157de3e621435eaf039122c6837d14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":92},
                "size":{
                  "width":720,
                  "height":1538},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/papers_upload/u0.png"}},
{
          "id":"112c1017421a4adcbc99291924d3f77d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d530de6a476b4c31a874215b9a8d4d4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"9b9651dbc3594e95a14b3de758acc3bd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"3312098c34964049a6c2bd5f09b04a2f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":14},
            "size":{
              "width":69,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"238cc2861438410dbda179dc10c5b5f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":14},
                "size":{
                  "width":69,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 UserConter-my",
                      "target":{
                        "targetType":"page",
                        "url":"userconter-my.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"4f8d9314b9b84963ae8702b6a70ef163",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "location":{
              "x":280,
              "y":22},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9aae3b0c27d4beabf1489b18070627b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "location":{
                  "x":280,
                  "y":22},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6b03f7d95a74f1c9911d45cb886fab4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":131},
            "size":{
              "width":720,
              "height":1434},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba59ac1ba95c4551bee80656205f3551",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":131},
                "size":{
                  "width":720,
                  "height":1434},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/papers_upload/u9.png"}},
{
          "id":"6ff27f8fef8b4c1592225b3a9d0d8045",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "lineSpacing":"120px",
            "location":{
              "x":256,
              "y":182},
            "size":{
              "width":244,
              "height":1320}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecfdcf8388ad42fcb4c12214446869da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "lineSpacing":"120px",
                "location":{
                  "x":256,
                  "y":182},
                "size":{
                  "width":244,
                  "height":1320}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Papers upload2",
                      "target":{
                        "targetType":"page",
                        "url":"papers_upload2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf61725ec7e3421882648d1cf5815b9e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":125},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"864be8fdee3b43f5999bb24f537b40cc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":364},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"e57d42bfae2b4245bbcfba1d89cd19ce",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1081},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"579afe1e671949a38e962455c13fc003",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":649,
              "y":220},
            "size":{
              "width":45,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7195c6d23dc4fc5b42071c0aa21a62b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":649,
                  "y":220},
                "size":{
                  "width":45,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about_user/u20.png"}},
{
          "id":"bf423a681a0c44bdb37d23f8795b80d0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1320},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"a19de8a5b11e4c698a9123e840cb5cd4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1559},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"4776f49816eb4c5d961ae9edf3ecbfc9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":603},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"feb56149485a434eac1b51e714c35f69",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":842},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"531ba41308a34f8da3e63cd5c8e692c7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":649,
              "y":460},
            "size":{
              "width":45,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4d561f002664fc8a30a09fc93348a75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":649,
                  "y":460},
                "size":{
                  "width":45,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about_user/u20.png"}},
{
          "id":"052d941c3e2f462c93be652625c8fb96",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":649,
              "y":700},
            "size":{
              "width":45,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c59b8df7da8441e8cdf1b8f9ebab5a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":649,
                  "y":700},
                "size":{
                  "width":45,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about_user/u20.png"}},
{
          "id":"9e2d6ca975e0412ba630610e8a1ee190",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":158},
            "size":{
              "width":180,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68344f896cd14d97b89acb8890ba963a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":158},
                "size":{
                  "width":180,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/papers_upload/u26.png"}},
{
          "id":"a5a2a16b7d554536bc1ccb659faa1b76",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":397},
            "size":{
              "width":180,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd222a1b41c64c279332721b3c4fefbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":397},
                "size":{
                  "width":180,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/papers_upload/u26.png"}},
{
          "id":"65f7b25b5e0c4fffaee2267a3cd11bb8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":635},
            "size":{
              "width":180,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7cff410e3db4d3a9b62d245ef2da962",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":635},
                "size":{
                  "width":180,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/papers_upload/u26.png"}},
{
          "id":"483996ee61874f39ba13af358a543c85",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":875},
            "size":{
              "width":180,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb090ca50a5b4a1996f1041cf93bfa4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":875},
                "size":{
                  "width":180,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/papers_upload/u26.png"}},
{
          "id":"552d0a18d20a405bb3b9abc39f9bae1b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":1115},
            "size":{
              "width":180,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"309d318db947477aacd1e0c75a33e2cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":1115},
                "size":{
                  "width":180,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/papers_upload/u26.png"}},
{
          "id":"83fac8fd7a6342358f3154c936a533ad",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":1353},
            "size":{
              "width":180,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ba02787d59546f0997c6c8c34f89065",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":1353},
                "size":{
                  "width":180,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/papers_upload/u26.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f98d983ddac44ccbb01da90d07c3f9eb":{
      "scriptId":"u0"},
    "4d157de3e621435eaf039122c6837d14":{
      "scriptId":"u1"},
    "112c1017421a4adcbc99291924d3f77d":{
      "scriptId":"u2"},
    "d530de6a476b4c31a874215b9a8d4d4c":{
      "scriptId":"u3"},
    "9b9651dbc3594e95a14b3de758acc3bd":{
      "scriptId":"u4"},
    "3312098c34964049a6c2bd5f09b04a2f":{
      "scriptId":"u5"},
    "238cc2861438410dbda179dc10c5b5f5":{
      "scriptId":"u6"},
    "4f8d9314b9b84963ae8702b6a70ef163":{
      "scriptId":"u7"},
    "f9aae3b0c27d4beabf1489b18070627b":{
      "scriptId":"u8"},
    "c6b03f7d95a74f1c9911d45cb886fab4":{
      "scriptId":"u9"},
    "ba59ac1ba95c4551bee80656205f3551":{
      "scriptId":"u10"},
    "6ff27f8fef8b4c1592225b3a9d0d8045":{
      "scriptId":"u11"},
    "ecfdcf8388ad42fcb4c12214446869da":{
      "scriptId":"u12"},
    "cf61725ec7e3421882648d1cf5815b9e":{
      "scriptId":"u13"},
    "864be8fdee3b43f5999bb24f537b40cc":{
      "scriptId":"u14"},
    "e57d42bfae2b4245bbcfba1d89cd19ce":{
      "scriptId":"u15"},
    "579afe1e671949a38e962455c13fc003":{
      "scriptId":"u16"},
    "b7195c6d23dc4fc5b42071c0aa21a62b":{
      "scriptId":"u17"},
    "bf423a681a0c44bdb37d23f8795b80d0":{
      "scriptId":"u18"},
    "a19de8a5b11e4c698a9123e840cb5cd4":{
      "scriptId":"u19"},
    "4776f49816eb4c5d961ae9edf3ecbfc9":{
      "scriptId":"u20"},
    "feb56149485a434eac1b51e714c35f69":{
      "scriptId":"u21"},
    "531ba41308a34f8da3e63cd5c8e692c7":{
      "scriptId":"u22"},
    "c4d561f002664fc8a30a09fc93348a75":{
      "scriptId":"u23"},
    "052d941c3e2f462c93be652625c8fb96":{
      "scriptId":"u24"},
    "5c59b8df7da8441e8cdf1b8f9ebab5a7":{
      "scriptId":"u25"},
    "9e2d6ca975e0412ba630610e8a1ee190":{
      "scriptId":"u26"},
    "68344f896cd14d97b89acb8890ba963a":{
      "scriptId":"u27"},
    "a5a2a16b7d554536bc1ccb659faa1b76":{
      "scriptId":"u28"},
    "dd222a1b41c64c279332721b3c4fefbe":{
      "scriptId":"u29"},
    "65f7b25b5e0c4fffaee2267a3cd11bb8":{
      "scriptId":"u30"},
    "e7cff410e3db4d3a9b62d245ef2da962":{
      "scriptId":"u31"},
    "483996ee61874f39ba13af358a543c85":{
      "scriptId":"u32"},
    "bb090ca50a5b4a1996f1041cf93bfa4a":{
      "scriptId":"u33"},
    "552d0a18d20a405bb3b9abc39f9bae1b":{
      "scriptId":"u34"},
    "309d318db947477aacd1e0c75a33e2cb":{
      "scriptId":"u35"},
    "83fac8fd7a6342358f3154c936a533ad":{
      "scriptId":"u36"},
    "3ba02787d59546f0997c6c8c34f89065":{
      "scriptId":"u37"}}});