$axure.loadCurrentPage({
  "url":"infocontent.html",
  "generationDate":new Date(1444814342034.85),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b652eb0a0e064fbdbee9253cf81ee9d9",
    "type":"Axure:Page",
    "name":"infoContent",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dab1fa1e74bb40289bbb68c6217f05f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":48},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3a1dfa08da54a8aaca1378092508dbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":92},
                "size":{
                  "width":720,
                  "height":48},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/infocontent/u0.png"}},
{
          "id":"fc6f7a25459b4aa69d30e1d63810ce85",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95aa9dc5767f42909d7ac9afb9f50d91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"515fc6e73b134508bc9e90c97e38aa62",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"70e9fa33967543429dfaab43d864c85d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":14},
            "size":{
              "width":69,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ba24a2c443e4fd7a24567a7cc826e22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":14},
                "size":{
                  "width":69,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 info",
                      "target":{
                        "targetType":"page",
                        "url":"info.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"fe171f62fbe2486385741b23de123ed0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "location":{
              "x":280,
              "y":22},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"643bbac6e6814bdd9dfeb6ac0a02903d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "location":{
                  "x":280,
                  "y":22},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ccc4afa7dd684822b583e168e8dd207d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":131},
            "size":{
              "width":720,
              "height":659},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9856e474cd34fcd9d3ac4ed1df1279e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":131},
                "size":{
                  "width":720,
                  "height":659},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/infocontent/u9.png"}},
{
          "id":"80faa5c293cc4df5857299853933c6ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "lineSpacing":"60px",
            "location":{
              "x":27,
              "y":162},
            "size":{
              "width":673,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b390355ce7c44bf949c34f9f3b86c82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "lineSpacing":"60px",
                "location":{
                  "x":27,
                  "y":162},
                "size":{
                  "width":673,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2d3e9a992e34718837520159359fdcd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":125},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"d35e2f3b40284c248c8e2bbe4c542c08",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":292},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"4bf07a3c16c44e108a2945c90e46af3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'黑体 Regular', '黑体'",
            "fontSize":"36px",
            "lineSpacing":"60px",
            "location":{
              "x":27,
              "y":330},
            "size":{
              "width":653,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8b011f14342474c8750e2117fae692f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'黑体 Regular', '黑体'",
                "fontSize":"36px",
                "lineSpacing":"60px",
                "location":{
                  "x":27,
                  "y":330},
                "size":{
                  "width":653,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "dab1fa1e74bb40289bbb68c6217f05f3":{
      "scriptId":"u0"},
    "a3a1dfa08da54a8aaca1378092508dbf":{
      "scriptId":"u1"},
    "fc6f7a25459b4aa69d30e1d63810ce85":{
      "scriptId":"u2"},
    "95aa9dc5767f42909d7ac9afb9f50d91":{
      "scriptId":"u3"},
    "515fc6e73b134508bc9e90c97e38aa62":{
      "scriptId":"u4"},
    "70e9fa33967543429dfaab43d864c85d":{
      "scriptId":"u5"},
    "6ba24a2c443e4fd7a24567a7cc826e22":{
      "scriptId":"u6"},
    "fe171f62fbe2486385741b23de123ed0":{
      "scriptId":"u7"},
    "643bbac6e6814bdd9dfeb6ac0a02903d":{
      "scriptId":"u8"},
    "ccc4afa7dd684822b583e168e8dd207d":{
      "scriptId":"u9"},
    "f9856e474cd34fcd9d3ac4ed1df1279e":{
      "scriptId":"u10"},
    "80faa5c293cc4df5857299853933c6ec":{
      "scriptId":"u11"},
    "4b390355ce7c44bf949c34f9f3b86c82":{
      "scriptId":"u12"},
    "c2d3e9a992e34718837520159359fdcd":{
      "scriptId":"u13"},
    "d35e2f3b40284c248c8e2bbe4c542c08":{
      "scriptId":"u14"},
    "4bf07a3c16c44e108a2945c90e46af3f":{
      "scriptId":"u15"},
    "b8b011f14342474c8750e2117fae692f":{
      "scriptId":"u16"}}});