$axure.loadCurrentPage({
  "url":"orders-sale.html",
  "generationDate":new Date(1444814344427.99),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5995c5680cb3479db4c8dfb8e8b4ad44",
    "type":"Axure:Page",
    "name":"Orders-sale",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"45c4ba8b3f12430ca78f0f15a81079bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":14},
            "size":{
              "width":720,
              "height":2266},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bfa843e48d841e482b0df791ed976f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":14},
                "size":{
                  "width":720,
                  "height":2266},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-buy/u0.png"}},
{
          "id":"ea10b8698a8b4d97bd2ed1373652a222",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68720d9abaa54fb09896a29b9ba7001c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"6981a7d5c1d04f679e44c996cdd3bc6e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"844060582702435cb49b69f46b9ed258",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":14},
            "size":{
              "width":69,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a0b9e7fe9714e5e88512f32f1e7d8fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":14},
                "size":{
                  "width":69,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 UserConter-orders",
                      "target":{
                        "targetType":"page",
                        "url":"userconter-orders.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"c6b6c60cce5a45cc8fdff6c0a44cf1f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "location":{
              "x":280,
              "y":22},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"260af7aed874419fb17277ebb5593e7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "location":{
                  "x":280,
                  "y":22},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06b1a55d3c3347c690ff11f534e4eba0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":134},
            "size":{
              "width":720,
              "height":706},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf1d5122bb404005a960e330a23f3c84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":134},
                "size":{
                  "width":720,
                  "height":706},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-buy/u9.png"}},
{
          "id":"d360c6cea9af4095a327574e74651ab8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "lineSpacing":"60px",
            "location":{
              "x":27,
              "y":277},
            "size":{
              "width":397,
              "height":540}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a814e3ff0e4e4bb4b585055a67de6ff0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "lineSpacing":"60px",
                "location":{
                  "x":27,
                  "y":277},
                "size":{
                  "width":397,
                  "height":540}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4126f81b1ff545718f803d0fb3430e98",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":130},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"aafd82197de04c638e9070fc20b71d34",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":835},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"b397b5f309794148999a65a35e63a4db",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":252},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"7cfcb1ceb0c24cd790679fc32ff676dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":153},
            "size":{
              "width":490,
              "height":85},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b9d2b35f3564dfa856d043de70c5707",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":153},
                "size":{
                  "width":490,
                  "height":85},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-buy/u16.png"}},
{
          "id":"bd8304f3c0f340dc811990b29a98fc4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":530,
              "y":153},
            "size":{
              "width":164,
              "height":85},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0adeb416d859430fab99c21c0a112b70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":530,
                  "y":153},
                "size":{
                  "width":164,
                  "height":85},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDBDBDB},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-buy/u18.png"}},
{
          "id":"d2ead49a5f3344a49eb3fa51f13c49d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":576,
              "y":172},
            "size":{
              "width":73,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"263e252ba8db489bb69228e64dd9d1db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":576,
                  "y":172},
                "size":{
                  "width":73,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d3a1e68cdc74b7e86283b62d1c1d80e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":874},
            "size":{
              "width":720,
              "height":606},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45013f78365b48078a0549582d9c88e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":874},
                "size":{
                  "width":720,
                  "height":606},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-buy/u22.png"}},
{
          "id":"255c6175eac14bfca85098a4a27c63b7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1476},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"d75a48faae3141e4b04e9d194f7f4057",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":869},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"f8765c768fcb4328b701804bca66226e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "lineSpacing":"60px",
            "location":{
              "x":27,
              "y":900},
            "size":{
              "width":397,
              "height":540}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73ed741137c1495ca137a338719e8952",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "lineSpacing":"60px",
                "location":{
                  "x":27,
                  "y":900},
                "size":{
                  "width":397,
                  "height":540}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95f80806df36499f87e74dc11294f99c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1512},
            "size":{
              "width":720,
              "height":606},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09fed9da6845444eaaa7958b48750fd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1512},
                "size":{
                  "width":720,
                  "height":606},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-buy/u22.png"}},
{
          "id":"2972d6e2deda458b82bb0508c300aa83",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":2114},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"3c378157a024495e80df067a42e0d0f4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1507},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"7167541d22c046fcaa826ddf0b71948f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "lineSpacing":"60px",
            "location":{
              "x":27,
              "y":1538},
            "size":{
              "width":397,
              "height":540}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7348e40959142cdb6c37b8521f5ca2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "lineSpacing":"60px",
                "location":{
                  "x":27,
                  "y":1538},
                "size":{
                  "width":397,
                  "height":540}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c54205fcc7c46a4af0d01f375a0cd68",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":38,
              "y":2142},
            "size":{
              "width":65,
              "height":65},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b6c79e86bf3443aa436a92531292d89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":38,
                  "y":2142},
                "size":{
                  "width":65,
                  "height":65},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/info/u51.png"}},
{
          "id":"3545039a74324663b0a31642e590eff6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":115,
              "y":2142},
            "size":{
              "width":65,
              "height":65},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39d44ee86e9d4524856f6c592650b832",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":115,
                  "y":2142},
                "size":{
                  "width":65,
                  "height":65},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/info/u51.png"}},
{
          "id":"21d2d58ee315431a95061e640088a610",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":193,
              "y":2142},
            "size":{
              "width":65,
              "height":65},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"037c59ecdd8042d7b47916dfc1a4024b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":193,
                  "y":2142},
                "size":{
                  "width":65,
                  "height":65},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/info/u55.png"}},
{
          "id":"38f28fa182834313a97135d9d856806a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":270,
              "y":2142},
            "size":{
              "width":65,
              "height":65},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36db689db46f4c41832b9f9f0bd08269",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":270,
                  "y":2142},
                "size":{
                  "width":65,
                  "height":65},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/info/u51.png"}},
{
          "id":"b32026ce26524268931e90bf864244b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":348,
              "y":2142},
            "size":{
              "width":65,
              "height":65},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c45e73156814456939bac56bf686de6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":348,
                  "y":2142},
                "size":{
                  "width":65,
                  "height":65},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/info/u51.png"}},
{
          "id":"4660fde8fd5942febcc085f340af735b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":462,
              "y":2142},
            "size":{
              "width":65,
              "height":65},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c34a9165d90b45a28aee8067914bc755",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":462,
                  "y":2142},
                "size":{
                  "width":65,
                  "height":65},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/info/u51.png"}},
{
          "id":"1b510b63a7df4abe8a1ef561fe089e58",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":424,
              "y":2140},
            "size":{
              "width":27,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e24715ea2cde47b8be98389c1c864f7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":424,
                  "y":2140},
                "size":{
                  "width":27,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"52341378977e4b12a08b6845f3f3314e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":540,
              "y":2142},
            "size":{
              "width":65,
              "height":65},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"292d6b6d5d8444b283d9ed4c383de979",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":540,
                  "y":2142},
                "size":{
                  "width":65,
                  "height":65},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/info/u51.png"}},
{
          "id":"c0f149159fe545349ba43fef1132344b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":617,
              "y":2142},
            "size":{
              "width":65,
              "height":65},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73149094de3a4f79b991dbd6328a29af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":617,
                  "y":2142},
                "size":{
                  "width":65,
                  "height":65},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/info/u51.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "45c4ba8b3f12430ca78f0f15a81079bd":{
      "scriptId":"u0"},
    "4bfa843e48d841e482b0df791ed976f8":{
      "scriptId":"u1"},
    "ea10b8698a8b4d97bd2ed1373652a222":{
      "scriptId":"u2"},
    "68720d9abaa54fb09896a29b9ba7001c":{
      "scriptId":"u3"},
    "6981a7d5c1d04f679e44c996cdd3bc6e":{
      "scriptId":"u4"},
    "844060582702435cb49b69f46b9ed258":{
      "scriptId":"u5"},
    "2a0b9e7fe9714e5e88512f32f1e7d8fa":{
      "scriptId":"u6"},
    "c6b6c60cce5a45cc8fdff6c0a44cf1f4":{
      "scriptId":"u7"},
    "260af7aed874419fb17277ebb5593e7b":{
      "scriptId":"u8"},
    "06b1a55d3c3347c690ff11f534e4eba0":{
      "scriptId":"u9"},
    "bf1d5122bb404005a960e330a23f3c84":{
      "scriptId":"u10"},
    "d360c6cea9af4095a327574e74651ab8":{
      "scriptId":"u11"},
    "a814e3ff0e4e4bb4b585055a67de6ff0":{
      "scriptId":"u12"},
    "4126f81b1ff545718f803d0fb3430e98":{
      "scriptId":"u13"},
    "aafd82197de04c638e9070fc20b71d34":{
      "scriptId":"u14"},
    "b397b5f309794148999a65a35e63a4db":{
      "scriptId":"u15"},
    "7cfcb1ceb0c24cd790679fc32ff676dc":{
      "scriptId":"u16"},
    "1b9d2b35f3564dfa856d043de70c5707":{
      "scriptId":"u17"},
    "bd8304f3c0f340dc811990b29a98fc4d":{
      "scriptId":"u18"},
    "0adeb416d859430fab99c21c0a112b70":{
      "scriptId":"u19"},
    "d2ead49a5f3344a49eb3fa51f13c49d4":{
      "scriptId":"u20"},
    "263e252ba8db489bb69228e64dd9d1db":{
      "scriptId":"u21"},
    "9d3a1e68cdc74b7e86283b62d1c1d80e":{
      "scriptId":"u22"},
    "45013f78365b48078a0549582d9c88e0":{
      "scriptId":"u23"},
    "255c6175eac14bfca85098a4a27c63b7":{
      "scriptId":"u24"},
    "d75a48faae3141e4b04e9d194f7f4057":{
      "scriptId":"u25"},
    "f8765c768fcb4328b701804bca66226e":{
      "scriptId":"u26"},
    "73ed741137c1495ca137a338719e8952":{
      "scriptId":"u27"},
    "95f80806df36499f87e74dc11294f99c":{
      "scriptId":"u28"},
    "09fed9da6845444eaaa7958b48750fd2":{
      "scriptId":"u29"},
    "2972d6e2deda458b82bb0508c300aa83":{
      "scriptId":"u30"},
    "3c378157a024495e80df067a42e0d0f4":{
      "scriptId":"u31"},
    "7167541d22c046fcaa826ddf0b71948f":{
      "scriptId":"u32"},
    "a7348e40959142cdb6c37b8521f5ca2e":{
      "scriptId":"u33"},
    "5c54205fcc7c46a4af0d01f375a0cd68":{
      "scriptId":"u34"},
    "6b6c79e86bf3443aa436a92531292d89":{
      "scriptId":"u35"},
    "3545039a74324663b0a31642e590eff6":{
      "scriptId":"u36"},
    "39d44ee86e9d4524856f6c592650b832":{
      "scriptId":"u37"},
    "21d2d58ee315431a95061e640088a610":{
      "scriptId":"u38"},
    "037c59ecdd8042d7b47916dfc1a4024b":{
      "scriptId":"u39"},
    "38f28fa182834313a97135d9d856806a":{
      "scriptId":"u40"},
    "36db689db46f4c41832b9f9f0bd08269":{
      "scriptId":"u41"},
    "b32026ce26524268931e90bf864244b9":{
      "scriptId":"u42"},
    "3c45e73156814456939bac56bf686de6":{
      "scriptId":"u43"},
    "4660fde8fd5942febcc085f340af735b":{
      "scriptId":"u44"},
    "c34a9165d90b45a28aee8067914bc755":{
      "scriptId":"u45"},
    "1b510b63a7df4abe8a1ef561fe089e58":{
      "scriptId":"u46"},
    "e24715ea2cde47b8be98389c1c864f7b":{
      "scriptId":"u47"},
    "52341378977e4b12a08b6845f3f3314e":{
      "scriptId":"u48"},
    "292d6b6d5d8444b283d9ed4c383de979":{
      "scriptId":"u49"},
    "c0f149159fe545349ba43fef1132344b":{
      "scriptId":"u50"},
    "73149094de3a4f79b991dbd6328a29af":{
      "scriptId":"u51"}}});