$axure.loadCurrentPage({
  "url":"release-buy-plans2-2.html",
  "generationDate":new Date(1444814343572.94),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b20445841f074fca83e1af823411fdbb",
    "type":"Axure:Page",
    "name":"release-buy-plans2-2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3a38cdb407d14906956ef29d61f05fa1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":100},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef3722207fdc40aebdf2e06bb35b19ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":92},
                "size":{
                  "width":720,
                  "height":100},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/release-buy/u0.png"}},
{
          "id":"ca2b7a942ab44ae98e0bd95d01ced756",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31031379a84c49a29607073c809df73b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"d4cbfdd535d84bc4b0651ca50bbf572c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"7f761a1c2d7240fc8b764a75bcbd47e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":14},
            "size":{
              "width":69,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9c1c7e6ec7e4ec8aed7d1a1fd3174d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":14},
                "size":{
                  "width":69,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"c96183e5b4204b7db13ff25de430a152",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "location":{
              "x":280,
              "y":22},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84b810e9d6954a92a33b288488f3f279",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "location":{
                  "x":280,
                  "y":22},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa1845387ca34567866081522d37a794",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":186},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"5536967dabab4bacbbd39332068e2b40",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0094DE,
              "opacity":1},
            "location":{
              "x":324,
              "y":120},
            "size":{
              "width":73,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3390f1e879646fb911cfd18f6a75e8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE,
                  "opacity":1},
                "location":{
                  "x":324,
                  "y":120},
                "size":{
                  "width":73,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"09dc7990e4ad44b1894e21ab777a1ffd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":252},
            "size":{
              "width":660,
              "height":96},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a02127a7ab9d430a87d5e40c002805cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":252},
                "size":{
                  "width":660,
                  "height":96},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDBDBDB},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u9.png"}},
{
          "id":"2de4ea05d90a4fa5907b2e83f0cc9c8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":30,
              "y":386},
            "size":{
              "width":660,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ecaf7d7f1c041158578e62a061a5ecb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":30,
                  "y":386},
                "size":{
                  "width":660,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDBDBDB},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u17.png"}},
{
          "id":"9d7f3df834d0470a91e2ce1789db1bd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":320,
              "y":408},
            "size":{
              "width":81,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ae93d6fad204e20abaca3d129254f6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":408},
                "size":{
                  "width":81,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0d7d1a27fad417384ea798df3b59688",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":59,
              "y":280},
            "size":{
              "width":153,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f259ab2231e407aa34f2061132ccc06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":59,
                  "y":280},
                "size":{
                  "width":153,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "3a38cdb407d14906956ef29d61f05fa1":{
      "scriptId":"u0"},
    "ef3722207fdc40aebdf2e06bb35b19ce":{
      "scriptId":"u1"},
    "ca2b7a942ab44ae98e0bd95d01ced756":{
      "scriptId":"u2"},
    "31031379a84c49a29607073c809df73b":{
      "scriptId":"u3"},
    "d4cbfdd535d84bc4b0651ca50bbf572c":{
      "scriptId":"u4"},
    "7f761a1c2d7240fc8b764a75bcbd47e6":{
      "scriptId":"u5"},
    "f9c1c7e6ec7e4ec8aed7d1a1fd3174d8":{
      "scriptId":"u6"},
    "c96183e5b4204b7db13ff25de430a152":{
      "scriptId":"u7"},
    "84b810e9d6954a92a33b288488f3f279":{
      "scriptId":"u8"},
    "aa1845387ca34567866081522d37a794":{
      "scriptId":"u9"},
    "5536967dabab4bacbbd39332068e2b40":{
      "scriptId":"u10"},
    "d3390f1e879646fb911cfd18f6a75e8d":{
      "scriptId":"u11"},
    "09dc7990e4ad44b1894e21ab777a1ffd":{
      "scriptId":"u12"},
    "a02127a7ab9d430a87d5e40c002805cb":{
      "scriptId":"u13"},
    "2de4ea05d90a4fa5907b2e83f0cc9c8c":{
      "scriptId":"u14"},
    "4ecaf7d7f1c041158578e62a061a5ecb":{
      "scriptId":"u15"},
    "9d7f3df834d0470a91e2ce1789db1bd0":{
      "scriptId":"u16"},
    "6ae93d6fad204e20abaca3d129254f6c":{
      "scriptId":"u17"},
    "e0d7d1a27fad417384ea798df3b59688":{
      "scriptId":"u18"},
    "4f259ab2231e407aa34f2061132ccc06":{
      "scriptId":"u19"}}});