$axure.loadCurrentPage({
  "url":"orders-buy.html",
  "generationDate":new Date(1444814344023.97),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"614b954756a74b55b33a1e3f4c07bc07",
    "type":"Axure:Page",
    "name":"Orders-buy",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"93373ebaead5430aa4400c135ed4b2f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":14},
            "size":{
              "width":720,
              "height":2266},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99f18b0fa37d480bb10d8becff71174b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":14},
                "size":{
                  "width":720,
                  "height":2266},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-buy/u0.png"}},
{
          "id":"801626d078ca46be97deef3aa5732e5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e154839cfa2b4d2f98451f2a4d80183c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"b6e7a36ff9584b0b85cca32f54e8d004",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"96f86fb44a0049ec996a1e677422ee78",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":14},
            "size":{
              "width":69,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4762e903af5d4e92b9544f6bd739eed2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":14},
                "size":{
                  "width":69,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 UserConter-orders",
                      "target":{
                        "targetType":"page",
                        "url":"userconter-orders.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"06b08de0309f4b1cbb2f2a644cdbd3ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "location":{
              "x":280,
              "y":22},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"462e2213baca4c83a9ee6ac724049b22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "location":{
                  "x":280,
                  "y":22},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c84cc0c6c9f54c3cbe2a08430c68b7ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":134},
            "size":{
              "width":720,
              "height":706},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"507f44d19dd8456c88f089d066a6f7f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":134},
                "size":{
                  "width":720,
                  "height":706},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-buy/u9.png"}},
{
          "id":"d354079f6ef54dd8b9314b9d4a2586b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "lineSpacing":"60px",
            "location":{
              "x":27,
              "y":277},
            "size":{
              "width":397,
              "height":540}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cc37290162c4a2191fc61d9ad4ddc32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "lineSpacing":"60px",
                "location":{
                  "x":27,
                  "y":277},
                "size":{
                  "width":397,
                  "height":540}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Orders-buy-content",
                      "target":{
                        "targetType":"page",
                        "url":"orders-buy-content.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ede4252e8dbf4374a4e629bbff6a3214",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":130},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"73c7a732a2ba48cc812e241542ae125f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":835},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"649f962adc2e46d7adedf7bf0be8f4df",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":252},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"d80b5acdc4234beeb2809fb63193dd35",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":153},
            "size":{
              "width":490,
              "height":85},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"987961b9a44c45fa8a220e5349e6c7aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":153},
                "size":{
                  "width":490,
                  "height":85},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-buy/u16.png"}},
{
          "id":"e1cecc6e96b349a3820fb7eddf166d21",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":530,
              "y":153},
            "size":{
              "width":164,
              "height":85},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77659f5a3fd44137b074bf6ac744df06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":530,
                  "y":153},
                "size":{
                  "width":164,
                  "height":85},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDBDBDB},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-buy/u18.png"}},
{
          "id":"cf31fd3c39d447fb9f896025c7b36355",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":576,
              "y":172},
            "size":{
              "width":73,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5ddf32901934087bbf5b0c6f8e6ad2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":576,
                  "y":172},
                "size":{
                  "width":73,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc69e1fd5b4d4b018b42f5242b83f90c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":874},
            "size":{
              "width":720,
              "height":606},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d17c9102cca446399858f1b7211af560",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":874},
                "size":{
                  "width":720,
                  "height":606},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-buy/u22.png"}},
{
          "id":"e6fb8e296a454cefae18ea5b262a634b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1476},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"5415367796224b35af7b1dc0cce874fe",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":869},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"d51aa0c221a94525809eb9db5bb45076",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "lineSpacing":"60px",
            "location":{
              "x":27,
              "y":900},
            "size":{
              "width":397,
              "height":540}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2ee16a6ed154fe1ac4fcac6288d323f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "lineSpacing":"60px",
                "location":{
                  "x":27,
                  "y":900},
                "size":{
                  "width":397,
                  "height":540}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e338b47a5f1d4925b9ea9d157c7e6a3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1512},
            "size":{
              "width":720,
              "height":606},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8ab073f455e4123bb924353b1a5c4f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1512},
                "size":{
                  "width":720,
                  "height":606},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-buy/u22.png"}},
{
          "id":"5d1e1af881ef480bb5bfa216231ead20",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":2114},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"ceebd03271bd4c098b0120d41f2ceadb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1507},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"d675aef8eabc44b8a4c78c10b9770251",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "lineSpacing":"60px",
            "location":{
              "x":27,
              "y":1538},
            "size":{
              "width":397,
              "height":540}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c6a94c28b814b55ae0071900e510e57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "lineSpacing":"60px",
                "location":{
                  "x":27,
                  "y":1538},
                "size":{
                  "width":397,
                  "height":540}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e066b3cf0ee4f72a0212c8bc9f47c11",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":38,
              "y":2142},
            "size":{
              "width":65,
              "height":65},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e23e23398d89471eac55c522b8770831",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":38,
                  "y":2142},
                "size":{
                  "width":65,
                  "height":65},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/info/u51.png"}},
{
          "id":"f14263ec260c46c49d5d847246e644ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":115,
              "y":2142},
            "size":{
              "width":65,
              "height":65},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41b3547a43404c8193fffbd57c052d67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":115,
                  "y":2142},
                "size":{
                  "width":65,
                  "height":65},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/info/u51.png"}},
{
          "id":"74cdd85dca1d4e7c8710a06c1c0a62bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":193,
              "y":2142},
            "size":{
              "width":65,
              "height":65},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"768841b7096349178fa6adee86a98e15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":193,
                  "y":2142},
                "size":{
                  "width":65,
                  "height":65},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/info/u55.png"}},
{
          "id":"f56e2dbd03aa4a85a06ccebb6b39bf3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":270,
              "y":2142},
            "size":{
              "width":65,
              "height":65},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"682d26a620cc4ebfa7168ab8bf80356d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":270,
                  "y":2142},
                "size":{
                  "width":65,
                  "height":65},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/info/u51.png"}},
{
          "id":"3b2190c847bc4e8085ef78e3dab6c103",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":348,
              "y":2142},
            "size":{
              "width":65,
              "height":65},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f33784a83714d4c996fab173a6d0534",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":348,
                  "y":2142},
                "size":{
                  "width":65,
                  "height":65},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/info/u51.png"}},
{
          "id":"17a0601759474d08bdc574c18e6712b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":462,
              "y":2142},
            "size":{
              "width":65,
              "height":65},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f72a82b969104b35a0c026b3ee4c7477",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":462,
                  "y":2142},
                "size":{
                  "width":65,
                  "height":65},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/info/u51.png"}},
{
          "id":"ffa88f34b4d944c2a91a958cb22e6624",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":424,
              "y":2140},
            "size":{
              "width":27,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67fd3e652fa04f389b3e6fa029a1d26e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":424,
                  "y":2140},
                "size":{
                  "width":27,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4545eec7399142c690174547cdde7443",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":540,
              "y":2142},
            "size":{
              "width":65,
              "height":65},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0cdf3da089242ba8db2edc7f4d7df47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":540,
                  "y":2142},
                "size":{
                  "width":65,
                  "height":65},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/info/u51.png"}},
{
          "id":"8f01c45e9dae41fa8f957e04ed8186c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":617,
              "y":2142},
            "size":{
              "width":65,
              "height":65},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60406021231e4ac58938d46bc93b7423",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":617,
                  "y":2142},
                "size":{
                  "width":65,
                  "height":65},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/info/u51.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "93373ebaead5430aa4400c135ed4b2f3":{
      "scriptId":"u0"},
    "99f18b0fa37d480bb10d8becff71174b":{
      "scriptId":"u1"},
    "801626d078ca46be97deef3aa5732e5c":{
      "scriptId":"u2"},
    "e154839cfa2b4d2f98451f2a4d80183c":{
      "scriptId":"u3"},
    "b6e7a36ff9584b0b85cca32f54e8d004":{
      "scriptId":"u4"},
    "96f86fb44a0049ec996a1e677422ee78":{
      "scriptId":"u5"},
    "4762e903af5d4e92b9544f6bd739eed2":{
      "scriptId":"u6"},
    "06b08de0309f4b1cbb2f2a644cdbd3ad":{
      "scriptId":"u7"},
    "462e2213baca4c83a9ee6ac724049b22":{
      "scriptId":"u8"},
    "c84cc0c6c9f54c3cbe2a08430c68b7ad":{
      "scriptId":"u9"},
    "507f44d19dd8456c88f089d066a6f7f1":{
      "scriptId":"u10"},
    "d354079f6ef54dd8b9314b9d4a2586b5":{
      "scriptId":"u11"},
    "2cc37290162c4a2191fc61d9ad4ddc32":{
      "scriptId":"u12"},
    "ede4252e8dbf4374a4e629bbff6a3214":{
      "scriptId":"u13"},
    "73c7a732a2ba48cc812e241542ae125f":{
      "scriptId":"u14"},
    "649f962adc2e46d7adedf7bf0be8f4df":{
      "scriptId":"u15"},
    "d80b5acdc4234beeb2809fb63193dd35":{
      "scriptId":"u16"},
    "987961b9a44c45fa8a220e5349e6c7aa":{
      "scriptId":"u17"},
    "e1cecc6e96b349a3820fb7eddf166d21":{
      "scriptId":"u18"},
    "77659f5a3fd44137b074bf6ac744df06":{
      "scriptId":"u19"},
    "cf31fd3c39d447fb9f896025c7b36355":{
      "scriptId":"u20"},
    "e5ddf32901934087bbf5b0c6f8e6ad2b":{
      "scriptId":"u21"},
    "cc69e1fd5b4d4b018b42f5242b83f90c":{
      "scriptId":"u22"},
    "d17c9102cca446399858f1b7211af560":{
      "scriptId":"u23"},
    "e6fb8e296a454cefae18ea5b262a634b":{
      "scriptId":"u24"},
    "5415367796224b35af7b1dc0cce874fe":{
      "scriptId":"u25"},
    "d51aa0c221a94525809eb9db5bb45076":{
      "scriptId":"u26"},
    "d2ee16a6ed154fe1ac4fcac6288d323f":{
      "scriptId":"u27"},
    "e338b47a5f1d4925b9ea9d157c7e6a3b":{
      "scriptId":"u28"},
    "d8ab073f455e4123bb924353b1a5c4f9":{
      "scriptId":"u29"},
    "5d1e1af881ef480bb5bfa216231ead20":{
      "scriptId":"u30"},
    "ceebd03271bd4c098b0120d41f2ceadb":{
      "scriptId":"u31"},
    "d675aef8eabc44b8a4c78c10b9770251":{
      "scriptId":"u32"},
    "6c6a94c28b814b55ae0071900e510e57":{
      "scriptId":"u33"},
    "7e066b3cf0ee4f72a0212c8bc9f47c11":{
      "scriptId":"u34"},
    "e23e23398d89471eac55c522b8770831":{
      "scriptId":"u35"},
    "f14263ec260c46c49d5d847246e644ab":{
      "scriptId":"u36"},
    "41b3547a43404c8193fffbd57c052d67":{
      "scriptId":"u37"},
    "74cdd85dca1d4e7c8710a06c1c0a62bb":{
      "scriptId":"u38"},
    "768841b7096349178fa6adee86a98e15":{
      "scriptId":"u39"},
    "f56e2dbd03aa4a85a06ccebb6b39bf3d":{
      "scriptId":"u40"},
    "682d26a620cc4ebfa7168ab8bf80356d":{
      "scriptId":"u41"},
    "3b2190c847bc4e8085ef78e3dab6c103":{
      "scriptId":"u42"},
    "6f33784a83714d4c996fab173a6d0534":{
      "scriptId":"u43"},
    "17a0601759474d08bdc574c18e6712b1":{
      "scriptId":"u44"},
    "f72a82b969104b35a0c026b3ee4c7477":{
      "scriptId":"u45"},
    "ffa88f34b4d944c2a91a958cb22e6624":{
      "scriptId":"u46"},
    "67fd3e652fa04f389b3e6fa029a1d26e":{
      "scriptId":"u47"},
    "4545eec7399142c690174547cdde7443":{
      "scriptId":"u48"},
    "b0cdf3da089242ba8db2edc7f4d7df47":{
      "scriptId":"u49"},
    "8f01c45e9dae41fa8f957e04ed8186c1":{
      "scriptId":"u50"},
    "60406021231e4ac58938d46bc93b7423":{
      "scriptId":"u51"}}});