$axure.loadCurrentPage({
  "url":"userconter-release.html",
  "generationDate":new Date(1444814344889.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1d37d40274414d63b56e04ecb512ae4e",
    "type":"Axure:Page",
    "name":"UserConter-release",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1070af292cd247afb6d6199b4074215d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":963},
            "size":{
              "width":720,
              "height":221},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09a999329d354e25b24901db88093f85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":963},
                "size":{
                  "width":720,
                  "height":221},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-orders/u0.png"}},
{
          "id":"09fd02d8f1cd47e4a8499bcbde0b77bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0094DE},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55dca6ae8ec84d8aa75a62ec3b5faf91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0094DE},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-orders/u2.png"}},
{
          "id":"796c77c2215f4fe1b58ef4355d1b4196",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":16},
            "size":{
              "width":216,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2775a8849f384f8bb60d52f1862fe172",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":16},
                "size":{
                  "width":216,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u6.png"}},
{
          "id":"81ff4e2d2eb64c6e88f612fb0029a941",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":637,
              "y":23},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56431e8d7ddf497799e6494ddbaa5380",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":637,
                  "y":23},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 About User",
                      "target":{
                        "targetType":"page",
                        "url":"about_user.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u28.png"}},
{
          "id":"81ddd1534e3448b09dc911d5744b0ad8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":0,
              "y":1073},
            "size":{
              "width":720,
              "height":108},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f134076d07aa4a0ea1c2a46de56c6d4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":0,
                  "y":1073},
                "size":{
                  "width":720,
                  "height":108},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-orders/u8.png"}},
{
          "id":"91354c304fc14719ba9742731c95fff6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1066},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"7db7bd079f9f48a49f0fd3338f5b47e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":535,
              "y":30},
            "size":{
              "width":85,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afe66028669546c9800185198056d424",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":535,
                  "y":30},
                "size":{
                  "width":85,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0e130f463cb484a8a74420187fee317",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"26px",
            "location":{
              "x":74,
              "y":1138},
            "size":{
              "width":572,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5c5aac02e544a08a0d217183a2c4880",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"26px",
                "location":{
                  "x":74,
                  "y":1138},
                "size":{
                  "width":572,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d01d7824c03345d2b0344a9002778b3e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":1085},
            "size":{
              "width":49,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a55fbe6647e46898a0697f0568b70d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":1085},
                "size":{
                  "width":49,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 UserConter-orders",
                      "target":{
                        "targetType":"page",
                        "url":"userconter-orders.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/userconter-release/u15.png"}},
{
          "id":"eed65837bf884c87945b1ef04a1622b1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":1086},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7cade2269d64aa8868fcb47f5409d23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":249,
                  "y":1086},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-release/u17.png"}},
{
          "id":"c32e3999d35e44259fb197c7409b4f97",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":419,
              "y":1086},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce371b85a83e486b8eecd210377853d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":419,
                  "y":1086},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 UserConter-my",
                      "target":{
                        "targetType":"page",
                        "url":"userconter-my.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/userconter-orders/u19.png"}},
{
          "id":"2cc0e83106784422bd8b1e88febae98e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":1086},
            "size":{
              "width":56,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69b2fd5a8a464b5783c30cd20bf97ffc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":1086},
                "size":{
                  "width":56,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/userconter-orders/u21.png"}},
{
          "id":"54e41e1aede24685894fac9a941fee20",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":129,
              "y":169},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22004bd349944d9dbb1a899ee040d54e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":129,
                  "y":169},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-orders/u23.png"}},
{
          "id":"87286845409446c090eae4791d0a7382",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":169},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e674834fbc4f49ce943c89b4d6cff71a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":169},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-orders/u23.png"}},
{
          "id":"3fabd5facce94dbc9799d78205c83be8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":107,
              "y":280},
            "size":{
              "width":145,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b57c8ebd2ae4ef8ab1219fe4461f4ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":107,
                  "y":280},
                "size":{
                  "width":145,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 MyBuy-plan",
                      "target":{
                        "targetType":"page",
                        "url":"mybuy-plan.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04c51e7c207647e09125894d8b3ea9e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":468,
              "y":280},
            "size":{
              "width":145,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68bb43e1a7d041439d1a0f857a30fc2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":468,
                  "y":280},
                "size":{
                  "width":145,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 MySale-plan",
                      "target":{
                        "targetType":"page",
                        "url":"mysale-plan.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e1e99a7964e4953b51d5c43ae0d81a7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":380},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"2098b9a8dfa44fbd9958950837fe2272",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":129,
              "y":456},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb6913fe9cb049749f4dc8d87cb6a7f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":129,
                  "y":456},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-orders/u23.png"}},
{
          "id":"5cc7c97b1cce4549ba584084f1670ec2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":456},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e3de1cb12f04628ac992669bb3af490",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":456},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-orders/u23.png"}},
{
          "id":"5ebcf6d8e4ab4fae930df104bbd0c87a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":107,
              "y":567},
            "size":{
              "width":145,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"824261d908ec47e596e71115e12af118",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":107,
                  "y":567},
                "size":{
                  "width":145,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a643aa1d0bd42c18ef13413c9dff302",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":468,
              "y":567},
            "size":{
              "width":145,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe98941a3b7142118de53240d970b925",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":468,
                  "y":567},
                "size":{
                  "width":145,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28d265b7afc04a9a8908e8313dbd4a95",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":671},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"34d96e12064f4116b55c4be3adf8d469",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":129,
              "y":744},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1487d07ceb4457caa55b422a68611bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":129,
                  "y":744},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-orders/u23.png"}},
{
          "id":"9980d034e6524feb9e87357e90669181",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":744},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70f5e7f94c0b4a06965f5051bcad2b5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":744},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-orders/u23.png"}},
{
          "id":"31deb916d5674ee6b6fecbd1ba398c4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":107,
              "y":855},
            "size":{
              "width":145,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d318930c4f0445c194e4fa6d3334ec54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":107,
                  "y":855},
                "size":{
                  "width":145,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 MyEnquiry",
                      "target":{
                        "targetType":"page",
                        "url":"myenquiry.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0ff3db3e3aa4ea89e53a827257daf2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":468,
              "y":855},
            "size":{
              "width":145,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11387326e7b34ac0a840c831c2ccf3a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":468,
                  "y":855},
                "size":{
                  "width":145,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 MyAttention",
                      "target":{
                        "targetType":"page",
                        "url":"myattention.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e97297868a55495fa75141e43631dd83",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":959},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"bd168104160c4b6a9ca18b88577abbf6",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":355,
              "y":96},
            "size":{
              "width":10,
              "height":868},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/userconter-orders/u50_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "1070af292cd247afb6d6199b4074215d":{
      "scriptId":"u0"},
    "09a999329d354e25b24901db88093f85":{
      "scriptId":"u1"},
    "09fd02d8f1cd47e4a8499bcbde0b77bb":{
      "scriptId":"u2"},
    "55dca6ae8ec84d8aa75a62ec3b5faf91":{
      "scriptId":"u3"},
    "796c77c2215f4fe1b58ef4355d1b4196":{
      "scriptId":"u4"},
    "2775a8849f384f8bb60d52f1862fe172":{
      "scriptId":"u5"},
    "81ff4e2d2eb64c6e88f612fb0029a941":{
      "scriptId":"u6"},
    "56431e8d7ddf497799e6494ddbaa5380":{
      "scriptId":"u7"},
    "81ddd1534e3448b09dc911d5744b0ad8":{
      "scriptId":"u8"},
    "f134076d07aa4a0ea1c2a46de56c6d4a":{
      "scriptId":"u9"},
    "91354c304fc14719ba9742731c95fff6":{
      "scriptId":"u10"},
    "7db7bd079f9f48a49f0fd3338f5b47e1":{
      "scriptId":"u11"},
    "afe66028669546c9800185198056d424":{
      "scriptId":"u12"},
    "f0e130f463cb484a8a74420187fee317":{
      "scriptId":"u13"},
    "a5c5aac02e544a08a0d217183a2c4880":{
      "scriptId":"u14"},
    "d01d7824c03345d2b0344a9002778b3e":{
      "scriptId":"u15"},
    "6a55fbe6647e46898a0697f0568b70d5":{
      "scriptId":"u16"},
    "eed65837bf884c87945b1ef04a1622b1":{
      "scriptId":"u17"},
    "b7cade2269d64aa8868fcb47f5409d23":{
      "scriptId":"u18"},
    "c32e3999d35e44259fb197c7409b4f97":{
      "scriptId":"u19"},
    "ce371b85a83e486b8eecd210377853d7":{
      "scriptId":"u20"},
    "2cc0e83106784422bd8b1e88febae98e":{
      "scriptId":"u21"},
    "69b2fd5a8a464b5783c30cd20bf97ffc":{
      "scriptId":"u22"},
    "54e41e1aede24685894fac9a941fee20":{
      "scriptId":"u23"},
    "22004bd349944d9dbb1a899ee040d54e":{
      "scriptId":"u24"},
    "87286845409446c090eae4791d0a7382":{
      "scriptId":"u25"},
    "e674834fbc4f49ce943c89b4d6cff71a":{
      "scriptId":"u26"},
    "3fabd5facce94dbc9799d78205c83be8":{
      "scriptId":"u27"},
    "7b57c8ebd2ae4ef8ab1219fe4461f4ec":{
      "scriptId":"u28"},
    "04c51e7c207647e09125894d8b3ea9e3":{
      "scriptId":"u29"},
    "68bb43e1a7d041439d1a0f857a30fc2d":{
      "scriptId":"u30"},
    "8e1e99a7964e4953b51d5c43ae0d81a7":{
      "scriptId":"u31"},
    "2098b9a8dfa44fbd9958950837fe2272":{
      "scriptId":"u32"},
    "fb6913fe9cb049749f4dc8d87cb6a7f6":{
      "scriptId":"u33"},
    "5cc7c97b1cce4549ba584084f1670ec2":{
      "scriptId":"u34"},
    "2e3de1cb12f04628ac992669bb3af490":{
      "scriptId":"u35"},
    "5ebcf6d8e4ab4fae930df104bbd0c87a":{
      "scriptId":"u36"},
    "824261d908ec47e596e71115e12af118":{
      "scriptId":"u37"},
    "2a643aa1d0bd42c18ef13413c9dff302":{
      "scriptId":"u38"},
    "fe98941a3b7142118de53240d970b925":{
      "scriptId":"u39"},
    "28d265b7afc04a9a8908e8313dbd4a95":{
      "scriptId":"u40"},
    "34d96e12064f4116b55c4be3adf8d469":{
      "scriptId":"u41"},
    "e1487d07ceb4457caa55b422a68611bd":{
      "scriptId":"u42"},
    "9980d034e6524feb9e87357e90669181":{
      "scriptId":"u43"},
    "70f5e7f94c0b4a06965f5051bcad2b5e":{
      "scriptId":"u44"},
    "31deb916d5674ee6b6fecbd1ba398c4c":{
      "scriptId":"u45"},
    "d318930c4f0445c194e4fa6d3334ec54":{
      "scriptId":"u46"},
    "f0ff3db3e3aa4ea89e53a827257daf2a":{
      "scriptId":"u47"},
    "11387326e7b34ac0a840c831c2ccf3a1":{
      "scriptId":"u48"},
    "e97297868a55495fa75141e43631dd83":{
      "scriptId":"u49"},
    "bd168104160c4b6a9ca18b88577abbf6":{
      "scriptId":"u50"}}});