$axure.loadCurrentPage({
  "url":"mysale-content.html",
  "generationDate":new Date(1444814345500.05),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0fae46289dfd4eda85409192b6b01880",
    "type":"Axure:Page",
    "name":"MySale-content",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b988b31293cc4380b9f5d4db61f9a2a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":1728},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c73f11ff09c04df49a28c4b148f1ca4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":92},
                "size":{
                  "width":720,
                  "height":1728},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mysale-content/u0.png"}},
{
          "id":"48a5baa313874f7091b8103a24865086",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06c64ff0ac424a61934d0b62fe336de2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"8977716142284142a76b7d09dd3cf5af",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"6e033a44fada492795a05dc068de2609",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":14},
            "size":{
              "width":69,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ca2d37299c64463b46645e62c71456e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":14},
                "size":{
                  "width":69,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 MySale-plan",
                      "target":{
                        "targetType":"page",
                        "url":"mysale-plan.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"df1f220d687e4391aa4b5f2b41fa8dd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "location":{
              "x":280,
              "y":22},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7631aa68a0d443d1bbd4766631a511ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "location":{
                  "x":280,
                  "y":22},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42900e31cbe84407bcf18be35fff062e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":131},
            "size":{
              "width":720,
              "height":474},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7f7b208e7e74a97ae08a384079b71b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":131},
                "size":{
                  "width":720,
                  "height":474},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mysale-content/u9.png"}},
{
          "id":"2493ab17a2034fd3a60debfcae52991c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "lineSpacing":"60px",
            "location":{
              "x":27,
              "y":153},
            "size":{
              "width":374,
              "height":420}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f44ef6c201946db9822aa2eaa72c6d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "lineSpacing":"60px",
                "location":{
                  "x":27,
                  "y":153},
                "size":{
                  "width":374,
                  "height":420}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f512986a105142b6a76541ded3477452",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":125},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"60dad586a7be4006af04ba7aec4755bc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":599},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"cf8cf0d2291644339517f9d7add45485",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":633},
            "size":{
              "width":720,
              "height":1137},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0189629d76784e1db9ef4b93176d8703",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":633},
                "size":{
                  "width":720,
                  "height":1137},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mysale-content/u15.png"}},
{
          "id":"c16bc309f5094853b63c9ae2c796f300",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1764},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"c9e047a5c9684869bcbef8341a7d755e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":627},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"d61e2e8a025f4af7976ab32ea5942eb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"40px",
            "location":{
              "x":27,
              "y":657},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f19477726884d98a15ff21ce2cfe88d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"40px",
                "location":{
                  "x":27,
                  "y":657},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03d9b81df6014530b9c76ed2502f85ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "lineSpacing":"60px",
            "location":{
              "x":27,
              "y":746},
            "size":{
              "width":462,
              "height":960}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1f7c6e9962649f081fe8717d7993f5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"60px",
                "location":{
                  "x":27,
                  "y":746},
                "size":{
                  "width":462,
                  "height":960}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"020106da340e438e9336fa44f7cc1954",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":724},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "b988b31293cc4380b9f5d4db61f9a2a5":{
      "scriptId":"u0"},
    "c73f11ff09c04df49a28c4b148f1ca4a":{
      "scriptId":"u1"},
    "48a5baa313874f7091b8103a24865086":{
      "scriptId":"u2"},
    "06c64ff0ac424a61934d0b62fe336de2":{
      "scriptId":"u3"},
    "8977716142284142a76b7d09dd3cf5af":{
      "scriptId":"u4"},
    "6e033a44fada492795a05dc068de2609":{
      "scriptId":"u5"},
    "2ca2d37299c64463b46645e62c71456e":{
      "scriptId":"u6"},
    "df1f220d687e4391aa4b5f2b41fa8dd8":{
      "scriptId":"u7"},
    "7631aa68a0d443d1bbd4766631a511ba":{
      "scriptId":"u8"},
    "42900e31cbe84407bcf18be35fff062e":{
      "scriptId":"u9"},
    "e7f7b208e7e74a97ae08a384079b71b6":{
      "scriptId":"u10"},
    "2493ab17a2034fd3a60debfcae52991c":{
      "scriptId":"u11"},
    "8f44ef6c201946db9822aa2eaa72c6d8":{
      "scriptId":"u12"},
    "f512986a105142b6a76541ded3477452":{
      "scriptId":"u13"},
    "60dad586a7be4006af04ba7aec4755bc":{
      "scriptId":"u14"},
    "cf8cf0d2291644339517f9d7add45485":{
      "scriptId":"u15"},
    "0189629d76784e1db9ef4b93176d8703":{
      "scriptId":"u16"},
    "c16bc309f5094853b63c9ae2c796f300":{
      "scriptId":"u17"},
    "c9e047a5c9684869bcbef8341a7d755e":{
      "scriptId":"u18"},
    "d61e2e8a025f4af7976ab32ea5942eb7":{
      "scriptId":"u19"},
    "1f19477726884d98a15ff21ce2cfe88d":{
      "scriptId":"u20"},
    "03d9b81df6014530b9c76ed2502f85ff":{
      "scriptId":"u21"},
    "c1f7c6e9962649f081fe8717d7993f5b":{
      "scriptId":"u22"},
    "020106da340e438e9336fa44f7cc1954":{
      "scriptId":"u23"}}});