$axure.loadCurrentPage({
  "url":"products-info.html",
  "generationDate":new Date(1444814343282.92),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"36adfcbacf0b4a4eac2c7bedbe5301b4",
    "type":"Axure:Page",
    "name":"products-info",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2800ae790f8d4c6aaf08229c98b4e018",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":200},
            "size":{
              "width":720,
              "height":1080},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e77aa4dc214f495a8a785a54f394b35e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":200},
                "size":{
                  "width":720,
                  "height":1080},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/products-info/u0.png"}},
{
          "id":"21e25eefa5234bd38210f8e52fd7d3f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":232},
            "size":{
              "width":720,
              "height":900},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6b4b1e9705047ed874246f481519940",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":232},
                "size":{
                  "width":720,
                  "height":900},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/info/u2.png"}},
{
          "id":"4a09147410e94165a74cfd01fb45a351",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":226},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"2d4cb3c7335b4c93b2880b96a21f7bf6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54c124ef9b07494f829698ac5e9dcf0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"609acb17e52d41d8a4732ac73d263cc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "lineSpacing":"100px",
            "location":{
              "x":27,
              "y":235},
            "size":{
              "width":700,
              "height":1000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7d83afa95ea431faac663823ccdf293",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "lineSpacing":"100px",
                "location":{
                  "x":27,
                  "y":235},
                "size":{
                  "width":700,
                  "height":1000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 infoContent",
                      "target":{
                        "targetType":"page",
                        "url":"infocontent.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6355b796ff414c48b9d656d2deb6ea17",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"843806aa6afb4c85b222e20e50fe9382",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":14},
            "size":{
              "width":69,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6b3c4aae5b1480ba948438d6b5c3be6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":14},
                "size":{
                  "width":69,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 buy",
                      "target":{
                        "targetType":"page",
                        "url":"buy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"8aaadf6e1cc0440ba7ce1fbb92440066",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "location":{
              "x":315.5,
              "y":22},
            "size":{
              "width":89,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"961754c198e74016b1dbcec37ebfe2f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "location":{
                  "x":315.5,
                  "y":22},
                "size":{
                  "width":89,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f99b20a7417e4177816cbe819b82fc1a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":197},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"02536c185b434aa6a2a519a8b1505f0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":60,
              "y":127},
            "size":{
              "width":600,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d430b97b9f7b45cebc258ad8cdcad9d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":60,
                  "y":127},
                "size":{
                  "width":600,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38133d3a3b3549b09ed965a4f70234fd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":474,
              "y":194},
            "size":{
              "width":246,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/products-info/u17_line.png"}},
{
          "id":"d4df8c9d1fe449fb994206f63195a7e0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":727},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/info/u16_line.png"}},
{
          "id":"8495fe3898f2455fa14c1d15dd54256d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":631},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/info/u16_line.png"}},
{
          "id":"33b09b0235eb46128c9c6b6972c8884b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":532},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/info/u16_line.png"}},
{
          "id":"cee476c7832d4d729c8ba67fff6834ab",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":431},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/info/u16_line.png"}},
{
          "id":"4c834e8cf8514caf890717d5e87a1beb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":825},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/info/u16_line.png"}},
{
          "id":"e45424b9da5943769d39df59ce0be00b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":926},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/info/u16_line.png"}},
{
          "id":"1254027a39394f3f802e2f074ad57b85",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":1027},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/info/u16_line.png"}},
{
          "id":"83635a92a4af46309ac2fa6bff4cab27",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":1126},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/info/u16_line.png"}},
{
          "id":"1d3f124a01064d0980c37116ce693b6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":685,
              "y":366},
            "size":{
              "width":16,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a70a57892c9c4273a17fc7bac5129478",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":685,
                  "y":366},
                "size":{
                  "width":16,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2de5de5a2a154c7798fb8a7c212d3113",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":685,
              "y":471},
            "size":{
              "width":16,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dd2d6daa2974d90a97529e66f67e7bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":685,
                  "y":471},
                "size":{
                  "width":16,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e4cf25c65e74047bdf6749b8b9fed58",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":685,
              "y":572},
            "size":{
              "width":16,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a40c26a023f40b2af7bc12efe5315ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":685,
                  "y":572},
                "size":{
                  "width":16,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f70bf0e49e4416f9d6bae2bdf1572e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":685,
              "y":669},
            "size":{
              "width":16,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cff82db6d884108971f4dffccae7580",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":685,
                  "y":669},
                "size":{
                  "width":16,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d383a3fb6dab4d60a9e61ac7618e7dba",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":685,
              "y":764},
            "size":{
              "width":16,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae3aa949006f43a992b2df12bb21ccff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":685,
                  "y":764},
                "size":{
                  "width":16,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e40beca4f3f84acd8fa54da98710119e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":685,
              "y":866},
            "size":{
              "width":16,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"116b003c831b4394ac24ecb3a3cbc0ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":685,
                  "y":866},
                "size":{
                  "width":16,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f5ae84f956d4e75ae5d7bb5862f260c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":685,
              "y":969},
            "size":{
              "width":16,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b428aaf0c5b4efbb51e647af28ef6b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":685,
                  "y":969},
                "size":{
                  "width":16,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b086f54f1adc4acebb77e15cf2313175",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":685,
              "y":1065},
            "size":{
              "width":16,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71db1d73667747bbae62f4bdfea6e9d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":685,
                  "y":1065},
                "size":{
                  "width":16,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"caf6da5c6411499490caaa91605d7f6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":685,
              "y":270},
            "size":{
              "width":16,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc2d806bda724cd59c7dd24ccb9a73a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":685,
                  "y":270},
                "size":{
                  "width":16,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be993b61ec714b17b13cd862ea5a4538",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":331},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/info/u16_line.png"}},
{
          "id":"cb5a97e2932046969afa95f595645fd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":641,
              "y":30},
            "size":{
              "width":57,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7e05ab90bc74c92ac26bc3624f00c54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":641,
                  "y":30},
                "size":{
                  "width":57,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9535f315cc64b54b81ec30146119509",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":583,
              "y":24},
            "size":{
              "width":48,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56690b01a67d41738f205a65e293d010",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":583,
                  "y":24},
                "size":{
                  "width":48,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/info/u49.png"}},
{
          "id":"b86ca3e89b2947949c2e1446af0063f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":38,
              "y":1166},
            "size":{
              "width":65,
              "height":65},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a44d8886f4814c9ba6c94c75f1271898",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":38,
                  "y":1166},
                "size":{
                  "width":65,
                  "height":65},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/info/u51.png"}},
{
          "id":"0e10e3ff3dda462ea2020d7a9cf2a8bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":115,
              "y":1166},
            "size":{
              "width":65,
              "height":65},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a776901afaf2460dbc6ce6377971b38c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":115,
                  "y":1166},
                "size":{
                  "width":65,
                  "height":65},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/info/u51.png"}},
{
          "id":"f5321649a85d47e6a2e3e4885f976c7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":193,
              "y":1166},
            "size":{
              "width":65,
              "height":65},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"891ddb76fff943ea996fbe03a23b7ca3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":193,
                  "y":1166},
                "size":{
                  "width":65,
                  "height":65},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/info/u55.png"}},
{
          "id":"0e963772e3e34c8c91c4e062ca4b71fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":270,
              "y":1166},
            "size":{
              "width":65,
              "height":65},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2571f5ec6198473d990349ac92337eda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":270,
                  "y":1166},
                "size":{
                  "width":65,
                  "height":65},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/info/u51.png"}},
{
          "id":"ce6d25eab4f6481e8c39ed2e330b7f69",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":348,
              "y":1166},
            "size":{
              "width":65,
              "height":65},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f9d44cfcb3944da8b6e7179d147f0da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":348,
                  "y":1166},
                "size":{
                  "width":65,
                  "height":65},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/info/u51.png"}},
{
          "id":"0a94e7eed36d4caf933e6133ba77d8f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":462,
              "y":1166},
            "size":{
              "width":65,
              "height":65},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"704c9530a51147a0b5852075fc0124fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":462,
                  "y":1166},
                "size":{
                  "width":65,
                  "height":65},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/info/u51.png"}},
{
          "id":"a35021159bfc4993a4cbf68beab2a8be",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":424,
              "y":1164},
            "size":{
              "width":27,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae8c612956ef415ab88fb93b73cb858e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":424,
                  "y":1164},
                "size":{
                  "width":27,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5b15864a27145c9876c3b8a1f6e493d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":540,
              "y":1166},
            "size":{
              "width":65,
              "height":65},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c67b3c54dfa4107b70872bde8cf38cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":540,
                  "y":1166},
                "size":{
                  "width":65,
                  "height":65},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/info/u51.png"}},
{
          "id":"26abf98ba29f4a77aee1dcb34302cf65",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":617,
              "y":1166},
            "size":{
              "width":65,
              "height":65},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"473490d4fd6445c6b0f06ebf2d1c74bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":617,
                  "y":1166},
                "size":{
                  "width":65,
                  "height":65},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/info/u51.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "2800ae790f8d4c6aaf08229c98b4e018":{
      "scriptId":"u0"},
    "e77aa4dc214f495a8a785a54f394b35e":{
      "scriptId":"u1"},
    "21e25eefa5234bd38210f8e52fd7d3f8":{
      "scriptId":"u2"},
    "a6b4b1e9705047ed874246f481519940":{
      "scriptId":"u3"},
    "4a09147410e94165a74cfd01fb45a351":{
      "scriptId":"u4"},
    "2d4cb3c7335b4c93b2880b96a21f7bf6":{
      "scriptId":"u5"},
    "54c124ef9b07494f829698ac5e9dcf0a":{
      "scriptId":"u6"},
    "609acb17e52d41d8a4732ac73d263cc8":{
      "scriptId":"u7"},
    "e7d83afa95ea431faac663823ccdf293":{
      "scriptId":"u8"},
    "6355b796ff414c48b9d656d2deb6ea17":{
      "scriptId":"u9"},
    "843806aa6afb4c85b222e20e50fe9382":{
      "scriptId":"u10"},
    "a6b3c4aae5b1480ba948438d6b5c3be6":{
      "scriptId":"u11"},
    "8aaadf6e1cc0440ba7ce1fbb92440066":{
      "scriptId":"u12"},
    "961754c198e74016b1dbcec37ebfe2f5":{
      "scriptId":"u13"},
    "f99b20a7417e4177816cbe819b82fc1a":{
      "scriptId":"u14"},
    "02536c185b434aa6a2a519a8b1505f0d":{
      "scriptId":"u15"},
    "d430b97b9f7b45cebc258ad8cdcad9d1":{
      "scriptId":"u16"},
    "38133d3a3b3549b09ed965a4f70234fd":{
      "scriptId":"u17"},
    "d4df8c9d1fe449fb994206f63195a7e0":{
      "scriptId":"u18"},
    "8495fe3898f2455fa14c1d15dd54256d":{
      "scriptId":"u19"},
    "33b09b0235eb46128c9c6b6972c8884b":{
      "scriptId":"u20"},
    "cee476c7832d4d729c8ba67fff6834ab":{
      "scriptId":"u21"},
    "4c834e8cf8514caf890717d5e87a1beb":{
      "scriptId":"u22"},
    "e45424b9da5943769d39df59ce0be00b":{
      "scriptId":"u23"},
    "1254027a39394f3f802e2f074ad57b85":{
      "scriptId":"u24"},
    "83635a92a4af46309ac2fa6bff4cab27":{
      "scriptId":"u25"},
    "1d3f124a01064d0980c37116ce693b6b":{
      "scriptId":"u26"},
    "a70a57892c9c4273a17fc7bac5129478":{
      "scriptId":"u27"},
    "2de5de5a2a154c7798fb8a7c212d3113":{
      "scriptId":"u28"},
    "2dd2d6daa2974d90a97529e66f67e7bb":{
      "scriptId":"u29"},
    "2e4cf25c65e74047bdf6749b8b9fed58":{
      "scriptId":"u30"},
    "7a40c26a023f40b2af7bc12efe5315ce":{
      "scriptId":"u31"},
    "5f70bf0e49e4416f9d6bae2bdf1572e7":{
      "scriptId":"u32"},
    "7cff82db6d884108971f4dffccae7580":{
      "scriptId":"u33"},
    "d383a3fb6dab4d60a9e61ac7618e7dba":{
      "scriptId":"u34"},
    "ae3aa949006f43a992b2df12bb21ccff":{
      "scriptId":"u35"},
    "e40beca4f3f84acd8fa54da98710119e":{
      "scriptId":"u36"},
    "116b003c831b4394ac24ecb3a3cbc0ad":{
      "scriptId":"u37"},
    "8f5ae84f956d4e75ae5d7bb5862f260c":{
      "scriptId":"u38"},
    "1b428aaf0c5b4efbb51e647af28ef6b3":{
      "scriptId":"u39"},
    "b086f54f1adc4acebb77e15cf2313175":{
      "scriptId":"u40"},
    "71db1d73667747bbae62f4bdfea6e9d7":{
      "scriptId":"u41"},
    "caf6da5c6411499490caaa91605d7f6d":{
      "scriptId":"u42"},
    "cc2d806bda724cd59c7dd24ccb9a73a6":{
      "scriptId":"u43"},
    "be993b61ec714b17b13cd862ea5a4538":{
      "scriptId":"u44"},
    "cb5a97e2932046969afa95f595645fd4":{
      "scriptId":"u45"},
    "b7e05ab90bc74c92ac26bc3624f00c54":{
      "scriptId":"u46"},
    "f9535f315cc64b54b81ec30146119509":{
      "scriptId":"u47"},
    "56690b01a67d41738f205a65e293d010":{
      "scriptId":"u48"},
    "b86ca3e89b2947949c2e1446af0063f0":{
      "scriptId":"u49"},
    "a44d8886f4814c9ba6c94c75f1271898":{
      "scriptId":"u50"},
    "0e10e3ff3dda462ea2020d7a9cf2a8bf":{
      "scriptId":"u51"},
    "a776901afaf2460dbc6ce6377971b38c":{
      "scriptId":"u52"},
    "f5321649a85d47e6a2e3e4885f976c7f":{
      "scriptId":"u53"},
    "891ddb76fff943ea996fbe03a23b7ca3":{
      "scriptId":"u54"},
    "0e963772e3e34c8c91c4e062ca4b71fa":{
      "scriptId":"u55"},
    "2571f5ec6198473d990349ac92337eda":{
      "scriptId":"u56"},
    "ce6d25eab4f6481e8c39ed2e330b7f69":{
      "scriptId":"u57"},
    "7f9d44cfcb3944da8b6e7179d147f0da":{
      "scriptId":"u58"},
    "0a94e7eed36d4caf933e6133ba77d8f7":{
      "scriptId":"u59"},
    "704c9530a51147a0b5852075fc0124fc":{
      "scriptId":"u60"},
    "a35021159bfc4993a4cbf68beab2a8be":{
      "scriptId":"u61"},
    "ae8c612956ef415ab88fb93b73cb858e":{
      "scriptId":"u62"},
    "e5b15864a27145c9876c3b8a1f6e493d":{
      "scriptId":"u63"},
    "2c67b3c54dfa4107b70872bde8cf38cc":{
      "scriptId":"u64"},
    "26abf98ba29f4a77aee1dcb34302cf65":{
      "scriptId":"u65"},
    "473490d4fd6445c6b0f06ebf2d1c74bf":{
      "scriptId":"u66"}}});