$axure.loadCurrentPage({
  "url":"products-buy.html",
  "generationDate":new Date(1444814342241.86),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7fe5fd6019414798a5766dadbf21d523",
    "type":"Axure:Page",
    "name":"products-buy",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5eadb509579643c1a080ac1e9d712a75",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":200},
            "size":{
              "width":720,
              "height":980},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee8b1cca358c4499ac227053fd5f38f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":200},
                "size":{
                  "width":720,
                  "height":980},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/products-buy/u0.png"}},
{
          "id":"fd2d5f8f939a433cad9748c24a59b132",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":230},
            "size":{
              "width":720,
              "height":446},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e647b6ed2c84d9b93ef686fbbfbb0e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":230},
                "size":{
                  "width":720,
                  "height":446},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/products-buy/u2.png"}},
{
          "id":"1b75da9cf96b457291471c669dc6b3f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c8afb71e45d4a058725f79352a18005",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"9c262590164c41848aae284465b81336",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"ddbfd6630faf4da9a06103e37552676d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":14},
            "size":{
              "width":69,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a6e69096532477fb0dc2f5cb7d9596f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":14},
                "size":{
                  "width":69,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 buy",
                      "target":{
                        "targetType":"page",
                        "url":"buy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"f9de6e0c63ae43eba9837e58e065129d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "location":{
              "x":316,
              "y":22},
            "size":{
              "width":79,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7fb18e98d1b4f4cb7446bb50b401372",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "location":{
                  "x":316,
                  "y":22},
                "size":{
                  "width":79,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2c556bae1fe4bbfaf1017a67e59a610",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":197},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"fc0bf33fbae945ebabac805c575cbb1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":60,
              "y":127},
            "size":{
              "width":600,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e92e8141ca842f3887197b53188325c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":60,
                  "y":127},
                "size":{
                  "width":600,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad6b476a06504c96bdee071708018a49",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":194},
            "size":{
              "width":230,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/products-buy/u14_line.png"}},
{
          "id":"ea35f104d0b7491482947964498284e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":19,
              "y":347},
            "size":{
              "width":159,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd9264815ead497687f3c58db8e6f4c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":19,
                  "y":347},
                "size":{
                  "width":159,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f711e21a61f844e783ea1240044c44a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":19,
              "y":410},
            "size":{
              "width":223,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f670f38999247cf95882fb31b1694d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":19,
                  "y":410},
                "size":{
                  "width":223,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13c1aab60a0b44a59ebe570e97fcea8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":598,
              "y":347},
            "size":{
              "width":105,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25ff3e70b8b041b182a24ac3e38ea6be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":598,
                  "y":347},
                "size":{
                  "width":105,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77c6448a8d4246fb989ac56fbfd77c9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":465,
              "y":406},
            "size":{
              "width":113,
              "height":45},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "cornerRadiusTopLeft":"50"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"caa2a38ca72041bc8e54ad4a1e962948",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":465,
                  "y":406},
                "size":{
                  "width":113,
                  "height":45},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "cornerRadiusTopLeft":"50"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Products-Buy-content",
                      "target":{
                        "targetType":"page",
                        "url":"products-buy-content.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/products-buy/u21.png"}},
{
          "id":"9497581cf2554596b183824ca347284a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "paddingTop":"0",
            "location":{
              "x":590,
              "y":406},
            "size":{
              "width":113,
              "height":45},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "cornerRadiusTopLeft":"50"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0353b3125ad34acdb47f163eb2597997",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "paddingTop":"0",
                "location":{
                  "x":590,
                  "y":406},
                "size":{
                  "width":113,
                  "height":45},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "cornerRadiusTopLeft":"50"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Products-Buy-enquiry",
                      "target":{
                        "targetType":"page",
                        "url":"products-buy-enquiry.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/products-buy/u23.png"}},
{
          "id":"36e298b69bf8445795fad42ee912fae1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":19,
              "y":532},
            "size":{
              "width":159,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58a0d0eed86948deb4971d17e8b456bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":19,
                  "y":532},
                "size":{
                  "width":159,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"41e55d331d3f4eeeaf9a4247b0fa9483",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":19,
              "y":595},
            "size":{
              "width":223,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1175bf3f3a2f40ce8adce074fa354bda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":19,
                  "y":595},
                "size":{
                  "width":223,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c37540bfdea348338a4fafa0649177af",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":599,
              "y":532},
            "size":{
              "width":105,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6bcf39eb9244b11801ee6a2f6851231",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":599,
                  "y":532},
                "size":{
                  "width":105,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96b5c517f95e4ee78623cccf2e7c5fe6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":465,
              "y":591},
            "size":{
              "width":113,
              "height":45},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "cornerRadiusTopLeft":"50"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e451512655f4cfe8abec2ff506dc2d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":465,
                  "y":591},
                "size":{
                  "width":113,
                  "height":45},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "cornerRadiusTopLeft":"50"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Products-Buy-content",
                      "target":{
                        "targetType":"page",
                        "url":"products-buy-content.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/products-buy/u21.png"}},
{
          "id":"322b5e3c557d4cfaad2b1f51a6edc135",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "paddingTop":"0",
            "location":{
              "x":590,
              "y":591},
            "size":{
              "width":113,
              "height":45},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "cornerRadiusTopLeft":"50"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80d4db065b8a440498201ae4b9b1a92a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "paddingTop":"0",
                "location":{
                  "x":590,
                  "y":591},
                "size":{
                  "width":113,
                  "height":45},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "cornerRadiusTopLeft":"50"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Products-Buy-enquiry",
                      "target":{
                        "targetType":"page",
                        "url":"products-buy-enquiry.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/products-buy/u23.png"}},
{
          "id":"fe78e84073a946719fb00bb9e9ed63bf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":483},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"efcbdbcd8b8044f2b87981827b95d722",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":670},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"338d9c8d809f4ae392ce50179dd6b446",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":66,
              "y":247},
            "size":{
              "width":571,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1958d08c9a244ea596b94a5f9152d6a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":66,
                  "y":247},
                "size":{
                  "width":571,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46dbe5327846470c9e24053778ace1f6",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":223,
              "y":250},
            "size":{
              "width":10,
              "height":44},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/products-buy/u39_line.png"}},
{
          "id":"85819aa3a4f64b139ada29898aa68897",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":226},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"4b8c71857062463b9d6ec9f3667dd1f1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":309},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"0d2900575d1a42aabc40a195668f03e2",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":478,
              "y":250},
            "size":{
              "width":10,
              "height":44},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/products-buy/u39_line.png"}},
{
          "id":"c70c4cbb432c4f90a25e204f4d2e1a8e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":394,
              "y":268},
            "size":{
              "width":12,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b11af14ea234a938745f9c96cfdf226",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":394,
                  "y":268},
                "size":{
                  "width":12,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/products-buy/u43.png"}},
{
          "id":"f5aadf72caa74dbba35b75954f066f15",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":642,
              "y":268},
            "size":{
              "width":12,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"289293a5493d4d71ac88680c8eb543cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":642,
                  "y":268},
                "size":{
                  "width":12,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/products-buy/u43.png"}},
{
          "id":"a21e3ebb3c30411ba2f1db2c89348a73",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":641,
              "y":30},
            "size":{
              "width":57,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46fa7e9debd14407bcc71d0948a65175",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":641,
                  "y":30},
                "size":{
                  "width":57,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d74bc2fb9ac04c9dbea94f8cf70a3def",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":583,
              "y":24},
            "size":{
              "width":48,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00eb679c905443aaaff489c82bb6b665",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":583,
                  "y":24},
                "size":{
                  "width":48,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 search",
                      "target":{
                        "targetType":"page",
                        "url":"search.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/info/u49.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "5eadb509579643c1a080ac1e9d712a75":{
      "scriptId":"u0"},
    "ee8b1cca358c4499ac227053fd5f38f6":{
      "scriptId":"u1"},
    "fd2d5f8f939a433cad9748c24a59b132":{
      "scriptId":"u2"},
    "0e647b6ed2c84d9b93ef686fbbfbb0e3":{
      "scriptId":"u3"},
    "1b75da9cf96b457291471c669dc6b3f1":{
      "scriptId":"u4"},
    "6c8afb71e45d4a058725f79352a18005":{
      "scriptId":"u5"},
    "9c262590164c41848aae284465b81336":{
      "scriptId":"u6"},
    "ddbfd6630faf4da9a06103e37552676d":{
      "scriptId":"u7"},
    "6a6e69096532477fb0dc2f5cb7d9596f":{
      "scriptId":"u8"},
    "f9de6e0c63ae43eba9837e58e065129d":{
      "scriptId":"u9"},
    "f7fb18e98d1b4f4cb7446bb50b401372":{
      "scriptId":"u10"},
    "c2c556bae1fe4bbfaf1017a67e59a610":{
      "scriptId":"u11"},
    "fc0bf33fbae945ebabac805c575cbb1a":{
      "scriptId":"u12"},
    "5e92e8141ca842f3887197b53188325c":{
      "scriptId":"u13"},
    "ad6b476a06504c96bdee071708018a49":{
      "scriptId":"u14"},
    "ea35f104d0b7491482947964498284e2":{
      "scriptId":"u15"},
    "fd9264815ead497687f3c58db8e6f4c2":{
      "scriptId":"u16"},
    "f711e21a61f844e783ea1240044c44a1":{
      "scriptId":"u17"},
    "4f670f38999247cf95882fb31b1694d4":{
      "scriptId":"u18"},
    "13c1aab60a0b44a59ebe570e97fcea8f":{
      "scriptId":"u19"},
    "25ff3e70b8b041b182a24ac3e38ea6be":{
      "scriptId":"u20"},
    "77c6448a8d4246fb989ac56fbfd77c9f":{
      "scriptId":"u21"},
    "caa2a38ca72041bc8e54ad4a1e962948":{
      "scriptId":"u22"},
    "9497581cf2554596b183824ca347284a":{
      "scriptId":"u23"},
    "0353b3125ad34acdb47f163eb2597997":{
      "scriptId":"u24"},
    "36e298b69bf8445795fad42ee912fae1":{
      "scriptId":"u25"},
    "58a0d0eed86948deb4971d17e8b456bf":{
      "scriptId":"u26"},
    "41e55d331d3f4eeeaf9a4247b0fa9483":{
      "scriptId":"u27"},
    "1175bf3f3a2f40ce8adce074fa354bda":{
      "scriptId":"u28"},
    "c37540bfdea348338a4fafa0649177af":{
      "scriptId":"u29"},
    "a6bcf39eb9244b11801ee6a2f6851231":{
      "scriptId":"u30"},
    "96b5c517f95e4ee78623cccf2e7c5fe6":{
      "scriptId":"u31"},
    "0e451512655f4cfe8abec2ff506dc2d0":{
      "scriptId":"u32"},
    "322b5e3c557d4cfaad2b1f51a6edc135":{
      "scriptId":"u33"},
    "80d4db065b8a440498201ae4b9b1a92a":{
      "scriptId":"u34"},
    "fe78e84073a946719fb00bb9e9ed63bf":{
      "scriptId":"u35"},
    "efcbdbcd8b8044f2b87981827b95d722":{
      "scriptId":"u36"},
    "338d9c8d809f4ae392ce50179dd6b446":{
      "scriptId":"u37"},
    "1958d08c9a244ea596b94a5f9152d6a5":{
      "scriptId":"u38"},
    "46dbe5327846470c9e24053778ace1f6":{
      "scriptId":"u39"},
    "85819aa3a4f64b139ada29898aa68897":{
      "scriptId":"u40"},
    "4b8c71857062463b9d6ec9f3667dd1f1":{
      "scriptId":"u41"},
    "0d2900575d1a42aabc40a195668f03e2":{
      "scriptId":"u42"},
    "c70c4cbb432c4f90a25e204f4d2e1a8e":{
      "scriptId":"u43"},
    "8b11af14ea234a938745f9c96cfdf226":{
      "scriptId":"u44"},
    "f5aadf72caa74dbba35b75954f066f15":{
      "scriptId":"u45"},
    "289293a5493d4d71ac88680c8eb543cd":{
      "scriptId":"u46"},
    "a21e3ebb3c30411ba2f1db2c89348a73":{
      "scriptId":"u47"},
    "46fa7e9debd14407bcc71d0948a65175":{
      "scriptId":"u48"},
    "d74bc2fb9ac04c9dbea94f8cf70a3def":{
      "scriptId":"u49"},
    "00eb679c905443aaaff489c82bb6b665":{
      "scriptId":"u50"}}});