$axure.loadCurrentPage({
  "url":"products-sale-content.html",
  "generationDate":new Date(1444814343055.91),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"65ef8de628944f43adaa23a2d9c8bc44",
    "type":"Axure:Page",
    "name":"Products-Sale-content",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c35734ed2fa949499fd0c7e5ba6f2d92",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":96},
            "size":{
              "width":720,
              "height":1744},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72d4668e4c7d43178d42533609088d48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":96},
                "size":{
                  "width":720,
                  "height":1744},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/products-buy-content/u0.png"}},
{
          "id":"423edfa6d6134fbcbc2862dcb56ff33f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":126},
            "size":{
              "width":720,
              "height":569},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f07bd74352e4a629d4ba2f0794cfd98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":126},
                "size":{
                  "width":720,
                  "height":569},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/products-sale-content/u2.png"}},
{
          "id":"cb155fb31fee42f3960e678d87a74ad8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bdafde644fa4d4c90702917c394fbc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"b08e75292c864d518177bcfa8999f13d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"e3cf753d7ee744e88ff97529796cde4f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":14},
            "size":{
              "width":69,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fc5b9064e004f0bbf69be9f5facc5e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":14},
                "size":{
                  "width":69,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 products-sale",
                      "target":{
                        "targetType":"page",
                        "url":"products-sale.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"03327eac9701449bbac2e95c58c64861",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "location":{
              "x":280,
              "y":22},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdbb50a0bff14ff4956ff426f5c6db9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "location":{
                  "x":280,
                  "y":22},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3735442441fb422d9dc3c7ebbddf06f3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":122},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"8016be52196842bab70da596983badab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":723},
            "size":{
              "width":720,
              "height":1047},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf6c327ae48d42fc874264b92d92d2ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":723},
                "size":{
                  "width":720,
                  "height":1047},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/products-sale-content/u12.png"}},
{
          "id":"cff8913bba6b486bbf967cd7a73f86b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"40px",
            "location":{
              "x":19,
              "y":750},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58edf936d3d04060b340d3dc255677a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"40px",
                "location":{
                  "x":19,
                  "y":750},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46d870900cca4dba94a9ccf256b05085",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "lineSpacing":"60px",
            "location":{
              "x":19,
              "y":839},
            "size":{
              "width":462,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d86f9992ce544d4a45ef0fbd5bfae2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"60px",
                "location":{
                  "x":19,
                  "y":839},
                "size":{
                  "width":462,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4300421cd5cf437f87e5301be7a7f1fb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1767},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"1b341db64d6b41bdab0fe440f24b71f1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":817},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"430edd9914304819b6e31c7a7836569b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":690},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"7b5b01df95d844199cb7ac1f1e756f0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":31,
              "y":546},
            "size":{
              "width":660,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8a2ac959e284773b8d454e71c1ce4b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":31,
                  "y":546},
                "size":{
                  "width":660,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDBDBDB},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u17.png"}},
{
          "id":"1b64cbcccb3e479bb14ed31864da8824",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":322,
              "y":568},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ca49d3455e2466695128ab7a4399b28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":322,
                  "y":568},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d51bafe297141d6981768f7f7ba79b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "lineSpacing":"72px",
            "location":{
              "x":38,
              "y":146},
            "size":{
              "width":421,
              "height":359}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23bf7b3fe5db4635bb9b14025a2842a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "lineSpacing":"72px",
                "location":{
                  "x":38,
                  "y":146},
                "size":{
                  "width":421,
                  "height":359}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75f47f833ab24c2089feefe6cfe1841d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":717},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"eb43891618d3423596b418d34c22a068",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":581,
              "y":30},
            "size":{
              "width":113,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26bf6fe345bc4e5ca1d2a080691e66d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":581,
                  "y":30},
                "size":{
                  "width":113,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Products-Buy-help",
                      "target":{
                        "targetType":"page",
                        "url":"products-buy-help.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0bb94b954b92420e9cca1173cfce5b91",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":562},
            "size":{
              "width":64,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c38a6441f59448e7b6d41d69ba6ecfa9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":562},
                "size":{
                  "width":64,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/products-sale-content/u30.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c35734ed2fa949499fd0c7e5ba6f2d92":{
      "scriptId":"u0"},
    "72d4668e4c7d43178d42533609088d48":{
      "scriptId":"u1"},
    "423edfa6d6134fbcbc2862dcb56ff33f":{
      "scriptId":"u2"},
    "7f07bd74352e4a629d4ba2f0794cfd98":{
      "scriptId":"u3"},
    "cb155fb31fee42f3960e678d87a74ad8":{
      "scriptId":"u4"},
    "3bdafde644fa4d4c90702917c394fbc1":{
      "scriptId":"u5"},
    "b08e75292c864d518177bcfa8999f13d":{
      "scriptId":"u6"},
    "e3cf753d7ee744e88ff97529796cde4f":{
      "scriptId":"u7"},
    "1fc5b9064e004f0bbf69be9f5facc5e8":{
      "scriptId":"u8"},
    "03327eac9701449bbac2e95c58c64861":{
      "scriptId":"u9"},
    "cdbb50a0bff14ff4956ff426f5c6db9d":{
      "scriptId":"u10"},
    "3735442441fb422d9dc3c7ebbddf06f3":{
      "scriptId":"u11"},
    "8016be52196842bab70da596983badab":{
      "scriptId":"u12"},
    "cf6c327ae48d42fc874264b92d92d2ff":{
      "scriptId":"u13"},
    "cff8913bba6b486bbf967cd7a73f86b4":{
      "scriptId":"u14"},
    "58edf936d3d04060b340d3dc255677a9":{
      "scriptId":"u15"},
    "46d870900cca4dba94a9ccf256b05085":{
      "scriptId":"u16"},
    "5d86f9992ce544d4a45ef0fbd5bfae2e":{
      "scriptId":"u17"},
    "4300421cd5cf437f87e5301be7a7f1fb":{
      "scriptId":"u18"},
    "1b341db64d6b41bdab0fe440f24b71f1":{
      "scriptId":"u19"},
    "430edd9914304819b6e31c7a7836569b":{
      "scriptId":"u20"},
    "7b5b01df95d844199cb7ac1f1e756f0a":{
      "scriptId":"u21"},
    "b8a2ac959e284773b8d454e71c1ce4b8":{
      "scriptId":"u22"},
    "1b64cbcccb3e479bb14ed31864da8824":{
      "scriptId":"u23"},
    "0ca49d3455e2466695128ab7a4399b28":{
      "scriptId":"u24"},
    "4d51bafe297141d6981768f7f7ba79b3":{
      "scriptId":"u25"},
    "23bf7b3fe5db4635bb9b14025a2842a7":{
      "scriptId":"u26"},
    "75f47f833ab24c2089feefe6cfe1841d":{
      "scriptId":"u27"},
    "eb43891618d3423596b418d34c22a068":{
      "scriptId":"u28"},
    "26bf6fe345bc4e5ca1d2a080691e66d6":{
      "scriptId":"u29"},
    "0bb94b954b92420e9cca1173cfce5b91":{
      "scriptId":"u30"},
    "c38a6441f59448e7b6d41d69ba6ecfa9":{
      "scriptId":"u31"}}});