$axure.loadCurrentPage({
  "url":"search.html",
  "generationDate":new Date(1444814341583.83),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c6c5d92aee0d42b6b286fd590de7acc7",
    "type":"Axure:Page",
    "name":"search",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2e214c70db804603af9ca23451294ee6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":1088},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ade17f206c784a3299026080eb44df11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":92},
                "size":{
                  "width":720,
                  "height":1088},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search/u0.png"}},
{
          "id":"f97cd326fbd24b7b92537ad13821302a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b0ce8189774449593594df11416115e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"f06caea087bd42ebba2601ce2592ed8a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"ff6154bb16e441e88eecf2826c5be658",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":14},
            "size":{
              "width":69,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93b3ff2eb6eb4041ba2d333bf68d441e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":14},
                "size":{
                  "width":69,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"022964cb6f514a808f473e99838bd33e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "location":{
              "x":279.5,
              "y":22},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"312953e69be749e7a168ad7491980e91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "location":{
                  "x":279.5,
                  "y":22},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"177f692c5d23464a8b1de650d473b390",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":131},
            "size":{
              "width":720,
              "height":426},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e286bfa50534817932405e9b66d254e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":131},
                "size":{
                  "width":720,
                  "height":426},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search/u9.png"}},
{
          "id":"2c0b536fb70143fd87b5b478f2778a01",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "lineSpacing":"96px",
            "location":{
              "x":27,
              "y":131},
            "size":{
              "width":367,
              "height":384}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fa66fd855794f48912ebe0592936227",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "lineSpacing":"96px",
                "location":{
                  "x":27,
                  "y":131},
                "size":{
                  "width":367,
                  "height":384}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65bf382f4ae24ee8a7785e193ff481a6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":125},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"1ef362a3308842a48010359c62a7d6c8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":221},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"d43c396c3e934217b72733c60e66a666",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":317},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"0259fbca5ce9486bb129b6c813bb3312",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":552},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"0b5440f771a4477f82e526a71f255baf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":400},
            "size":{
              "width":445,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9900}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search/u17_line.png"}},
{
          "id":"08f18eb7f17b4d09ada1a9894a7d65c4",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":659,
              "y":391},
            "size":{
              "width":10,
              "height":15},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9900}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search/u18_line.png"}},
{
          "id":"f5f4525d7f5b45399f5f60dda5e41b9b",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":216,
              "y":391},
            "size":{
              "width":10,
              "height":15},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9900}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search/u18_line.png"}},
{
          "id":"6239031fe7a0424e9239358ff94d5d83",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":499},
            "size":{
              "width":445,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9900}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search/u17_line.png"}},
{
          "id":"188b1d1e12b24cbb8af55613dbaea3a0",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":659,
              "y":490},
            "size":{
              "width":10,
              "height":15},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9900}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search/u18_line.png"}},
{
          "id":"35f1a0ef79f74fcfaf4bc4da1f564fd1",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":216,
              "y":490},
            "size":{
              "width":10,
              "height":15},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9900}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search/u18_line.png"}},
{
          "id":"f29752296db344979da7d8ce0c7acb47",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'黑体 Bold', '黑体'",
            "fontSize":"32px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":653,
              "y":162},
            "size":{
              "width":18,
              "height":37},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7117e30f7104bf28e2194432a298b32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'黑体 Bold', '黑体'",
                "fontSize":"32px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":653,
                  "y":162},
                "size":{
                  "width":18,
                  "height":37},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed2b4f609ece4c17b829024a408b52a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'黑体 Bold', '黑体'",
            "fontSize":"32px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":653,
              "y":253},
            "size":{
              "width":18,
              "height":37},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29c5e16e90b04feaa189b98e689d18d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'黑体 Bold', '黑体'",
                "fontSize":"32px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":653,
                  "y":253},
                "size":{
                  "width":18,
                  "height":37},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa983a1ff3d84721b17c3e1587938041",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":30,
              "y":604},
            "size":{
              "width":660,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1eb2fc866c9e45158763f34c4b62adb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":30,
                  "y":604},
                "size":{
                  "width":660,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDBDBDB},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u17.png"}},
{
          "id":"8995a89fad1447e98b441edd6f86a9ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":320,
              "y":626},
            "size":{
              "width":81,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a8e681a957648e588b74639b8967dc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":626},
                "size":{
                  "width":81,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5b249ff4b91475cb362f097e0bfcc65",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":41,
              "y":865},
            "size":{
              "width":625,
              "height":125}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd7c63040e4543f4ad9a33acdfec06cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":41,
                  "y":865},
                "size":{
                  "width":625,
                  "height":125}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "2e214c70db804603af9ca23451294ee6":{
      "scriptId":"u0"},
    "ade17f206c784a3299026080eb44df11":{
      "scriptId":"u1"},
    "f97cd326fbd24b7b92537ad13821302a":{
      "scriptId":"u2"},
    "4b0ce8189774449593594df11416115e":{
      "scriptId":"u3"},
    "f06caea087bd42ebba2601ce2592ed8a":{
      "scriptId":"u4"},
    "ff6154bb16e441e88eecf2826c5be658":{
      "scriptId":"u5"},
    "93b3ff2eb6eb4041ba2d333bf68d441e":{
      "scriptId":"u6"},
    "022964cb6f514a808f473e99838bd33e":{
      "scriptId":"u7"},
    "312953e69be749e7a168ad7491980e91":{
      "scriptId":"u8"},
    "177f692c5d23464a8b1de650d473b390":{
      "scriptId":"u9"},
    "3e286bfa50534817932405e9b66d254e":{
      "scriptId":"u10"},
    "2c0b536fb70143fd87b5b478f2778a01":{
      "scriptId":"u11"},
    "6fa66fd855794f48912ebe0592936227":{
      "scriptId":"u12"},
    "65bf382f4ae24ee8a7785e193ff481a6":{
      "scriptId":"u13"},
    "1ef362a3308842a48010359c62a7d6c8":{
      "scriptId":"u14"},
    "d43c396c3e934217b72733c60e66a666":{
      "scriptId":"u15"},
    "0259fbca5ce9486bb129b6c813bb3312":{
      "scriptId":"u16"},
    "0b5440f771a4477f82e526a71f255baf":{
      "scriptId":"u17"},
    "08f18eb7f17b4d09ada1a9894a7d65c4":{
      "scriptId":"u18"},
    "f5f4525d7f5b45399f5f60dda5e41b9b":{
      "scriptId":"u19"},
    "6239031fe7a0424e9239358ff94d5d83":{
      "scriptId":"u20"},
    "188b1d1e12b24cbb8af55613dbaea3a0":{
      "scriptId":"u21"},
    "35f1a0ef79f74fcfaf4bc4da1f564fd1":{
      "scriptId":"u22"},
    "f29752296db344979da7d8ce0c7acb47":{
      "scriptId":"u23"},
    "f7117e30f7104bf28e2194432a298b32":{
      "scriptId":"u24"},
    "ed2b4f609ece4c17b829024a408b52a6":{
      "scriptId":"u25"},
    "29c5e16e90b04feaa189b98e689d18d3":{
      "scriptId":"u26"},
    "aa983a1ff3d84721b17c3e1587938041":{
      "scriptId":"u27"},
    "1eb2fc866c9e45158763f34c4b62adb7":{
      "scriptId":"u28"},
    "8995a89fad1447e98b441edd6f86a9ed":{
      "scriptId":"u29"},
    "7a8e681a957648e588b74639b8967dc2":{
      "scriptId":"u30"},
    "e5b249ff4b91475cb362f097e0bfcc65":{
      "scriptId":"u31"},
    "bd7c63040e4543f4ad9a33acdfec06cb":{
      "scriptId":"u32"}}});