$axure.loadCurrentPage({
  "url":"mybuy-content.html",
  "generationDate":new Date(1444814345195.03),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cc21d6377c5142b19985f40fb89440e5",
    "type":"Axure:Page",
    "name":"MyBuy-content",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0bc7b07df303477aaed85e98cd84e2f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":14},
            "size":{
              "width":720,
              "height":1618},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ad269bc8f994fe59e4a6202ce744a7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":14},
                "size":{
                  "width":720,
                  "height":1618},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mybuy-content/u0.png"}},
{
          "id":"6878de234a54480aa9ddc99d478e0c67",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2da515a16e647538451f2d9cd77abf3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"a182033f44724c028456986f12d38f4c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"078fa364e39247af8b922c431547b212",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":14},
            "size":{
              "width":69,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"125d6b15844d4e048e58cde606968d45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":14},
                "size":{
                  "width":69,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 MyBuy-plan",
                      "target":{
                        "targetType":"page",
                        "url":"mybuy-plan.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"affad9dc631d4dc6b3f4b1e6a6336e75",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "location":{
              "x":280,
              "y":22},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f39fd8a725ff4e8f8b334fc2040e8d30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "location":{
                  "x":280,
                  "y":22},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"871b767c833b4f339d3b9645aa8d0e57",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":131},
            "size":{
              "width":720,
              "height":414},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4791b628fdc544ec85f19c257b7395d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":131},
                "size":{
                  "width":720,
                  "height":414},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mybuy-content/u9.png"}},
{
          "id":"3307855c742248d88e150de79d1bad17",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "lineSpacing":"60px",
            "location":{
              "x":27,
              "y":153},
            "size":{
              "width":374,
              "height":360}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"055a44f55362472ab65acdb351bdd95c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "lineSpacing":"60px",
                "location":{
                  "x":27,
                  "y":153},
                "size":{
                  "width":374,
                  "height":360}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99ffaf3c1b0349c3bd125e2387ffa00b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":125},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"6216daad2ca84b57aa72cafb74887025",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":539},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"75ee4e5de38f447bab226ce117aeee7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":579},
            "size":{
              "width":720,
              "height":1007},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8eae6d088e1414286708625474e4f74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":579},
                "size":{
                  "width":720,
                  "height":1007},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-buy-content/u13.png"}},
{
          "id":"5cd3961772bc42dea0ee3283b1a2672d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1581},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"b2faeee59eec44cfa24b63837c819f24",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":573},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"ee3de4ee11dc4cbd95b66432e6af1eb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"40px",
            "location":{
              "x":27,
              "y":603},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b702b68f49147c5a6691399ff0addd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"40px",
                "location":{
                  "x":27,
                  "y":603},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ac95d1bb6534ebebaab976e4e2850b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "lineSpacing":"60px",
            "location":{
              "x":27,
              "y":692},
            "size":{
              "width":462,
              "height":840}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5626703190c4e579fae625f32d163ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"60px",
                "location":{
                  "x":27,
                  "y":692},
                "size":{
                  "width":462,
                  "height":840}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8aca9ae4710b42949cea9832f1adb3e7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":664},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "0bc7b07df303477aaed85e98cd84e2f4":{
      "scriptId":"u0"},
    "0ad269bc8f994fe59e4a6202ce744a7e":{
      "scriptId":"u1"},
    "6878de234a54480aa9ddc99d478e0c67":{
      "scriptId":"u2"},
    "c2da515a16e647538451f2d9cd77abf3":{
      "scriptId":"u3"},
    "a182033f44724c028456986f12d38f4c":{
      "scriptId":"u4"},
    "078fa364e39247af8b922c431547b212":{
      "scriptId":"u5"},
    "125d6b15844d4e048e58cde606968d45":{
      "scriptId":"u6"},
    "affad9dc631d4dc6b3f4b1e6a6336e75":{
      "scriptId":"u7"},
    "f39fd8a725ff4e8f8b334fc2040e8d30":{
      "scriptId":"u8"},
    "871b767c833b4f339d3b9645aa8d0e57":{
      "scriptId":"u9"},
    "4791b628fdc544ec85f19c257b7395d9":{
      "scriptId":"u10"},
    "3307855c742248d88e150de79d1bad17":{
      "scriptId":"u11"},
    "055a44f55362472ab65acdb351bdd95c":{
      "scriptId":"u12"},
    "99ffaf3c1b0349c3bd125e2387ffa00b":{
      "scriptId":"u13"},
    "6216daad2ca84b57aa72cafb74887025":{
      "scriptId":"u14"},
    "75ee4e5de38f447bab226ce117aeee7d":{
      "scriptId":"u15"},
    "f8eae6d088e1414286708625474e4f74":{
      "scriptId":"u16"},
    "5cd3961772bc42dea0ee3283b1a2672d":{
      "scriptId":"u17"},
    "b2faeee59eec44cfa24b63837c819f24":{
      "scriptId":"u18"},
    "ee3de4ee11dc4cbd95b66432e6af1eb2":{
      "scriptId":"u19"},
    "7b702b68f49147c5a6691399ff0addd5":{
      "scriptId":"u20"},
    "7ac95d1bb6534ebebaab976e4e2850b4":{
      "scriptId":"u21"},
    "d5626703190c4e579fae625f32d163ff":{
      "scriptId":"u22"},
    "8aca9ae4710b42949cea9832f1adb3e7":{
      "scriptId":"u23"}}});