$axure.loadCurrentPage({
  "url":"products-sale.html",
  "generationDate":new Date(1444814342882.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"518bba65b5c047329b58ba2b64c0aac5",
    "type":"Axure:Page",
    "name":"products-sale",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"be4010be114943e1a96376a23b413175",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":200},
            "size":{
              "width":720,
              "height":980},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57b9cada91464c869532bfd9cd2ef89d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":200},
                "size":{
                  "width":720,
                  "height":980},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/products-buy/u0.png"}},
{
          "id":"455ebcab07fc4a5184be4678452b25a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":230},
            "size":{
              "width":720,
              "height":446},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ec2b2639f104f39beb22c9d3f56e992",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":230},
                "size":{
                  "width":720,
                  "height":446},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/products-buy/u2.png"}},
{
          "id":"58b979a1413d4b21bcd1cbe99ccc41e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08bd012d88ff4682a3d9b30b3acb1546",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"aaa6224285c640a899e82fdce83cd38a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"e9ea15676f74427989dfe3383a7abac4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":14},
            "size":{
              "width":69,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35dbfa865ef54d60a3e4a9643a6f7063",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":14},
                "size":{
                  "width":69,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 sale",
                      "target":{
                        "targetType":"page",
                        "url":"sale.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"75cd95df30c84a29aa8571d9ae76ecdf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "location":{
              "x":316,
              "y":22},
            "size":{
              "width":79,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"646b590608cb4ec7ad8581fbbd91fdec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "location":{
                  "x":316,
                  "y":22},
                "size":{
                  "width":79,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0be0379379d2445dac07f7334b73c33e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":197},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"bdb0bd43a7e2437a93c26817b0920b49",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":60,
              "y":127},
            "size":{
              "width":600,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"567fbdd4625f4f18a8dad469d764a56c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":60,
                  "y":127},
                "size":{
                  "width":600,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"726a4659ab4949d1baac8fc186609478",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":194},
            "size":{
              "width":230,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/products-buy/u14_line.png"}},
{
          "id":"0d8f5713db5945af956575a15d7e03ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":19,
              "y":347},
            "size":{
              "width":159,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fad3cdc974b4601aaabb73413c66f91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":19,
                  "y":347},
                "size":{
                  "width":159,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d6d236584a24763bd47b6bfca279694",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":19,
              "y":410},
            "size":{
              "width":223,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf81a2c35e614c9c8bbc56d4effa7ba0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":19,
                  "y":410},
                "size":{
                  "width":223,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f10ba436dbd43ad985e012dca8e9c3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":596,
              "y":347},
            "size":{
              "width":105,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"867b1fb2db364ca5bc675d7088323660",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":596,
                  "y":347},
                "size":{
                  "width":105,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"793d8dadb8cd4475841bf4ddd87c2226",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":551,
              "y":406},
            "size":{
              "width":155,
              "height":45},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "cornerRadiusTopLeft":"50"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ee3d068b4e2486ab13e9143e707c768",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":551,
                  "y":406},
                "size":{
                  "width":155,
                  "height":45},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "cornerRadiusTopLeft":"50"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Products-Sale-content",
                      "target":{
                        "targetType":"page",
                        "url":"products-sale-content.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/products-sale/u21.png"}},
{
          "id":"74e8723911fd4c91b158a8b85313751d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":483},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"9f9d0836676b44288166f71d350a154d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":670},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"6c7025d9b2574e67b77bb0d7a1938397",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":19,
              "y":532},
            "size":{
              "width":159,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"350eca4105b141aa811f954779c313a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":19,
                  "y":532},
                "size":{
                  "width":159,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9874f4c020da4a2e9366151f4a06aeaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":19,
              "y":595},
            "size":{
              "width":223,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16fba84c84994393b1f647404e8d135e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":19,
                  "y":595},
                "size":{
                  "width":223,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cc85f6a3c154633a9abb20f77f5a473",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":596,
              "y":532},
            "size":{
              "width":105,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32cb0a53f2ea456d9760f5bb4d13ca4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":596,
                  "y":532},
                "size":{
                  "width":105,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d2822f4dc6c44b38d36c31ccf684ed8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":551,
              "y":591},
            "size":{
              "width":155,
              "height":45},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "cornerRadiusTopLeft":"50"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1d2416228944ba3a1ed05da18bcbc5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":551,
                  "y":591},
                "size":{
                  "width":155,
                  "height":45},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "cornerRadiusTopLeft":"50"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Products-Sale-content",
                      "target":{
                        "targetType":"page",
                        "url":"products-sale-content.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/products-sale/u21.png"}},
{
          "id":"b04fa6996a4c49c0911f249376a28d65",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":226},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"96d20bbbeb614c84b4ae283e7455f7c2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":309},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"bba9081f3db944a6a6589fbf500495d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":66,
              "y":247},
            "size":{
              "width":571,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"799536cee0114ce9b1508621f77cd835",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":66,
                  "y":247},
                "size":{
                  "width":571,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8fddefa2efe84ccca7e112051b4e338b",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":223,
              "y":250},
            "size":{
              "width":10,
              "height":44},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/products-buy/u39_line.png"}},
{
          "id":"5dc829d94d6942fda50b1d4f550afc9f",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":478,
              "y":250},
            "size":{
              "width":10,
              "height":44},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/products-buy/u39_line.png"}},
{
          "id":"d8e3d8398848476cbd5011ea6274bf8a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":394,
              "y":268},
            "size":{
              "width":12,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fea08073c56490cabd03a1f66a0dfde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":394,
                  "y":268},
                "size":{
                  "width":12,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/products-buy/u43.png"}},
{
          "id":"13357b1154574956a2c2cbda3531c86b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":642,
              "y":268},
            "size":{
              "width":12,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14061c6d7df74ea392fb26797d039720",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":642,
                  "y":268},
                "size":{
                  "width":12,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/products-buy/u43.png"}},
{
          "id":"273f6bdacddf4a2a9df02ee55ec62224",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":641,
              "y":30},
            "size":{
              "width":57,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f305995a251415dbe51a2b763ecce8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":641,
                  "y":30},
                "size":{
                  "width":57,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e79616aa82b04f8f9fbe4ece1880a88c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":583,
              "y":24},
            "size":{
              "width":48,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7598bfe425394bfba7fa0ceaac0554c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":583,
                  "y":24},
                "size":{
                  "width":48,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 search",
                      "target":{
                        "targetType":"page",
                        "url":"search.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/info/u49.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "be4010be114943e1a96376a23b413175":{
      "scriptId":"u0"},
    "57b9cada91464c869532bfd9cd2ef89d":{
      "scriptId":"u1"},
    "455ebcab07fc4a5184be4678452b25a2":{
      "scriptId":"u2"},
    "1ec2b2639f104f39beb22c9d3f56e992":{
      "scriptId":"u3"},
    "58b979a1413d4b21bcd1cbe99ccc41e2":{
      "scriptId":"u4"},
    "08bd012d88ff4682a3d9b30b3acb1546":{
      "scriptId":"u5"},
    "aaa6224285c640a899e82fdce83cd38a":{
      "scriptId":"u6"},
    "e9ea15676f74427989dfe3383a7abac4":{
      "scriptId":"u7"},
    "35dbfa865ef54d60a3e4a9643a6f7063":{
      "scriptId":"u8"},
    "75cd95df30c84a29aa8571d9ae76ecdf":{
      "scriptId":"u9"},
    "646b590608cb4ec7ad8581fbbd91fdec":{
      "scriptId":"u10"},
    "0be0379379d2445dac07f7334b73c33e":{
      "scriptId":"u11"},
    "bdb0bd43a7e2437a93c26817b0920b49":{
      "scriptId":"u12"},
    "567fbdd4625f4f18a8dad469d764a56c":{
      "scriptId":"u13"},
    "726a4659ab4949d1baac8fc186609478":{
      "scriptId":"u14"},
    "0d8f5713db5945af956575a15d7e03ad":{
      "scriptId":"u15"},
    "7fad3cdc974b4601aaabb73413c66f91":{
      "scriptId":"u16"},
    "0d6d236584a24763bd47b6bfca279694":{
      "scriptId":"u17"},
    "bf81a2c35e614c9c8bbc56d4effa7ba0":{
      "scriptId":"u18"},
    "9f10ba436dbd43ad985e012dca8e9c3d":{
      "scriptId":"u19"},
    "867b1fb2db364ca5bc675d7088323660":{
      "scriptId":"u20"},
    "793d8dadb8cd4475841bf4ddd87c2226":{
      "scriptId":"u21"},
    "8ee3d068b4e2486ab13e9143e707c768":{
      "scriptId":"u22"},
    "74e8723911fd4c91b158a8b85313751d":{
      "scriptId":"u23"},
    "9f9d0836676b44288166f71d350a154d":{
      "scriptId":"u24"},
    "6c7025d9b2574e67b77bb0d7a1938397":{
      "scriptId":"u25"},
    "350eca4105b141aa811f954779c313a0":{
      "scriptId":"u26"},
    "9874f4c020da4a2e9366151f4a06aeaa":{
      "scriptId":"u27"},
    "16fba84c84994393b1f647404e8d135e":{
      "scriptId":"u28"},
    "6cc85f6a3c154633a9abb20f77f5a473":{
      "scriptId":"u29"},
    "32cb0a53f2ea456d9760f5bb4d13ca4f":{
      "scriptId":"u30"},
    "2d2822f4dc6c44b38d36c31ccf684ed8":{
      "scriptId":"u31"},
    "d1d2416228944ba3a1ed05da18bcbc5c":{
      "scriptId":"u32"},
    "b04fa6996a4c49c0911f249376a28d65":{
      "scriptId":"u33"},
    "96d20bbbeb614c84b4ae283e7455f7c2":{
      "scriptId":"u34"},
    "bba9081f3db944a6a6589fbf500495d2":{
      "scriptId":"u35"},
    "799536cee0114ce9b1508621f77cd835":{
      "scriptId":"u36"},
    "8fddefa2efe84ccca7e112051b4e338b":{
      "scriptId":"u37"},
    "5dc829d94d6942fda50b1d4f550afc9f":{
      "scriptId":"u38"},
    "d8e3d8398848476cbd5011ea6274bf8a":{
      "scriptId":"u39"},
    "0fea08073c56490cabd03a1f66a0dfde":{
      "scriptId":"u40"},
    "13357b1154574956a2c2cbda3531c86b":{
      "scriptId":"u41"},
    "14061c6d7df74ea392fb26797d039720":{
      "scriptId":"u42"},
    "273f6bdacddf4a2a9df02ee55ec62224":{
      "scriptId":"u43"},
    "7f305995a251415dbe51a2b763ecce8f":{
      "scriptId":"u44"},
    "e79616aa82b04f8f9fbe4ece1880a88c":{
      "scriptId":"u45"},
    "7598bfe425394bfba7fa0ceaac0554c4":{
      "scriptId":"u46"}}});