$axure.loadCurrentPage({
  "url":"products-buy-content.html",
  "generationDate":new Date(1444814342415.87),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1bcb38c23abe4d3886f678b40230a7db",
    "type":"Axure:Page",
    "name":"Products-Buy-content",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"743c17ffc0b04e20ba5873bd371b1e4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":96},
            "size":{
              "width":720,
              "height":1744},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a0411617bc44f5fb5d7a8e5172eef53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":96},
                "size":{
                  "width":720,
                  "height":1744},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/products-buy-content/u0.png"}},
{
          "id":"5d21b5c73ac94a71a41fc18fc08d939f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":126},
            "size":{
              "width":720,
              "height":509},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b4961dd79c14801b48566ec505d1687",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":126},
                "size":{
                  "width":720,
                  "height":509},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/products-buy-content/u2.png"}},
{
          "id":"ad0bc699ea204c8094d1b2c94b89382d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF30A9EE},
            "location":{
              "x":374,
              "y":475},
            "size":{
              "width":308,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77af27814cf347a287bf1a4e062254e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF30A9EE},
                "location":{
                  "x":374,
                  "y":475},
                "size":{
                  "width":308,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDBDBDB},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/products-buy-content/u4.png"}},
{
          "id":"fd966d46144a40c4b43bc179a2a9adec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34d72bbecd97401bae482214852f1530",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"510def91cc3d41edb50a0480af2c0ca8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"990aa69c5bb94499b08f2212fa130964",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":14},
            "size":{
              "width":69,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20900899dedf48a28001a6a09c457a74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":14},
                "size":{
                  "width":69,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 products-buy",
                      "target":{
                        "targetType":"page",
                        "url":"products-buy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"20e84f3d01144e378cf960ed9c22ebe6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "location":{
              "x":279.5,
              "y":22},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bf86aadd0c94095a4f2bc0729af6b46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "location":{
                  "x":279.5,
                  "y":22},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33426d512bc04910861c667d111508d2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":122},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"71d49892f7bd4f68b8b4bc0621a5e9d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":666},
            "size":{
              "width":720,
              "height":1105},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae5bfbdd82f746ae8209937b2491c906",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":666},
                "size":{
                  "width":720,
                  "height":1105},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/products-buy-content/u14.png"}},
{
          "id":"6e9352ac4b2b41ad94a5a8a6a8d4d354",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"40px",
            "location":{
              "x":19,
              "y":693},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"394fea56320e44dba5eb8863b91e170f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"40px",
                "location":{
                  "x":19,
                  "y":693},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12bb6bcbcbb741979780c4bf8481640c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "lineSpacing":"60px",
            "location":{
              "x":19,
              "y":782},
            "size":{
              "width":462,
              "height":960}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4eec6a207a224657831f793e6632f149",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"60px",
                "location":{
                  "x":19,
                  "y":782},
                "size":{
                  "width":462,
                  "height":960}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dfed8636d22c41d88c3f1a732b4aef57",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1767},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"275bcaa837414344a0c9fb64bdf43b9d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":760},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"b0069a2d19144cd98e2c2585c8d7b3e9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":631},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"3b28a44b070d4d19b23409657ca0797a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":40,
              "y":475},
            "size":{
              "width":308,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0e79bb496584769942adda40789764b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":40,
                  "y":475},
                "size":{
                  "width":308,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDBDBDB},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/products-buy-content/u23.png"}},
{
          "id":"0eb32ec1705f4a97afa6474afee913d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":154,
              "y":497},
            "size":{
              "width":81,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e4344f966cf40eab3698d65e70a5415",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":497},
                "size":{
                  "width":81,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Products-Buy-toBuy",
                      "target":{
                        "targetType":"page",
                        "url":"products-buy-tobuy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b633aeac59e4b22984326e1edc4e28a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":488,
              "y":497},
            "size":{
              "width":81,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00e5cdf7a39747db9898a74bc0bedb1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":488,
                  "y":497},
                "size":{
                  "width":81,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Products-Buy-enquiry",
                      "target":{
                        "targetType":"page",
                        "url":"products-buy-enquiry.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f860826f568b44a7b74bf6323e61b457",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "lineSpacing":"72px",
            "location":{
              "x":38,
              "y":146},
            "size":{
              "width":421,
              "height":299}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a38066431d9648ce9722638cde98d8a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "lineSpacing":"72px",
                "location":{
                  "x":38,
                  "y":146},
                "size":{
                  "width":421,
                  "height":299}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40147bd1c8be4a64b327f451bfde2de2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":660},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"cb4e758e1f1c48c0b7398b03e130f937",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":578,
              "y":28},
            "size":{
              "width":123,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f971366ef0e4fd88232f481af510492",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":578,
                  "y":28},
                "size":{
                  "width":123,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Products-Buy-help",
                      "target":{
                        "targetType":"page",
                        "url":"products-buy-help.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "743c17ffc0b04e20ba5873bd371b1e4e":{
      "scriptId":"u0"},
    "5a0411617bc44f5fb5d7a8e5172eef53":{
      "scriptId":"u1"},
    "5d21b5c73ac94a71a41fc18fc08d939f":{
      "scriptId":"u2"},
    "7b4961dd79c14801b48566ec505d1687":{
      "scriptId":"u3"},
    "ad0bc699ea204c8094d1b2c94b89382d":{
      "scriptId":"u4"},
    "77af27814cf347a287bf1a4e062254e5":{
      "scriptId":"u5"},
    "fd966d46144a40c4b43bc179a2a9adec":{
      "scriptId":"u6"},
    "34d72bbecd97401bae482214852f1530":{
      "scriptId":"u7"},
    "510def91cc3d41edb50a0480af2c0ca8":{
      "scriptId":"u8"},
    "990aa69c5bb94499b08f2212fa130964":{
      "scriptId":"u9"},
    "20900899dedf48a28001a6a09c457a74":{
      "scriptId":"u10"},
    "20e84f3d01144e378cf960ed9c22ebe6":{
      "scriptId":"u11"},
    "7bf86aadd0c94095a4f2bc0729af6b46":{
      "scriptId":"u12"},
    "33426d512bc04910861c667d111508d2":{
      "scriptId":"u13"},
    "71d49892f7bd4f68b8b4bc0621a5e9d1":{
      "scriptId":"u14"},
    "ae5bfbdd82f746ae8209937b2491c906":{
      "scriptId":"u15"},
    "6e9352ac4b2b41ad94a5a8a6a8d4d354":{
      "scriptId":"u16"},
    "394fea56320e44dba5eb8863b91e170f":{
      "scriptId":"u17"},
    "12bb6bcbcbb741979780c4bf8481640c":{
      "scriptId":"u18"},
    "4eec6a207a224657831f793e6632f149":{
      "scriptId":"u19"},
    "dfed8636d22c41d88c3f1a732b4aef57":{
      "scriptId":"u20"},
    "275bcaa837414344a0c9fb64bdf43b9d":{
      "scriptId":"u21"},
    "b0069a2d19144cd98e2c2585c8d7b3e9":{
      "scriptId":"u22"},
    "3b28a44b070d4d19b23409657ca0797a":{
      "scriptId":"u23"},
    "d0e79bb496584769942adda40789764b":{
      "scriptId":"u24"},
    "0eb32ec1705f4a97afa6474afee913d4":{
      "scriptId":"u25"},
    "3e4344f966cf40eab3698d65e70a5415":{
      "scriptId":"u26"},
    "5b633aeac59e4b22984326e1edc4e28a":{
      "scriptId":"u27"},
    "00e5cdf7a39747db9898a74bc0bedb1a":{
      "scriptId":"u28"},
    "f860826f568b44a7b74bf6323e61b457":{
      "scriptId":"u29"},
    "a38066431d9648ce9722638cde98d8a1":{
      "scriptId":"u30"},
    "40147bd1c8be4a64b327f451bfde2de2":{
      "scriptId":"u31"},
    "cb4e758e1f1c48c0b7398b03e130f937":{
      "scriptId":"u32"},
    "9f971366ef0e4fd88232f481af510492":{
      "scriptId":"u33"}}});