$axure.loadCurrentPage({
  "url":"papers_upload2.html",
  "generationDate":new Date(1444814346590.11),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6ce278c44e40429c985e40a37e7e62c4",
    "type":"Axure:Page",
    "name":"Papers upload2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2cc1291d33e443c88e9914f2fcf2224d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":1188},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb5fead20d8d45b38ec2617914441eb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":92},
                "size":{
                  "width":720,
                  "height":1188},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about_company_edit/u0.png"}},
{
          "id":"51e5e34e07344f2cb8cb8b6cd5fbffbf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"284767146fb541e4be963b90a68724d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"3bb9b8b0d7d64791b2705194ce010c21",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"1095f64a53d94ca7a9657a46b27348b0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":14},
            "size":{
              "width":69,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"514d1250fb2b4ce7aa86c56b4557e17e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":14},
                "size":{
                  "width":69,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Papers upload",
                      "target":{
                        "targetType":"page",
                        "url":"papers_upload.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"85bd7475e8e646e99444b7fcdc78d81f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "location":{
              "x":280,
              "y":22},
            "size":{
              "width":179,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f39a4bb479da4585a02e1bc5649ab8a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "location":{
                  "x":280,
                  "y":22},
                "size":{
                  "width":179,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf7074b48f3a41a2b939f761274d4be9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "lineSpacing":"48px",
            "location":{
              "x":44,
              "y":986},
            "size":{
              "width":539,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0af72f7a996d428a82dd476ee5c59a95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"48px",
                "location":{
                  "x":44,
                  "y":986},
                "size":{
                  "width":539,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a7a84141a804c408afa5562c0cbb474",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":151},
            "size":{
              "width":640,
              "height":640},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15147083901b45ad9bbee705c4748f5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":151},
                "size":{
                  "width":640,
                  "height":640},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDBDBDB},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/papers_upload2/u11.png"}},
{
          "id":"b49e567fa21b44678718255b5f7fc87a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":351},
            "size":{
              "width":200,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57c48870753d4d8fbb8835af8afd0a03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":351},
                "size":{
                  "width":200,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/papers_upload2/u13.png"}},
{
          "id":"427158fdeb8f46e8aad9c551071e4b0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":375,
              "y":826},
            "size":{
              "width":305,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3aede3a58e984ae3b0aee38ecda52697",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":375,
                  "y":826},
                "size":{
                  "width":305,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDBDBDB},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/papers_upload2/u15.png"}},
{
          "id":"644787e9060e41bd91ef2a316f11bf21",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF30A9EE},
            "location":{
              "x":40,
              "y":826},
            "size":{
              "width":305,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5702e61fffb84524a040e8b8dc317f6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF30A9EE},
                "location":{
                  "x":40,
                  "y":826},
                "size":{
                  "width":305,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDBDBDB},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/papers_upload2/u17.png"}},
{
          "id":"8cc0b6d56f374e1381832813d05aff49",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":120,
              "y":851},
            "size":{
              "width":145,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db7298f3e7704d70a2320446227d7307",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":851},
                "size":{
                  "width":145,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58e4642d0a03414baeeb8900fa57431a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":455,
              "y":851},
            "size":{
              "width":145,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c920b6616ec48debea7563b7cadc1df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":455,
                  "y":851},
                "size":{
                  "width":145,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "2cc1291d33e443c88e9914f2fcf2224d":{
      "scriptId":"u0"},
    "cb5fead20d8d45b38ec2617914441eb4":{
      "scriptId":"u1"},
    "51e5e34e07344f2cb8cb8b6cd5fbffbf":{
      "scriptId":"u2"},
    "284767146fb541e4be963b90a68724d0":{
      "scriptId":"u3"},
    "3bb9b8b0d7d64791b2705194ce010c21":{
      "scriptId":"u4"},
    "1095f64a53d94ca7a9657a46b27348b0":{
      "scriptId":"u5"},
    "514d1250fb2b4ce7aa86c56b4557e17e":{
      "scriptId":"u6"},
    "85bd7475e8e646e99444b7fcdc78d81f":{
      "scriptId":"u7"},
    "f39a4bb479da4585a02e1bc5649ab8a7":{
      "scriptId":"u8"},
    "bf7074b48f3a41a2b939f761274d4be9":{
      "scriptId":"u9"},
    "0af72f7a996d428a82dd476ee5c59a95":{
      "scriptId":"u10"},
    "1a7a84141a804c408afa5562c0cbb474":{
      "scriptId":"u11"},
    "15147083901b45ad9bbee705c4748f5f":{
      "scriptId":"u12"},
    "b49e567fa21b44678718255b5f7fc87a":{
      "scriptId":"u13"},
    "57c48870753d4d8fbb8835af8afd0a03":{
      "scriptId":"u14"},
    "427158fdeb8f46e8aad9c551071e4b0c":{
      "scriptId":"u15"},
    "3aede3a58e984ae3b0aee38ecda52697":{
      "scriptId":"u16"},
    "644787e9060e41bd91ef2a316f11bf21":{
      "scriptId":"u17"},
    "5702e61fffb84524a040e8b8dc317f6d":{
      "scriptId":"u18"},
    "8cc0b6d56f374e1381832813d05aff49":{
      "scriptId":"u19"},
    "db7298f3e7704d70a2320446227d7307":{
      "scriptId":"u20"},
    "58e4642d0a03414baeeb8900fa57431a":{
      "scriptId":"u21"},
    "3c920b6616ec48debea7563b7cadc1df":{
      "scriptId":"u22"}}});