$axure.loadCurrentPage({
  "url":"orders-buy-content.html",
  "generationDate":new Date(1444814344215.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"dd1f8387884b4fdc8b577632ea1e0afc",
    "type":"Axure:Page",
    "name":"Orders-buy-content",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"562d73c1285a4861a1b2ab8a600ca918",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":14},
            "size":{
              "width":720,
              "height":2106},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4283d92038d64e5b9bf7a9440680ea4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":14},
                "size":{
                  "width":720,
                  "height":2106},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-buy-content/u0.png"}},
{
          "id":"3e0e6f86b7564afd9ef05ebfe2e207d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c381a852bbf248938bf25949ced34d1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"c38fdd053075407c88069e625241d43d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"b50a1a91380948b384b12c49023cf10a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":14},
            "size":{
              "width":69,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ca34ad35a634bb88b13455d0e5079ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":14},
                "size":{
                  "width":69,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Orders-buy",
                      "target":{
                        "targetType":"page",
                        "url":"orders-buy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"3052640e132545cf81f5fd972ed89ab8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "location":{
              "x":280,
              "y":22},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc89ee1266ce4cab8ee15fd894fd1bc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "location":{
                  "x":280,
                  "y":22},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce27b8f67c164f3e9becfd0cc515a52c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":136},
            "size":{
              "width":720,
              "height":904},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1405fd0da29416180dcd7b177a5b889",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":136},
                "size":{
                  "width":720,
                  "height":904},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-buy-content/u9.png"}},
{
          "id":"61de606d75c941b7b74d36345b6c1e36",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":130},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"6b5319dfcfdf4a71afb2f8d4ccc6fb36",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1035},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"9872c1b9aaf041a4be76f702a1aa43bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1076},
            "size":{
              "width":720,
              "height":1007},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83ff5221018b44c1a099560c7e9ca9a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1076},
                "size":{
                  "width":720,
                  "height":1007},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-buy-content/u13.png"}},
{
          "id":"8b67355d848b45b7843b603c7c735c9e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":2078},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"8139ae7943e34344b55e365fbab46b7b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1070},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"072bc328897c4a258a76d43dbe0b4ca9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"40px",
            "location":{
              "x":19,
              "y":1100},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"354f17cea56c4b38a1eafd377facc24e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"40px",
                "location":{
                  "x":19,
                  "y":1100},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cfbbd0a2564948cc82cc1bacc2bd8e11",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "lineSpacing":"60px",
            "location":{
              "x":19,
              "y":1189},
            "size":{
              "width":462,
              "height":840}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fcaf020d08846bfadb87cc961f2d3b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"60px",
                "location":{
                  "x":19,
                  "y":1189},
                "size":{
                  "width":462,
                  "height":840}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0fdd99d54a55419db76fd4cc1ad2f76d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1161},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"ea91aa31b05a43b8b4bbee01a981a0ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "lineSpacing":"60px",
            "location":{
              "x":31,
              "y":291},
            "size":{
              "width":397,
              "height":720}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12401ded626c467590815f379dad6562",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "lineSpacing":"60px",
                "location":{
                  "x":31,
                  "y":291},
                "size":{
                  "width":397,
                  "height":720}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"742f22b494204670b742f8e56a8896ba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":158},
            "size":{
              "width":720,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21888b708581491ab5ef8bb500827bc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":158},
                "size":{
                  "width":720,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-buy-content/u24.png"}},
{
          "id":"f3c0eaf614da494e8d76e2b81b72a823",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":269},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"9dc7ff85aed34ccc83244f9ca01f6ff6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":28,
              "y":214},
            "size":{
              "width":665,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72824e9ed05c4985a0082dbe8afa9e31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":28,
                  "y":214},
                "size":{
                  "width":665,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "562d73c1285a4861a1b2ab8a600ca918":{
      "scriptId":"u0"},
    "4283d92038d64e5b9bf7a9440680ea4a":{
      "scriptId":"u1"},
    "3e0e6f86b7564afd9ef05ebfe2e207d1":{
      "scriptId":"u2"},
    "c381a852bbf248938bf25949ced34d1c":{
      "scriptId":"u3"},
    "c38fdd053075407c88069e625241d43d":{
      "scriptId":"u4"},
    "b50a1a91380948b384b12c49023cf10a":{
      "scriptId":"u5"},
    "8ca34ad35a634bb88b13455d0e5079ab":{
      "scriptId":"u6"},
    "3052640e132545cf81f5fd972ed89ab8":{
      "scriptId":"u7"},
    "fc89ee1266ce4cab8ee15fd894fd1bc6":{
      "scriptId":"u8"},
    "ce27b8f67c164f3e9becfd0cc515a52c":{
      "scriptId":"u9"},
    "b1405fd0da29416180dcd7b177a5b889":{
      "scriptId":"u10"},
    "61de606d75c941b7b74d36345b6c1e36":{
      "scriptId":"u11"},
    "6b5319dfcfdf4a71afb2f8d4ccc6fb36":{
      "scriptId":"u12"},
    "9872c1b9aaf041a4be76f702a1aa43bf":{
      "scriptId":"u13"},
    "83ff5221018b44c1a099560c7e9ca9a7":{
      "scriptId":"u14"},
    "8b67355d848b45b7843b603c7c735c9e":{
      "scriptId":"u15"},
    "8139ae7943e34344b55e365fbab46b7b":{
      "scriptId":"u16"},
    "072bc328897c4a258a76d43dbe0b4ca9":{
      "scriptId":"u17"},
    "354f17cea56c4b38a1eafd377facc24e":{
      "scriptId":"u18"},
    "cfbbd0a2564948cc82cc1bacc2bd8e11":{
      "scriptId":"u19"},
    "2fcaf020d08846bfadb87cc961f2d3b1":{
      "scriptId":"u20"},
    "0fdd99d54a55419db76fd4cc1ad2f76d":{
      "scriptId":"u21"},
    "ea91aa31b05a43b8b4bbee01a981a0ec":{
      "scriptId":"u22"},
    "12401ded626c467590815f379dad6562":{
      "scriptId":"u23"},
    "742f22b494204670b742f8e56a8896ba":{
      "scriptId":"u24"},
    "21888b708581491ab5ef8bb500827bc2":{
      "scriptId":"u25"},
    "f3c0eaf614da494e8d76e2b81b72a823":{
      "scriptId":"u26"},
    "9dc7ff85aed34ccc83244f9ca01f6ff6":{
      "scriptId":"u27"},
    "72824e9ed05c4985a0082dbe8afa9e31":{
      "scriptId":"u28"}}});