$axure.loadCurrentPage({
  "url":"mysale-plan.html",
  "generationDate":new Date(1444814345340.04),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3f053b718e4b4caca46ef1933bd0fc6b",
    "type":"Axure:Page",
    "name":"MySale-plan",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fbc6efcb74a64df7b6add059fb6b5223",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":1378},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9d3b99c836a49888674d8138504793c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":92},
                "size":{
                  "width":720,
                  "height":1378},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mysale-plan/u0.png"}},
{
          "id":"4d86037981504b4b88eb1c1b52051435",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"071fe6443b6e4e8c89d91b86148da10b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"3b455c87fede40c6b1184ebc191fc987",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":92},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"cd23f04c0a6e442aa1d4ed492b4a68da",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":14},
            "size":{
              "width":69,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"595f0fb7fce04827b0732cd0c8d705ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":14},
                "size":{
                  "width":69,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 UserConter-release",
                      "target":{
                        "targetType":"page",
                        "url":"userconter-release.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"79e13cb4247d499794de129dba848089",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"40px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "location":{
              "x":280,
              "y":22},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"830f0741858a44a588e09bf739f91155",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"40px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "location":{
                  "x":280,
                  "y":22},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d87bfac3c91b409bab12ab4ecd9c5ec3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":131},
            "size":{
              "width":720,
              "height":694},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"132f41522e404a86b67dd75df1db0e3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":131},
                "size":{
                  "width":720,
                  "height":694},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mysale-plan/u9.png"}},
{
          "id":"2968c9ddd7384554a6ac642686952e97",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "lineSpacing":"60px",
            "location":{
              "x":27,
              "y":264},
            "size":{
              "width":374,
              "height":540}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75da165809194529a5b86022dcffc017",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "lineSpacing":"60px",
                "location":{
                  "x":27,
                  "y":264},
                "size":{
                  "width":374,
                  "height":540}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 MySale-content",
                      "target":{
                        "targetType":"page",
                        "url":"mysale-content.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"857c363f02a34af5bc110b41387c4839",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":125},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"f871bf38d2d44c0482109919e86ac0f5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":819},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"bca2d8f4bf3a4c818d9aa0c2ee3e2b25",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":581,
              "y":30},
            "size":{
              "width":113,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d32a2b059e37428a9bd24f2f33214850",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":581,
                  "y":30},
                "size":{
                  "width":113,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 release-sale",
                      "target":{
                        "targetType":"page",
                        "url":"release-sale.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"080de4341e1043b79c1ecead1e66b335",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":521,
              "y":23},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38a6a1e9adb64a618e194cb75d6e7bff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":521,
                  "y":23},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u18.png"}},
{
          "id":"7814e1ff5e054acd885184eae08744d9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":247},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"1666a0daad7a4271aab1ce4497405667",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":853},
            "size":{
              "width":720,
              "height":573},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7777571b93eb47daa1d7c33a25577d98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":853},
                "size":{
                  "width":720,
                  "height":573},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mysale-plan/u20.png"}},
{
          "id":"15523bbc24e94dc0807c54639fd4f018",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "lineSpacing":"60px",
            "location":{
              "x":27,
              "y":865},
            "size":{
              "width":374,
              "height":540}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb1d78763b904a97ac69edb1fc687ff2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "lineSpacing":"60px",
                "location":{
                  "x":27,
                  "y":865},
                "size":{
                  "width":374,
                  "height":540}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a8091e017b4d4420a6adb8f20939e8be",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1420},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"91d31c4929e441589ec3e0b795eb14cf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":848},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"5eea212ecb0949008a51500a48b23f22",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":151},
            "size":{
              "width":485,
              "height":80},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78d19b521c164d5eb56636491bfab693",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":151},
                "size":{
                  "width":485,
                  "height":80},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-plan/u46.png"}},
{
          "id":"f7995199f09844aab9c778c22364ebee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":528,
              "y":151},
            "size":{
              "width":164,
              "height":80},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9823fde41df4871946685584475350c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":528,
                  "y":151},
                "size":{
                  "width":164,
                  "height":80},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDBDBDB},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-plan/u48.png"}},
{
          "id":"38879de8c8a14c818fbc26fb1287b787",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":574,
              "y":168},
            "size":{
              "width":73,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dd673eee45d40459791ad4bb1ec3817",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":574,
                  "y":168},
                "size":{
                  "width":73,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "fbc6efcb74a64df7b6add059fb6b5223":{
      "scriptId":"u0"},
    "c9d3b99c836a49888674d8138504793c":{
      "scriptId":"u1"},
    "4d86037981504b4b88eb1c1b52051435":{
      "scriptId":"u2"},
    "071fe6443b6e4e8c89d91b86148da10b":{
      "scriptId":"u3"},
    "3b455c87fede40c6b1184ebc191fc987":{
      "scriptId":"u4"},
    "cd23f04c0a6e442aa1d4ed492b4a68da":{
      "scriptId":"u5"},
    "595f0fb7fce04827b0732cd0c8d705ac":{
      "scriptId":"u6"},
    "79e13cb4247d499794de129dba848089":{
      "scriptId":"u7"},
    "830f0741858a44a588e09bf739f91155":{
      "scriptId":"u8"},
    "d87bfac3c91b409bab12ab4ecd9c5ec3":{
      "scriptId":"u9"},
    "132f41522e404a86b67dd75df1db0e3d":{
      "scriptId":"u10"},
    "2968c9ddd7384554a6ac642686952e97":{
      "scriptId":"u11"},
    "75da165809194529a5b86022dcffc017":{
      "scriptId":"u12"},
    "857c363f02a34af5bc110b41387c4839":{
      "scriptId":"u13"},
    "f871bf38d2d44c0482109919e86ac0f5":{
      "scriptId":"u14"},
    "bca2d8f4bf3a4c818d9aa0c2ee3e2b25":{
      "scriptId":"u15"},
    "d32a2b059e37428a9bd24f2f33214850":{
      "scriptId":"u16"},
    "080de4341e1043b79c1ecead1e66b335":{
      "scriptId":"u17"},
    "38a6a1e9adb64a618e194cb75d6e7bff":{
      "scriptId":"u18"},
    "7814e1ff5e054acd885184eae08744d9":{
      "scriptId":"u19"},
    "1666a0daad7a4271aab1ce4497405667":{
      "scriptId":"u20"},
    "7777571b93eb47daa1d7c33a25577d98":{
      "scriptId":"u21"},
    "15523bbc24e94dc0807c54639fd4f018":{
      "scriptId":"u22"},
    "fb1d78763b904a97ac69edb1fc687ff2":{
      "scriptId":"u23"},
    "a8091e017b4d4420a6adb8f20939e8be":{
      "scriptId":"u24"},
    "91d31c4929e441589ec3e0b795eb14cf":{
      "scriptId":"u25"},
    "5eea212ecb0949008a51500a48b23f22":{
      "scriptId":"u26"},
    "78d19b521c164d5eb56636491bfab693":{
      "scriptId":"u27"},
    "f7995199f09844aab9c778c22364ebee":{
      "scriptId":"u28"},
    "f9823fde41df4871946685584475350c":{
      "scriptId":"u29"},
    "38879de8c8a14c818fbc26fb1287b787":{
      "scriptId":"u30"},
    "8dd673eee45d40459791ad4bb1ec3817":{
      "scriptId":"u31"}}});