$axure.loadCurrentPage({
  "url":"userconter-orders.html",
  "generationDate":new Date(1444814343791.95),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"53538689eca94c1eb9f3fcbc7c9c2f75",
    "type":"Axure:Page",
    "name":"UserConter-orders",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6231d46924004e3b9fa9f607ae60f99b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFEF},
            "location":{
              "x":0,
              "y":963},
            "size":{
              "width":720,
              "height":221},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae57967ac2854f47b47b06c37937b7d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFEF},
                "location":{
                  "x":0,
                  "y":963},
                "size":{
                  "width":720,
                  "height":221},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-orders/u0.png"}},
{
          "id":"612d0b2ce05b4a0dac9c749b891b21b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0094DE},
            "size":{
              "width":720,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6ead6185f934f12a11c3ff48c4b616c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0094DE},
                "size":{
                  "width":720,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-orders/u2.png"}},
{
          "id":"f84b91b5654744abb5bbc693d90a9d9b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":16},
            "size":{
              "width":216,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7f5c33588e841a5bfa8d57f9ab4bae4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":16},
                "size":{
                  "width":216,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u6.png"}},
{
          "id":"0e81ab76d45947a4846fa31a951edf48",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":637,
              "y":23},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4781c7f00cc44a02b4b109b9f2137ee5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":637,
                  "y":23},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 About User",
                      "target":{
                        "targetType":"page",
                        "url":"about_user.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u28.png"}},
{
          "id":"677d61ae2ac244db80a77ec8cdcf3012",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":0,
              "y":1073},
            "size":{
              "width":720,
              "height":108},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0094DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e997acfda0904e55af6ff2c218b24f75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":0,
                  "y":1073},
                "size":{
                  "width":720,
                  "height":108},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0094DE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-orders/u8.png"}},
{
          "id":"043798c9d6994544a96cd95cc365815c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1066},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"fee8ad6026fd46b3b8a231daf78a32d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":535,
              "y":29.5},
            "size":{
              "width":85,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b70cfeb19e2496da9af86ccf8c126c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":535,
                  "y":29.5},
                "size":{
                  "width":85,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b7c71eac4f74def9e8ed30618d2f31a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"26px",
            "location":{
              "x":74,
              "y":1138},
            "size":{
              "width":572,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"112e4100547f4bc893b83be2f39ca605",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"26px",
                "location":{
                  "x":74,
                  "y":1138},
                "size":{
                  "width":572,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9f2938e34d94a87ab99597945e21e00",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":1085},
            "size":{
              "width":49,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"357c5b3982a941579e0fa74013c60c54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":1085},
                "size":{
                  "width":49,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-orders/u15.png"}},
{
          "id":"27e99e61950f402f9b11dcd95c7353e5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":1086},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"356d72a8636e4f0988e3db983dd3e747",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":249,
                  "y":1086},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 UserConter-release",
                      "target":{
                        "targetType":"page",
                        "url":"userconter-release.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/userconter-orders/u17.png"}},
{
          "id":"5204f3393abe4864ba5a2a2c24a0b70b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":419,
              "y":1086},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e13d87d367824fc897c227f809bc27c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":419,
                  "y":1086},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 UserConter-my",
                      "target":{
                        "targetType":"page",
                        "url":"userconter-my.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/userconter-orders/u19.png"}},
{
          "id":"6324740113fe4a02ab90f6428801e990",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":1086},
            "size":{
              "width":56,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46618e584e5f4edda9d4659a95cc3a92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":1086},
                "size":{
                  "width":56,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/userconter-orders/u21.png"}},
{
          "id":"a90523b046174ae7b7d3f45a83c5b65f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":129,
              "y":169},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d904f198f27e4e43ab2c1ca7dd399807",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":129,
                  "y":169},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-orders/u23.png"}},
{
          "id":"002006d0e32e4859b6df5966a08a7d21",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":169},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc5169ba67c241a99922a523cd6f2056",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":169},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-orders/u23.png"}},
{
          "id":"93b9b79db30849f896cab0a90ca6c7cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":107,
              "y":280},
            "size":{
              "width":145,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feb016f9c632413e8d0aefc1b37a9949",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":107,
                  "y":280},
                "size":{
                  "width":145,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Orders-buy",
                      "target":{
                        "targetType":"page",
                        "url":"orders-buy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9fcd22a1839442bbf8ec09a2bb7b736",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":468,
              "y":280},
            "size":{
              "width":145,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc3c236cf4584b2cbe3a801d08818a90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":468,
                  "y":280},
                "size":{
                  "width":145,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Orders-sale",
                      "target":{
                        "targetType":"page",
                        "url":"orders-sale.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff1e41281cee40cf81e5eda4474ad3e7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":380},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"6c136c8ae920477889bb98108a530731",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":129,
              "y":456},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c52d29dfeb9646b8a26031104b1f34b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":129,
                  "y":456},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-orders/u23.png"}},
{
          "id":"aeace8895cb045d2a9d87a06cde04a3c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":456},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e63df82a93654e6194d2ac02d97c5664",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":456},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-orders/u23.png"}},
{
          "id":"a00b77950d7a471da0aefdba8f595a6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":107,
              "y":567},
            "size":{
              "width":145,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8574b25c7ff34126b4d6e465960ac81b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":107,
                  "y":567},
                "size":{
                  "width":145,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Orders-plan",
                      "target":{
                        "targetType":"page",
                        "url":"orders-plan.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"778af625c8e442dca379b3d2bfb30a3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":468,
              "y":567},
            "size":{
              "width":145,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eaf7889b59a2441d8634fa65706012d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":468,
                  "y":567},
                "size":{
                  "width":145,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ddb9b1a1b53a4d54a1a8b4890731f250",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":671},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"3c901a3a0c7041f68b062fc1fef22b71",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":129,
              "y":744},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e9b84ab4441472182dbd262e312ef18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":129,
                  "y":744},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-orders/u23.png"}},
{
          "id":"d531018f90d34369b367a932bc2c390d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":744},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f70af3db94643d6b9510458d2396615",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":744},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userconter-orders/u23.png"}},
{
          "id":"ca513ea2e1cc4026ab7daad7b5fecba7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":107,
              "y":855},
            "size":{
              "width":145,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f144c569e06e4961ac6c6d11e6430441",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":107,
                  "y":855},
                "size":{
                  "width":145,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c2242380adf4514b3fe5bfd48812e59",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":468,
              "y":855},
            "size":{
              "width":145,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d22579a6fef40cc9dabf7dfc348c9ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":468,
                  "y":855},
                "size":{
                  "width":145,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Orders-contract",
                      "target":{
                        "targetType":"page",
                        "url":"orders-contract.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f4c1e0c524a4919936fcc1540e2726e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":959},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u38_line.png"}},
{
          "id":"d1e6e96416b5429285bb5ae6a08d8812",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":355,
              "y":96},
            "size":{
              "width":10,
              "height":868},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/userconter-orders/u50_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "6231d46924004e3b9fa9f607ae60f99b":{
      "scriptId":"u0"},
    "ae57967ac2854f47b47b06c37937b7d7":{
      "scriptId":"u1"},
    "612d0b2ce05b4a0dac9c749b891b21b8":{
      "scriptId":"u2"},
    "c6ead6185f934f12a11c3ff48c4b616c":{
      "scriptId":"u3"},
    "f84b91b5654744abb5bbc693d90a9d9b":{
      "scriptId":"u4"},
    "b7f5c33588e841a5bfa8d57f9ab4bae4":{
      "scriptId":"u5"},
    "0e81ab76d45947a4846fa31a951edf48":{
      "scriptId":"u6"},
    "4781c7f00cc44a02b4b109b9f2137ee5":{
      "scriptId":"u7"},
    "677d61ae2ac244db80a77ec8cdcf3012":{
      "scriptId":"u8"},
    "e997acfda0904e55af6ff2c218b24f75":{
      "scriptId":"u9"},
    "043798c9d6994544a96cd95cc365815c":{
      "scriptId":"u10"},
    "fee8ad6026fd46b3b8a231daf78a32d5":{
      "scriptId":"u11"},
    "5b70cfeb19e2496da9af86ccf8c126c0":{
      "scriptId":"u12"},
    "0b7c71eac4f74def9e8ed30618d2f31a":{
      "scriptId":"u13"},
    "112e4100547f4bc893b83be2f39ca605":{
      "scriptId":"u14"},
    "e9f2938e34d94a87ab99597945e21e00":{
      "scriptId":"u15"},
    "357c5b3982a941579e0fa74013c60c54":{
      "scriptId":"u16"},
    "27e99e61950f402f9b11dcd95c7353e5":{
      "scriptId":"u17"},
    "356d72a8636e4f0988e3db983dd3e747":{
      "scriptId":"u18"},
    "5204f3393abe4864ba5a2a2c24a0b70b":{
      "scriptId":"u19"},
    "e13d87d367824fc897c227f809bc27c6":{
      "scriptId":"u20"},
    "6324740113fe4a02ab90f6428801e990":{
      "scriptId":"u21"},
    "46618e584e5f4edda9d4659a95cc3a92":{
      "scriptId":"u22"},
    "a90523b046174ae7b7d3f45a83c5b65f":{
      "scriptId":"u23"},
    "d904f198f27e4e43ab2c1ca7dd399807":{
      "scriptId":"u24"},
    "002006d0e32e4859b6df5966a08a7d21":{
      "scriptId":"u25"},
    "bc5169ba67c241a99922a523cd6f2056":{
      "scriptId":"u26"},
    "93b9b79db30849f896cab0a90ca6c7cc":{
      "scriptId":"u27"},
    "feb016f9c632413e8d0aefc1b37a9949":{
      "scriptId":"u28"},
    "b9fcd22a1839442bbf8ec09a2bb7b736":{
      "scriptId":"u29"},
    "dc3c236cf4584b2cbe3a801d08818a90":{
      "scriptId":"u30"},
    "ff1e41281cee40cf81e5eda4474ad3e7":{
      "scriptId":"u31"},
    "6c136c8ae920477889bb98108a530731":{
      "scriptId":"u32"},
    "c52d29dfeb9646b8a26031104b1f34b4":{
      "scriptId":"u33"},
    "aeace8895cb045d2a9d87a06cde04a3c":{
      "scriptId":"u34"},
    "e63df82a93654e6194d2ac02d97c5664":{
      "scriptId":"u35"},
    "a00b77950d7a471da0aefdba8f595a6e":{
      "scriptId":"u36"},
    "8574b25c7ff34126b4d6e465960ac81b":{
      "scriptId":"u37"},
    "778af625c8e442dca379b3d2bfb30a3c":{
      "scriptId":"u38"},
    "eaf7889b59a2441d8634fa65706012d6":{
      "scriptId":"u39"},
    "ddb9b1a1b53a4d54a1a8b4890731f250":{
      "scriptId":"u40"},
    "3c901a3a0c7041f68b062fc1fef22b71":{
      "scriptId":"u41"},
    "8e9b84ab4441472182dbd262e312ef18":{
      "scriptId":"u42"},
    "d531018f90d34369b367a932bc2c390d":{
      "scriptId":"u43"},
    "1f70af3db94643d6b9510458d2396615":{
      "scriptId":"u44"},
    "ca513ea2e1cc4026ab7daad7b5fecba7":{
      "scriptId":"u45"},
    "f144c569e06e4961ac6c6d11e6430441":{
      "scriptId":"u46"},
    "9c2242380adf4514b3fe5bfd48812e59":{
      "scriptId":"u47"},
    "8d22579a6fef40cc9dabf7dfc348c9ba":{
      "scriptId":"u48"},
    "9f4c1e0c524a4919936fcc1540e2726e":{
      "scriptId":"u49"},
    "d1e6e96416b5429285bb5ae6a08d8812":{
      "scriptId":"u50"}}});